! (C) Copyright 2026- ECMWF and individual contributors.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation nor
! does it submit to any jurisdiction.

!> tensogram — Fortran 2008 interface to the Tensogram C ABI (libtensogram).
!> The rank-generic surface is built from explicit per-rank specifics, expanded
!> by the C preprocessor from src/tgm_*.inc (a `.F90` source), so the LIBRARY
!> compiles clean under `-std=f2008 -Wall -Wextra -Werror` — no assumed-rank or
!> SELECT RANK (both F2018). The `contiguous` attribute it leans on is F2008.
!>
!> gfortran note: the handle types pair a `final` procedure with default
!> initialization (the RAII + null-safety design, §5.4). That is valid F2008,
!> but gfortran's `-std=f2008` emits an f08/0011 advisory wherever such a type
!> appears as a LOCAL variable (application/test code, not this library). The
!> library itself has no such locals and stays warning-clean; consumers who
!> compile their own code with `-std=f2008 -Werror` should expect that advisory
!> (or use `-std=f2018`/`-std=gnu`).
!>
!> Shallow binding: a private `bind(C)` interface block mirrors the synchronous
!> subset of `tensogram.h`; the public `tensogram_*` procedures add idiomatic
!> Fortran strings, ownership (finalizers), the memory-order contract, and a
!> non-copyable handle guard.
!>
!> GENERIC ENCODE / DECODE
!>   `tensogram_encode` and `tensogram_to_array` are generic over dtype
!>   (real32, real64, int32, int64) and rank (0..7), via explicit per-rank
!>   specifics generated by the C preprocessor (src/tgm_ranks.inc drives the
!>   per-family templates). Ranks above 7 are a compile-time "no specific"
!>   error (vs. a runtime TGM_ERROR_OBJECT). (int8/int16/complex/float16 are
!>   documented follow-ups; Fortran has no native unsigned or half/complex-as-
!>   pairs scalar mapping.)
!>
!> MEMORY-ORDER CONTRACT
!>   A Fortran array `a(ni, nj, ...)` is written with the on-wire descriptor
!>   shape and strides REVERSED to C/row-major order. Consequences:
!>     * Round-trips Fortran <-> Fortran are bit-identical.
!>     * A NumPy / C reader sees the reversed (transposed) shape.
!>
!> OWNERSHIP / LIFETIMES (non-copyable owning-handle approach)
!>   `tensogram_buffer`  owns Rust-allocated encoded bytes (tgm_bytes_free).
!>   `tensogram_message` owns a decoded message handle  (tgm_message_free).
!>   Both free in a `final` procedure and via an idempotent `free` binding.
!>   The types are NON-COPYABLE: a defined `assignment(=)` calls `error stop`,
!>   so an accidental `b = a` aborts loudly at the copy site instead of
!>   aliasing the handle and double-freeing later. Pass handles by reference.
module tensogram
   use, intrinsic :: iso_c_binding
   use, intrinsic :: iso_fortran_env, only : error_unit
   implicit none
   private

   ! ---- Public API ---------------------------------------------------------
   public :: tensogram_buffer, tensogram_message
   public :: tensogram_encode      !> generic: real32/64, int32/64, rank 0..7
   public :: tensogram_decode
   public :: tensogram_to_array    !> generic: real32/64, int32/64, rank 0..7
   public :: tensogram_file
   public :: tensogram_file_open, tensogram_file_create
   public :: tensogram_file_message_count
   public :: tensogram_file_append   !> generic: real32/64, int32/64, rank 0..7
   public :: tensogram_file_decode_message, tensogram_file_read_message
   public :: tensogram_meta            !> build per-object application metadata
   public :: tensogram_metadata, tensogram_message_metadata
   public :: tensogram_metadata_get_string, tensogram_metadata_get_int
   public :: tensogram_metadata_get_float
   !> Precise (no-coercion) metadata access — existence, typed try-get,
   !> enumeration and nested/array navigation via the borrowed value cursor.
   public :: tensogram_value
   public :: tensogram_metadata_has, tensogram_metadata_get
   public :: tensogram_metadata_try_get_int, tensogram_metadata_try_get_float
   public :: tensogram_metadata_try_get_string, tensogram_metadata_try_get_bool
   public :: tensogram_metadata_object, tensogram_metadata_extra
   public :: tensogram_metadata_reserved, tensogram_metadata_num_objects
   public :: TGM_VALUE_TYPE_NULL, TGM_VALUE_TYPE_BOOL, TGM_VALUE_TYPE_INT,   &
             TGM_VALUE_TYPE_FLOAT, TGM_VALUE_TYPE_STRING, TGM_VALUE_TYPE_BYTES, &
             TGM_VALUE_TYPE_ARRAY, TGM_VALUE_TYPE_MAP
   public :: tensogram_streaming_encoder
   public :: tensogram_streaming_encoder_create, tensogram_streaming_encoder_write
   public :: tensogram_streaming_encoder_finish, tensogram_streaming_encoder_count
   public :: tensogram_num_objects, tensogram_object_ndim
   public :: tensogram_object_shape, tensogram_object_dtype
   public :: tensogram_strerror, tensogram_last_error, tensogram_check
   public :: TGM_ERROR_OK, TGM_ERROR_FRAMING, TGM_ERROR_METADATA,            &
             TGM_ERROR_ENCODING, TGM_ERROR_COMPRESSION, TGM_ERROR_OBJECT,    &
             TGM_ERROR_IO, TGM_ERROR_HASH_MISMATCH, TGM_ERROR_INVALID_ARG,   &
             TGM_ERROR_END_OF_ITER, TGM_ERROR_REMOTE, TGM_ERROR_MISSING_HASH,&
             TGM_ERROR_TIMEOUT, TGM_ERROR_CANCELLED

   ! ---- tgm_error enum — mirror of tensogram.h (CI checks they match) ------
   integer(c_int), parameter :: TGM_ERROR_OK            = 0
   integer(c_int), parameter :: TGM_ERROR_FRAMING       = 1
   integer(c_int), parameter :: TGM_ERROR_METADATA      = 2
   integer(c_int), parameter :: TGM_ERROR_ENCODING      = 3
   integer(c_int), parameter :: TGM_ERROR_COMPRESSION   = 4
   integer(c_int), parameter :: TGM_ERROR_OBJECT        = 5
   integer(c_int), parameter :: TGM_ERROR_IO            = 6
   integer(c_int), parameter :: TGM_ERROR_HASH_MISMATCH = 7
   integer(c_int), parameter :: TGM_ERROR_INVALID_ARG   = 8
   integer(c_int), parameter :: TGM_ERROR_END_OF_ITER   = 9
   integer(c_int), parameter :: TGM_ERROR_REMOTE        = 10
   integer(c_int), parameter :: TGM_ERROR_MISSING_HASH  = 11
   integer(c_int), parameter :: TGM_ERROR_TIMEOUT       = 12
   integer(c_int), parameter :: TGM_ERROR_CANCELLED     = 13

   ! ---- tgm_value_type enum — mirror of tensogram.h (header order) ---------
   !  The kind of a metadata value handle. CBOR integers are i128-backed and
   !  surface as the single TGM_VALUE_TYPE_INT; use %as_int / %as_uint to
   !  extract with range checking.
   integer(c_int), parameter :: TGM_VALUE_TYPE_NULL   = 0
   integer(c_int), parameter :: TGM_VALUE_TYPE_BOOL   = 1
   integer(c_int), parameter :: TGM_VALUE_TYPE_INT    = 2
   integer(c_int), parameter :: TGM_VALUE_TYPE_FLOAT  = 3
   integer(c_int), parameter :: TGM_VALUE_TYPE_STRING = 4
   integer(c_int), parameter :: TGM_VALUE_TYPE_BYTES  = 5
   integer(c_int), parameter :: TGM_VALUE_TYPE_ARRAY  = 6
   integer(c_int), parameter :: TGM_VALUE_TYPE_MAP    = 7

   ! ---- Interoperable POD struct: tgm_bytes_t ------------------------------
   type, bind(C) :: tgm_bytes_t
      type(c_ptr)       :: data = c_null_ptr
      integer(c_size_t) :: len  = 0_c_size_t
   end type tgm_bytes_t

   ! ---- Owned encoded buffer (RAII over tgm_bytes_t) -----------------------
   type :: tensogram_buffer
      type(tgm_bytes_t), private :: raw
   contains
      procedure :: as_array => buffer_as_array
      procedure :: size     => buffer_size
      procedure :: free     => buffer_free
      procedure, private :: buffer_assign
      generic, public :: assignment(=) => buffer_assign
      final     :: buffer_final
   end type tensogram_buffer

   ! ---- Owned decoded message (RAII over tgm_message_t*) -------------------
   type :: tensogram_message
      type(c_ptr), private :: ptr = c_null_ptr
   contains
      procedure :: free => message_free
      procedure, private :: message_assign
      generic, public :: assignment(=) => message_assign
      final     :: message_final
   end type tensogram_message

   ! ---- Owned file handle (RAII over tgm_file_t*) --------------------------
   type :: tensogram_file
      type(c_ptr), private :: ptr = c_null_ptr
   contains
      procedure :: close => file_close
      procedure, private :: file_assign
      generic, public :: assignment(=) => file_assign
      final     :: file_final
   end type tensogram_file

   ! ---- Application-metadata builder (one object's `base[i]` entry) ---------
   !  Accumulate key/value pairs (zero-dependency, JSON-escaped) and emit a
   !  `"base":[{...}]` fragment to pass as `metadata_json` on encode/append.
   type :: tensogram_meta
      character(len=:), allocatable, private :: body
   contains
      procedure :: add_string => meta_add_string
      procedure :: add_int    => meta_add_int
      procedure :: add_real   => meta_add_real
      procedure :: base_json  => meta_base_json
   end type tensogram_meta

   ! ---- Owned metadata handle (RAII over tgm_metadata_t*) ------------------
   type :: tensogram_metadata
      type(c_ptr), private :: ptr = c_null_ptr
   contains
      procedure :: free => metadata_free
      procedure, private :: metadata_assign
      generic, public :: assignment(=) => metadata_assign
      final     :: metadata_final
   end type tensogram_metadata

   ! ---- Borrowed metadata value cursor (tgm_value_t) -----------------------
   !  A NON-OWNING view into a parent tensogram_metadata: existence, typed
   !  extraction, enumeration and nested/array navigation, all zero-copy. The
   !  handle (and any string/bytes it lends) is borrowed and valid only until
   !  the parent metadata is freed — it must NOT outlive its parent, and is
   !  never freed by the caller. A default-initialised (or absent-lookup)
   !  cursor has a null `ptr`; test it with `%is_present()`.
   type :: tensogram_value
      type(c_ptr), private :: ptr = c_null_ptr
   contains
      procedure :: is_present => value_is_present  !> non-NULL handle?
      procedure :: kind       => value_kind        !> TGM_VALUE_TYPE_* code
      procedure :: as_int     => value_as_int      !> i64 (logical found)
      procedure :: as_uint    => value_as_uint     !> u64 bits (logical found)
      procedure :: as_float   => value_as_float    !> f64 or int-widened
      procedure :: as_bool    => value_as_bool     !> bool (logical found)
      procedure :: as_string  => value_as_string   !> text ptr+len (found)
      procedure :: as_bytes   => value_as_bytes    !> byte string (found)
      procedure :: len        => value_len         !> array/map element count
      procedure :: elem       => value_elem        !> array elem i (1-based)
      procedure :: key        => value_key         !> map key i (1-based)
      procedure :: value      => value_value       !> map value i (1-based)
      procedure :: get        => value_get         !> single-segment map lookup
   end type tensogram_value

   ! ---- Owned streaming encoder (RAII over tgm_streaming_encoder_t*) -------
   !  Writes a single multi-object message to a file progressively: the
   !  preamble + header metadata on create, one data-object frame per write,
   !  and the footer + postamble on finish. The handle is freed via `free`
   !  (which ABANDONS an unfinished stream — call finish first for a valid
   !  file); the finalizer only releases the handle, it does not finish.
   type :: tensogram_streaming_encoder
      type(c_ptr), private :: ptr = c_null_ptr
   contains
      procedure :: free => stream_enc_free
      procedure, private :: stream_enc_assign
      generic, public :: assignment(=) => stream_enc_assign
      final     :: stream_enc_final
   end type tensogram_streaming_encoder

   ! ---- Generic encode / decode / append over dtype ------------------------
   ! Generic over dtype x rank 0..7, expanded from tgm_iface.inc via the
   ! per-rank table tgm_ranks.inc. The matching
   ! implementations (tgm_encode.inc) are expanded in the CONTAINS section.
   interface tensogram_encode
#define FAM encode_
#define TGM_BODY "tgm_iface.inc"
#define KS f32
#include "tgm_ranks.inc"
#undef KS
#define KS f64
#include "tgm_ranks.inc"
#undef KS
#define KS i32
#include "tgm_ranks.inc"
#undef KS
#define KS i64
#include "tgm_ranks.inc"
#undef KS
#undef TGM_BODY
#undef FAM
   end interface tensogram_encode

   interface tensogram_to_array
#define FAM to_array_
#define TGM_BODY "tgm_iface.inc"
#define KS f32
#include "tgm_ranks.inc"
#undef KS
#define KS f64
#include "tgm_ranks.inc"
#undef KS
#define KS i32
#include "tgm_ranks.inc"
#undef KS
#define KS i64
#include "tgm_ranks.inc"
#undef KS
#undef TGM_BODY
#undef FAM
   end interface tensogram_to_array

   interface tensogram_file_append
#define FAM append_
#define TGM_BODY "tgm_iface.inc"
#define KS f32
#include "tgm_ranks.inc"
#undef KS
#define KS f64
#include "tgm_ranks.inc"
#undef KS
#define KS i32
#include "tgm_ranks.inc"
#undef KS
#define KS i64
#include "tgm_ranks.inc"
#undef KS
#undef TGM_BODY
#undef FAM
   end interface tensogram_file_append

   interface tensogram_streaming_encoder_write
#define FAM stream_write_
#define TGM_BODY "tgm_iface.inc"
#define KS f32
#include "tgm_ranks.inc"
#undef KS
#define KS f64
#include "tgm_ranks.inc"
#undef KS
#define KS i32
#include "tgm_ranks.inc"
#undef KS
#define KS i64
#include "tgm_ranks.inc"
#undef KS
#undef TGM_BODY
#undef FAM
   end interface tensogram_streaming_encoder_write

   ! =========================================================================
   !  Raw C ABI — synchronous subset of tensogram.h.
   ! =========================================================================
   interface
      function c_tgm_last_error() bind(C, name="tgm_last_error") result(p)
         import :: c_ptr
         type(c_ptr) :: p
      end function

      function c_tgm_error_string(err) bind(C, name="tgm_error_string") result(p)
         import :: c_ptr, c_int
         integer(c_int), value :: err
         type(c_ptr) :: p
      end function

      subroutine c_tgm_bytes_free(buf) bind(C, name="tgm_bytes_free")
         import :: tgm_bytes_t
         type(tgm_bytes_t), value :: buf     ! struct passed BY VALUE
      end subroutine

      function c_tgm_encode(meta, ptrs, lens, n, hash, threads, out) &
            bind(C, name="tgm_encode") result(err)
         import :: c_ptr, c_size_t, c_int32_t, c_int, tgm_bytes_t
         type(c_ptr),        value       :: meta
         type(c_ptr),        value       :: ptrs
         type(c_ptr),        value       :: lens
         integer(c_size_t),  value       :: n
         type(c_ptr),        value       :: hash
         integer(c_int32_t), value       :: threads
         type(tgm_bytes_t),  intent(out) :: out
         integer(c_int)                  :: err
      end function

      function c_tgm_decode(buf, buf_len, native_bo, threads, verify, out) &
            bind(C, name="tgm_decode") result(err)
         import :: c_ptr, c_size_t, c_int32_t, c_int
         type(c_ptr),        value       :: buf
         integer(c_size_t),  value       :: buf_len
         integer(c_int32_t), value       :: native_bo
         integer(c_int32_t), value       :: threads
         integer(c_int32_t), value       :: verify
         type(c_ptr),        intent(out) :: out
         integer(c_int)                  :: err
      end function

      function c_tgm_message_num_objects(msg) &
            bind(C, name="tgm_message_num_objects") result(n)
         import :: c_ptr, c_size_t
         type(c_ptr), value :: msg
         integer(c_size_t)  :: n
      end function

      function c_tgm_object_ndim(msg, idx) bind(C, name="tgm_object_ndim") result(n)
         import :: c_ptr, c_size_t, c_int64_t
         type(c_ptr),       value :: msg
         integer(c_size_t), value :: idx
         integer(c_int64_t)       :: n
      end function

      function c_tgm_object_shape(msg, idx) bind(C, name="tgm_object_shape") result(p)
         import :: c_ptr, c_size_t
         type(c_ptr),       value :: msg
         integer(c_size_t), value :: idx
         type(c_ptr)              :: p
      end function

      function c_tgm_object_dtype(msg, idx) bind(C, name="tgm_object_dtype") result(p)
         import :: c_ptr, c_size_t
         type(c_ptr),       value :: msg
         integer(c_size_t), value :: idx
         type(c_ptr)              :: p
      end function

      function c_tgm_object_data(msg, idx, out_len) &
            bind(C, name="tgm_object_data") result(p)
         import :: c_ptr, c_size_t
         type(c_ptr),       value       :: msg
         integer(c_size_t), value       :: idx
         integer(c_size_t), intent(out) :: out_len
         type(c_ptr)                    :: p
      end function

      subroutine c_tgm_message_free(msg) bind(C, name="tgm_message_free")
         import :: c_ptr
         type(c_ptr), value :: msg
      end subroutine

      function c_strlen(s) bind(C, name="strlen") result(n)
         import :: c_ptr, c_size_t
         type(c_ptr), value :: s
         integer(c_size_t)  :: n
      end function

      function c_tgm_file_open(path, out) bind(C, name="tgm_file_open") result(err)
         import :: c_ptr, c_int
         type(c_ptr), value       :: path
         type(c_ptr), intent(out) :: out
         integer(c_int)           :: err
      end function

      function c_tgm_file_create(path, out) bind(C, name="tgm_file_create") result(err)
         import :: c_ptr, c_int
         type(c_ptr), value       :: path
         type(c_ptr), intent(out) :: out
         integer(c_int)           :: err
      end function

      function c_tgm_file_message_count(file, cnt) &
            bind(C, name="tgm_file_message_count") result(err)
         import :: c_ptr, c_size_t, c_int
         type(c_ptr), value             :: file
         integer(c_size_t), intent(out) :: cnt
         integer(c_int)                 :: err
      end function

      function c_tgm_file_decode_message(file, idx, native_bo, threads, verify, out) &
            bind(C, name="tgm_file_decode_message") result(err)
         import :: c_ptr, c_size_t, c_int32_t, c_int
         type(c_ptr),        value       :: file
         integer(c_size_t),  value       :: idx
         integer(c_int32_t), value       :: native_bo
         integer(c_int32_t), value       :: threads
         integer(c_int32_t), value       :: verify
         type(c_ptr),        intent(out) :: out
         integer(c_int)                  :: err
      end function

      function c_tgm_file_read_message(file, idx, out) &
            bind(C, name="tgm_file_read_message") result(err)
         import :: c_ptr, c_size_t, c_int, tgm_bytes_t
         type(c_ptr),       value       :: file
         integer(c_size_t), value       :: idx
         type(tgm_bytes_t), intent(out) :: out
         integer(c_int)                 :: err
      end function

      function c_tgm_file_append(file, meta, ptrs, lens, n, hash, threads) &
            bind(C, name="tgm_file_append") result(err)
         import :: c_ptr, c_size_t, c_int32_t, c_int
         type(c_ptr),        value :: file
         type(c_ptr),        value :: meta
         type(c_ptr),        value :: ptrs
         type(c_ptr),        value :: lens
         integer(c_size_t),  value :: n
         type(c_ptr),        value :: hash
         integer(c_int32_t), value :: threads
         integer(c_int)            :: err
      end function

      subroutine c_tgm_file_close(file) bind(C, name="tgm_file_close")
         import :: c_ptr
         type(c_ptr), value :: file
      end subroutine

      function c_tgm_message_metadata(msg, out) &
            bind(C, name="tgm_message_metadata") result(err)
         import :: c_ptr, c_int
         type(c_ptr), value       :: msg
         type(c_ptr), intent(out) :: out
         integer(c_int)           :: err
      end function

      function c_tgm_metadata_get_string(meta, key) &
            bind(C, name="tgm_metadata_get_string") result(p)
         import :: c_ptr
         type(c_ptr), value :: meta
         type(c_ptr), value :: key
         type(c_ptr)        :: p
      end function

      function c_tgm_metadata_get_int(meta, key, default_val) &
            bind(C, name="tgm_metadata_get_int") result(v)
         import :: c_ptr, c_int64_t
         type(c_ptr),        value :: meta
         type(c_ptr),        value :: key
         integer(c_int64_t), value :: default_val
         integer(c_int64_t)        :: v
      end function

      function c_tgm_metadata_get_float(meta, key, default_val) &
            bind(C, name="tgm_metadata_get_float") result(v)
         import :: c_ptr, c_double
         type(c_ptr),    value :: meta
         type(c_ptr),    value :: key
         real(c_double), value :: default_val
         real(c_double)        :: v
      end function

      ! ---- Metadata value cursor (borrowed views into decoded metadata) ----

      function c_tgm_metadata_num_objects(meta) &
            bind(C, name="tgm_metadata_num_objects") result(n)
         import :: c_ptr, c_size_t
         type(c_ptr), value :: meta
         integer(c_size_t)  :: n
      end function

      function c_tgm_metadata_get(meta, path) &
            bind(C, name="tgm_metadata_get") result(p)
         import :: c_ptr
         type(c_ptr), value :: meta
         type(c_ptr), value :: path
         type(c_ptr)        :: p
      end function

      function c_tgm_metadata_get_at(meta, obj, path) &
            bind(C, name="tgm_metadata_get_at") result(p)
         import :: c_ptr, c_size_t
         type(c_ptr),       value :: meta
         integer(c_size_t), value :: obj
         type(c_ptr),       value :: path
         type(c_ptr)              :: p
      end function

      function c_tgm_metadata_has(meta, path) &
            bind(C, name="tgm_metadata_has") result(b)
         import :: c_ptr, c_bool
         type(c_ptr), value :: meta
         type(c_ptr), value :: path
         logical(c_bool)    :: b
      end function

      function c_tgm_metadata_has_at(meta, obj, path) &
            bind(C, name="tgm_metadata_has_at") result(b)
         import :: c_ptr, c_size_t, c_bool
         type(c_ptr),       value :: meta
         integer(c_size_t), value :: obj
         type(c_ptr),       value :: path
         logical(c_bool)          :: b
      end function

      function c_tgm_metadata_object(meta, obj) &
            bind(C, name="tgm_metadata_object") result(p)
         import :: c_ptr, c_size_t
         type(c_ptr),       value :: meta
         integer(c_size_t), value :: obj
         type(c_ptr)              :: p
      end function

      function c_tgm_metadata_extra(meta) &
            bind(C, name="tgm_metadata_extra") result(p)
         import :: c_ptr
         type(c_ptr), value :: meta
         type(c_ptr)        :: p
      end function

      function c_tgm_metadata_reserved(meta) &
            bind(C, name="tgm_metadata_reserved") result(p)
         import :: c_ptr
         type(c_ptr), value :: meta
         type(c_ptr)        :: p
      end function

      function c_tgm_value_get_type(v) &
            bind(C, name="tgm_value_get_type") result(t)
         import :: c_ptr, c_int
         type(c_ptr), value :: v
         integer(c_int)     :: t
      end function

      function c_tgm_value_as_bool(v, out) &
            bind(C, name="tgm_value_as_bool") result(b)
         import :: c_ptr, c_bool
         type(c_ptr),     value       :: v
         logical(c_bool), intent(out) :: out
         logical(c_bool)              :: b
      end function

      function c_tgm_value_as_i64(v, out) &
            bind(C, name="tgm_value_as_i64") result(b)
         import :: c_ptr, c_int64_t, c_bool
         type(c_ptr),        value       :: v
         integer(c_int64_t), intent(out) :: out
         logical(c_bool)                 :: b
      end function

      function c_tgm_value_as_u64(v, out) &
            bind(C, name="tgm_value_as_u64") result(b)
         import :: c_ptr, c_int64_t, c_bool
         type(c_ptr),        value       :: v
         integer(c_int64_t), intent(out) :: out   ! u64 bit pattern (no unsigned in F)
         logical(c_bool)                 :: b
      end function

      function c_tgm_value_as_f64(v, out) &
            bind(C, name="tgm_value_as_f64") result(b)
         import :: c_ptr, c_double, c_bool
         type(c_ptr),    value       :: v
         real(c_double), intent(out) :: out
         logical(c_bool)             :: b
      end function

      function c_tgm_value_as_string(v, len_out) &
            bind(C, name="tgm_value_as_string") result(p)
         import :: c_ptr, c_size_t
         type(c_ptr),       value       :: v
         integer(c_size_t), intent(out) :: len_out
         type(c_ptr)                    :: p
      end function

      function c_tgm_value_as_bytes(v, len_out) &
            bind(C, name="tgm_value_as_bytes") result(p)
         import :: c_ptr, c_size_t
         type(c_ptr),       value       :: v
         integer(c_size_t), intent(out) :: len_out
         type(c_ptr)                    :: p
      end function

      function c_tgm_value_array_len(v) &
            bind(C, name="tgm_value_array_len") result(n)
         import :: c_ptr, c_size_t
         type(c_ptr), value :: v
         integer(c_size_t)  :: n
      end function

      function c_tgm_value_array_get(v, index) &
            bind(C, name="tgm_value_array_get") result(p)
         import :: c_ptr, c_size_t
         type(c_ptr),       value :: v
         integer(c_size_t), value :: index
         type(c_ptr)              :: p
      end function

      function c_tgm_value_map_len(v) &
            bind(C, name="tgm_value_map_len") result(n)
         import :: c_ptr, c_size_t
         type(c_ptr), value :: v
         integer(c_size_t)  :: n
      end function

      function c_tgm_value_map_key_at(v, index, len_out) &
            bind(C, name="tgm_value_map_key_at") result(p)
         import :: c_ptr, c_size_t
         type(c_ptr),       value       :: v
         integer(c_size_t), value       :: index
         integer(c_size_t), intent(out) :: len_out
         type(c_ptr)                    :: p
      end function

      function c_tgm_value_map_value_at(v, index) &
            bind(C, name="tgm_value_map_value_at") result(p)
         import :: c_ptr, c_size_t
         type(c_ptr),       value :: v
         integer(c_size_t), value :: index
         type(c_ptr)              :: p
      end function

      function c_tgm_value_map_get(v, key) &
            bind(C, name="tgm_value_map_get") result(p)
         import :: c_ptr
         type(c_ptr), value :: v
         type(c_ptr), value :: key
         type(c_ptr)        :: p
      end function

      subroutine c_tgm_metadata_free(meta) bind(C, name="tgm_metadata_free")
         import :: c_ptr
         type(c_ptr), value :: meta
      end subroutine

      function c_tgm_streaming_encoder_create(path, meta, hash, threads, out) &
            bind(C, name="tgm_streaming_encoder_create") result(err)
         import :: c_ptr, c_int32_t, c_int
         type(c_ptr),        value       :: path
         type(c_ptr),        value       :: meta
         type(c_ptr),        value       :: hash
         integer(c_int32_t), value       :: threads
         type(c_ptr),        intent(out) :: out
         integer(c_int)                  :: err
      end function

      function c_tgm_streaming_encoder_write(enc, descriptor_json, data, data_len) &
            bind(C, name="tgm_streaming_encoder_write") result(err)
         import :: c_ptr, c_size_t, c_int
         type(c_ptr),       value :: enc
         type(c_ptr),       value :: descriptor_json
         type(c_ptr),       value :: data
         integer(c_size_t), value :: data_len
         integer(c_int)           :: err
      end function

      function c_tgm_streaming_encoder_count(enc) &
            bind(C, name="tgm_streaming_encoder_count") result(n)
         import :: c_ptr, c_size_t
         type(c_ptr), value :: enc
         integer(c_size_t)  :: n
      end function

      function c_tgm_streaming_encoder_finish(enc) &
            bind(C, name="tgm_streaming_encoder_finish") result(err)
         import :: c_ptr, c_int
         type(c_ptr), value :: enc
         integer(c_int)     :: err
      end function

      subroutine c_tgm_streaming_encoder_free(enc) &
            bind(C, name="tgm_streaming_encoder_free")
         import :: c_ptr
         type(c_ptr), value :: enc
      end subroutine
   end interface

contains

   ! =========================================================================
   !  String / JSON helpers
   ! =========================================================================

   subroutine f_to_cstr(f, c)
      character(len=*),                    intent(in)  :: f
      character(kind=c_char), allocatable, intent(out) :: c(:)
      integer :: i, n
      n = len(f)
      allocate(c(n + 1))
      do i = 1, n
         c(i) = f(i:i)
      end do
      c(n + 1) = c_null_char
   end subroutine f_to_cstr

   function cptr_to_fstr(p) result(f)
      type(c_ptr), intent(in)         :: p
      character(len=:), allocatable   :: f
      character(kind=c_char), pointer :: buf(:)
      integer(c_size_t) :: n
      integer :: i
      if (.not. c_associated(p)) then
         f = ''
         return
      end if
      n = c_strlen(p)
      call c_f_pointer(p, buf, [n])
      allocate(character(len=int(n)) :: f)
      do i = 1, int(n)
         f(i:i) = buf(i)
      end do
   end function cptr_to_fstr

   !> Copy exactly `n` bytes from a borrowed C buffer into a Fortran string.
   !> Unlike cptr_to_fstr this does NOT stop at (nor require) a terminating
   !> NUL: the metadata value cursor lends UTF-8 `ptr + len` buffers that may
   !> hold interior NUL bytes and are not NUL-terminated. A zero length yields
   !> an empty string WITHOUT dereferencing `p` (safe for the empty-string /
   !> empty-key case, where `p` may be a non-dereferenceable sentinel).
   function cptr_len_to_fstr(p, n) result(f)
      type(c_ptr),       intent(in) :: p
      integer(c_size_t), intent(in) :: n
      character(len=:), allocatable   :: f
      character(kind=c_char), pointer :: buf(:)
      integer :: i
      allocate(character(len=int(n)) :: f)
      if (n == 0_c_size_t) return
      call c_f_pointer(p, buf, [n])
      do i = 1, int(n)
         f(i:i) = buf(i)
      end do
   end function cptr_len_to_fstr

   pure function itoa(i) result(s)
      integer(c_int64_t), intent(in) :: i
      character(len=:), allocatable  :: s
      character(len=32)              :: tmp
      write (tmp, '(i0)') i
      s = trim(tmp)
   end function itoa

   !> Comma-separated list of int64 values ('' for an empty vector).
   pure function i64list(v) result(s)
      integer(c_int64_t), intent(in) :: v(:)
      character(len=:), allocatable  :: s
      integer :: k
      s = ''
      do k = 1, size(v)
         if (k > 1) s = s // ','
         s = s // itoa(v(k))
      end do
   end function i64list

   pure function host_byte_order() result(bo)
      character(len=:), allocatable :: bo
      integer(c_int8_t) :: bytes(4)
      bytes = transfer(1_c_int32_t, 0_c_int8_t, 4)
      if (bytes(1) == 1_c_int8_t) then
         bo = 'little'
      else
         bo = 'big'
      end if
   end function host_byte_order

   !> Resolve the optional hash-algorithm name to a C string pointer. Fills
   !> `hash_c` (a caller-owned target buffer that must outlive the C call) and
   !> `hash_ptr`: a present-but-empty name means "no hash" (NULL); absent means
   !> the default "xxh3".
   subroutine resolve_hash(hash, hash_c, hash_ptr)
      character(len=*), intent(in), optional :: hash
      character(kind=c_char), allocatable, target, intent(out) :: hash_c(:)
      type(c_ptr),                                 intent(out) :: hash_ptr
      character(len=:), allocatable :: hash_s
      if (present(hash)) then
         hash_s = trim(hash)            ! drop fixed-length padding
      else
         hash_s = 'xxh3'
      end if
      if (len(hash_s) == 0) then
         hash_ptr = c_null_ptr
      else
         call f_to_cstr(hash_s, hash_c)
         hash_ptr = c_loc(hash_c)
      end if
   end subroutine resolve_hash

   !> Total element count for a Fortran extent vector (1 for a scalar / empty).
   pure function num_elements(ext) result(n)
      integer(c_int64_t), intent(in) :: ext(:)
      integer(c_size_t) :: n
      n = product([1_c_size_t, int(ext, c_size_t)])
   end function num_elements

   !> Wire payload byte count = element count × element byte width (`bits/8`).
   !> Deriving the width from `storage_size(a)` keeps it consistent with the
   !> actual Fortran type rather than a hard-coded literal per dtype wrapper.
   pure function byte_count(num, bits) result(n)
      integer(c_size_t), intent(in) :: num, bits
      integer(c_size_t) :: n
      n = num * (bits / 8_c_size_t)
   end function byte_count

   !> Build the one-object descriptor JSON. `fshape` is the Fortran
   !> (column-major) extents; the on-wire shape and C-contiguous strides are
   !> the REVERSE (see the memory-order contract above). `extra`, if present, is raw JSON of
   !> additional top-level keys appended verbatim.
   !> Build a single DataObjectDescriptor object `{...}` with the on-wire
   !> shape and C-contiguous strides REVERSED from the Fortran extents
   !> (column-major contract). Used directly by the streaming encoder; wrapped
   !> in `{"descriptors":[...]}` by descriptor_json for the buffer/file path.
   function descriptor_object_json(fshape, dtype, encoding, filter, compression) result(js)
      integer(c_int64_t), intent(in)           :: fshape(:)
      character(len=*),   intent(in)           :: dtype
      character(len=*),   intent(in), optional :: encoding, filter, compression
      character(len=:), allocatable :: js, enc_s, flt_s, cmp_s
      integer(c_int64_t), allocatable :: wshape(:), wstrides(:)
      integer :: nd, k
      nd = size(fshape)
      allocate(wshape(nd), wstrides(nd))
      do k = 1, nd
         wshape(k) = fshape(nd - k + 1)          ! reverse to C order
      end do
      if (nd > 0) then
         wstrides(nd) = 1_c_int64_t
         do k = nd - 1, 1, -1
            wstrides(k) = wstrides(k + 1) * wshape(k + 1)
         end do
      end if
      enc_s = 'none'; if (present(encoding))    enc_s = trim(encoding)
      flt_s = 'none'; if (present(filter))      flt_s = trim(filter)
      cmp_s = 'none'; if (present(compression)) cmp_s = trim(compression)
      js = '{"type":"ntensor","ndim":' // itoa(int(nd, c_int64_t)) // &
           ',"shape":['   // i64list(wshape)   // ']' //                   &
           ',"strides":[' // i64list(wstrides) // ']' //                   &
           ',"dtype":"' // trim(dtype) // '","byte_order":"' // host_byte_order() // '"' // &
           ',"encoding":"' // enc_s // '","filter":"' // flt_s // &
           '","compression":"' // cmp_s // '"}'
   end function descriptor_object_json

   !> Wrap one descriptor in the `{"descriptors":[...], <extra>}` envelope the
   !> buffer/file encode entry points expect. `extra` is raw top-level JSON.
   function descriptor_json(fshape, dtype, extra, encoding, filter, compression) result(js)
      integer(c_int64_t), intent(in)           :: fshape(:)
      character(len=*),   intent(in)           :: dtype
      character(len=*),   intent(in), optional :: extra
      character(len=*),   intent(in), optional :: encoding, filter, compression
      character(len=:), allocatable :: js, e
      js = '{"descriptors":[' // &
           descriptor_object_json(fshape, dtype, encoding, filter, compression) // ']'
      if (present(extra)) then
         ! `extra` may be a complete JSON object (`{ ... }`, matching the
         ! streaming metadata argument) or a raw top-level key fragment
         ! (`"base":[...]`, e.g. the output of tensogram_meta%base_json()).
         ! Strip the outer braces of a complete object so the result is a
         ! single valid object either way.
         e = trim(adjustl(extra))
         if (len(e) >= 2) then
            if (e(1:1) == '{' .and. e(len(e):len(e)) == '}') e = e(2:len(e) - 1)
         end if
         if (len_trim(e) > 0) js = js // ',' // e
      end if
      js = js // '}'
   end function descriptor_json

   ! =========================================================================
   !  Error helpers
   ! =========================================================================

   !> Static, human-readable description of a `tgm_error` code.
   function tensogram_strerror(err) result(msg)
      integer(c_int), intent(in)    :: err
      character(len=:), allocatable :: msg
      msg = cptr_to_fstr(c_tgm_error_string(err))
   end function tensogram_strerror

   !> The thread-local detail message left by the most recent failing call
   !> (empty when there is none).
   function tensogram_last_error() result(msg)
      character(len=:), allocatable :: msg
      msg = cptr_to_fstr(c_tgm_last_error())
   end function tensogram_last_error

   !> Convenience guard: a no-op on `TGM_ERROR_OK`; otherwise print `context`
   !> plus the error detail to stderr and `error stop`. Prefer inspecting the
   !> error code directly in library code.
   subroutine tensogram_check(err, context)
      integer(c_int),   intent(in)           :: err
      character(len=*), intent(in), optional :: context
      character(len=:), allocatable :: detail
      if (err == TGM_ERROR_OK) return
      detail = tensogram_last_error()
      if (len(detail) == 0) detail = tensogram_strerror(err)
      if (present(context)) then
         write (error_unit, '(a)') 'tensogram: ' // trim(context) // ': ' // detail
      else
         write (error_unit, '(a)') 'tensogram: ' // detail
      end if
      error stop 1
   end subroutine tensogram_check

   ! =========================================================================
   !  tensogram_buffer methods
   ! =========================================================================

   function buffer_size(self) result(n)
      class(tensogram_buffer), intent(in) :: self
      integer(c_size_t) :: n
      n = self%raw%len
   end function buffer_size

   subroutine buffer_as_array(self, out)
      class(tensogram_buffer), intent(in)          :: self
      integer(c_int8_t), allocatable, intent(out)  :: out(:)
      integer(c_int8_t), pointer :: view(:)
      if (.not. c_associated(self%raw%data) .or. self%raw%len == 0_c_size_t) then
         allocate(out(0))
         return
      end if
      call c_f_pointer(self%raw%data, view, [self%raw%len])
      allocate(out(self%raw%len))
      out = view
   end subroutine buffer_as_array

   subroutine buffer_free(self)
      class(tensogram_buffer), intent(inout) :: self
      if (c_associated(self%raw%data)) then
         call c_tgm_bytes_free(self%raw)
         self%raw%data = c_null_ptr
         self%raw%len  = 0_c_size_t
      end if
   end subroutine buffer_free

   subroutine buffer_final(self)
      type(tensogram_buffer), intent(inout) :: self
      call self%free()
   end subroutine buffer_final

   subroutine buffer_assign(lhs, rhs)
      class(tensogram_buffer), intent(out) :: lhs
      type(tensogram_buffer),  intent(in)  :: rhs
      if (c_associated(rhs%raw%data)) then
         error stop "tensogram_buffer is non-copyable: assigning a live buffer would alias and double-free; pass by reference"
      else
         error stop "tensogram_buffer is non-copyable: do not assign buffers; pass by reference"
      end if
   end subroutine buffer_assign

   ! =========================================================================
   !  tensogram_message methods
   ! =========================================================================

   subroutine message_free(self)
      class(tensogram_message), intent(inout) :: self
      if (c_associated(self%ptr)) then
         call c_tgm_message_free(self%ptr)
         self%ptr = c_null_ptr
      end if
   end subroutine message_free

   subroutine message_final(self)
      type(tensogram_message), intent(inout) :: self
      call self%free()
   end subroutine message_final

   subroutine message_assign(lhs, rhs)
      class(tensogram_message), intent(out) :: lhs
      type(tensogram_message),  intent(in)  :: rhs
      if (c_associated(rhs%ptr)) then
         error stop "tensogram_message is non-copyable: assigning a live handle would alias and double-free; pass by reference"
      else
         error stop "tensogram_message is non-copyable: do not assign handles; pass by reference"
      end if
   end subroutine message_assign

   ! =========================================================================
   !  Encode core (shared by all dtype/rank overloads)
   ! =========================================================================

   !> Encode one tensor (described by `ptr` + `nbytes` + Fortran `fshape` +
   !> `dtype`) into `buf`. `ptr` must reference `nbytes` contiguous bytes that
   !> stay valid for the duration of this call.
   subroutine encode_core(ptr, nbytes, fshape, dtype, buf, err, &
                          metadata_json, hash, encoding, filter, compression)
      type(c_ptr),        intent(in)  :: ptr
      integer(c_size_t),  intent(in)  :: nbytes
      integer(c_int64_t), intent(in)  :: fshape(:)
      character(len=*),   intent(in)  :: dtype
      type(tensogram_buffer), intent(out) :: buf
      integer(c_int),     intent(out) :: err
      character(len=*), intent(in), optional :: metadata_json, hash
      character(len=*), intent(in), optional :: encoding, filter, compression

      character(kind=c_char), allocatable, target :: meta_c(:), hash_c(:)
      character(len=:),       allocatable         :: meta_s
      type(c_ptr),       target :: ptrs(1)
      integer(c_size_t), target :: lens(1)
      type(c_ptr)               :: hash_ptr

      meta_s = descriptor_json(fshape, dtype, metadata_json, encoding, filter, compression)
      call f_to_cstr(meta_s, meta_c)
      call resolve_hash(hash, hash_c, hash_ptr)
      ptrs(1) = ptr
      lens(1) = nbytes
      err = c_tgm_encode(c_loc(meta_c), c_loc(ptrs), c_loc(lens), &
                         1_c_size_t, hash_ptr, 0_c_int32_t, buf%raw)
   end subroutine encode_core

   ! =========================================================================
   !  Generic encode overloads (dtype x rank 0..7). The per-rank specifics are
   !  expanded from tgm_encode.inc via the per-rank table tgm_ranks.inc, once
   !  per dtype. Explicit per-rank dummies (vs. an assumed-rank `a(..)`) keep
   !  the surface within Fortran 2008. The shared encode_core does the work.
   ! =========================================================================
#define FAM encode_
#define TGM_BODY "tgm_encode.inc"
#define KS f32
#define DT real(c_float)
#define DTSTR 'float32'
#include "tgm_ranks.inc"
#undef DTSTR
#undef DT
#undef KS
#define KS f64
#define DT real(c_double)
#define DTSTR 'float64'
#include "tgm_ranks.inc"
#undef DTSTR
#undef DT
#undef KS
#define KS i32
#define DT integer(c_int32_t)
#define DTSTR 'int32'
#include "tgm_ranks.inc"
#undef DTSTR
#undef DT
#undef KS
#define KS i64
#define DT integer(c_int64_t)
#define DTSTR 'int64'
#include "tgm_ranks.inc"
#undef DTSTR
#undef DT
#undef KS
#undef TGM_BODY
#undef FAM

   ! =========================================================================
   !  Decode wire bytes -> message handle
   ! =========================================================================

   !> Decode wire-format bytes into a message handle. `verify_hash` (default
   !> `.false.`, to match the core library) checks the per-object xxh3 digest;
   !> `native_byte_order` (default `.true.`) converts to the host byte order.
   subroutine tensogram_decode(wire, msg, err, verify_hash, native_byte_order)
      integer(c_int8_t), target, contiguous, intent(in)  :: wire(:)
      type(tensogram_message),               intent(out) :: msg
      integer(c_int),                        intent(out) :: err
      logical, intent(in), optional :: verify_hash        ! default .false.
      logical, intent(in), optional :: native_byte_order  ! default .true.
      integer(c_int32_t) :: vh, nbo
      type(c_ptr)        :: out
      vh = 0_c_int32_t
      if (present(verify_hash)) vh = merge(1_c_int32_t, 0_c_int32_t, verify_hash)
      nbo = 1_c_int32_t
      if (present(native_byte_order)) &
         nbo = merge(1_c_int32_t, 0_c_int32_t, native_byte_order)
      err = c_tgm_decode(c_loc(wire), size(wire, kind=c_size_t), &
                         nbo, 0_c_int32_t, vh, out)
      if (err == TGM_ERROR_OK) msg%ptr = out
   end subroutine tensogram_decode

   ! =========================================================================
   !  Object metadata accessors
   ! =========================================================================

   !> Number of decoded objects in the message.
   function tensogram_num_objects(msg) result(n)
      type(tensogram_message), intent(in) :: msg
      integer :: n
      n = int(c_tgm_message_num_objects(msg%ptr))
   end function tensogram_num_objects

   !> Rank of object `iobj` (1-based); `0` for an out-of-range index.
   function tensogram_object_ndim(msg, iobj) result(nd)
      type(tensogram_message), intent(in) :: msg
      integer,                 intent(in) :: iobj
      integer :: nd
      nd = int(c_tgm_object_ndim(msg%ptr, int(iobj - 1, c_size_t)))
   end function tensogram_object_ndim

   !> Object extents in FORTRAN (column-major) order — the on-wire shape
   !> REVERSED. ext(1) is the fastest-varying axis.
   function tensogram_object_shape(msg, iobj) result(ext)
      type(tensogram_message), intent(in) :: msg
      integer,                 intent(in) :: iobj
      integer(c_int64_t), allocatable :: ext(:)
      integer(c_int64_t), pointer     :: cshape(:)
      integer     :: nd, k
      type(c_ptr) :: p
      nd = tensogram_object_ndim(msg, iobj)
      allocate(ext(nd))
      if (nd == 0) return
      p = c_tgm_object_shape(msg%ptr, int(iobj - 1, c_size_t))
      call c_f_pointer(p, cshape, [nd])
      do k = 1, nd
         ext(k) = cshape(nd - k + 1)              ! reverse -> Fortran order
      end do
   end function tensogram_object_shape

   !> dtype string of object `iobj` (e.g. `"float32"`); empty for an
   !> out-of-range index.
   function tensogram_object_dtype(msg, iobj) result(dt)
      type(tensogram_message), intent(in) :: msg
      integer,                 intent(in) :: iobj
      character(len=:), allocatable :: dt
      dt = cptr_to_fstr(c_tgm_object_dtype(msg%ptr, int(iobj - 1, c_size_t)))
   end function tensogram_object_dtype

   ! =========================================================================
   !  Decode helper: validate object i against an expected dtype, return the
   !  Fortran extents + a c_ptr to the payload bytes (or err set).
   ! =========================================================================
   subroutine object_payload(msg, iobj, want_dtype, want_rank, ext, dptr, err)
      type(tensogram_message), intent(in)  :: msg
      integer,                 intent(in)  :: iobj
      character(len=*),        intent(in)  :: want_dtype
      integer,                 intent(in)  :: want_rank
      integer(c_int64_t), allocatable, intent(out) :: ext(:)
      type(c_ptr),             intent(out) :: dptr
      integer(c_int),          intent(out) :: err
      integer(c_size_t) :: nbytes
      err = TGM_ERROR_OK
      if (tensogram_object_dtype(msg, iobj) /= want_dtype) then
         err = TGM_ERROR_OBJECT
         return
      end if
      ext = tensogram_object_shape(msg, iobj)
      if (size(ext) /= want_rank) then
         err = TGM_ERROR_OBJECT
         return
      end if
      dptr = c_tgm_object_data(msg%ptr, int(iobj - 1, c_size_t), nbytes)
      if (.not. c_associated(dptr)) err = TGM_ERROR_OBJECT
   end subroutine object_payload

   ! =========================================================================
   !  Generic decode overloads (dtype x rank 0..7). Expanded from
   !  tgm_to_array.inc via tgm_ranks.inc, once per dtype. The known rank (RNK)
   !  replaces the F2018 SELECT RANK: each specific allocates directly, then a
   !  unified flat copy — the reversed-shape contract makes the C and Fortran
   !  flat layouts coincide. The shared object_payload validates dtype/rank.
   ! =========================================================================
#define FAM to_array_
#define TGM_BODY "tgm_to_array.inc"
#define KS f32
#define DT real(c_float)
#define DTSTR 'float32'
#include "tgm_ranks.inc"
#undef DTSTR
#undef DT
#undef KS
#define KS f64
#define DT real(c_double)
#define DTSTR 'float64'
#include "tgm_ranks.inc"
#undef DTSTR
#undef DT
#undef KS
#define KS i32
#define DT integer(c_int32_t)
#define DTSTR 'int32'
#include "tgm_ranks.inc"
#undef DTSTR
#undef DT
#undef KS
#define KS i64
#define DT integer(c_int64_t)
#define DTSTR 'int64'
#include "tgm_ranks.inc"
#undef DTSTR
#undef DT
#undef KS
#undef TGM_BODY
#undef FAM

   ! =========================================================================
   !  tensogram_file methods
   ! =========================================================================

   subroutine file_close(self)
      class(tensogram_file), intent(inout) :: self
      if (c_associated(self%ptr)) then
         call c_tgm_file_close(self%ptr)
         self%ptr = c_null_ptr
      end if
   end subroutine file_close

   subroutine file_final(self)
      type(tensogram_file), intent(inout) :: self
      call self%close()
   end subroutine file_final

   subroutine file_assign(lhs, rhs)
      class(tensogram_file), intent(out) :: lhs
      type(tensogram_file),  intent(in)  :: rhs
      if (c_associated(rhs%ptr)) then
         error stop "tensogram_file is non-copyable: assigning a live handle would alias and double-close; pass by reference"
      else
         error stop "tensogram_file is non-copyable: do not assign handles; pass by reference"
      end if
   end subroutine file_assign

   !> Open an existing .tgm file for reading.
   subroutine tensogram_file_open(path, file, err)
      character(len=*),      intent(in)  :: path
      type(tensogram_file),  intent(out) :: file
      integer(c_int),        intent(out) :: err
      character(kind=c_char), allocatable, target :: path_c(:)
      type(c_ptr) :: out
      call f_to_cstr(trim(path), path_c)
      err = c_tgm_file_open(c_loc(path_c), out)
      if (err == TGM_ERROR_OK) file%ptr = out
   end subroutine tensogram_file_open

   !> Create a new .tgm file for writing (append messages with file_append).
   subroutine tensogram_file_create(path, file, err)
      character(len=*),      intent(in)  :: path
      type(tensogram_file),  intent(out) :: file
      integer(c_int),        intent(out) :: err
      character(kind=c_char), allocatable, target :: path_c(:)
      type(c_ptr) :: out
      call f_to_cstr(trim(path), path_c)
      err = c_tgm_file_create(c_loc(path_c), out)
      if (err == TGM_ERROR_OK) file%ptr = out
   end subroutine tensogram_file_create

   !> Number of messages in the file (may trigger a lazy scan).
   subroutine tensogram_file_message_count(file, count, err)
      type(tensogram_file), intent(in)  :: file
      integer,              intent(out) :: count
      integer(c_int),       intent(out) :: err
      integer(c_size_t) :: cnt
      cnt = 0_c_size_t
      err = c_tgm_file_message_count(file%ptr, cnt)
      count = int(cnt)
   end subroutine tensogram_file_message_count

   !> Decode the message at `index` (1-based) into a handle.
   subroutine tensogram_file_decode_message(file, index, msg, err, &
                                            verify_hash, native_byte_order)
      type(tensogram_file),    intent(in)  :: file
      integer,                 intent(in)  :: index
      type(tensogram_message), intent(out) :: msg
      integer(c_int),          intent(out) :: err
      logical, intent(in), optional :: verify_hash       ! default .false.
      logical, intent(in), optional :: native_byte_order ! default .true.
      integer(c_int32_t) :: vh, nbo
      type(c_ptr) :: out
      vh = 0_c_int32_t
      if (present(verify_hash)) vh = merge(1_c_int32_t, 0_c_int32_t, verify_hash)
      nbo = 1_c_int32_t
      if (present(native_byte_order)) &
         nbo = merge(1_c_int32_t, 0_c_int32_t, native_byte_order)
      err = c_tgm_file_decode_message(file%ptr, int(index - 1, c_size_t), &
                                      nbo, 0_c_int32_t, vh, out)
      if (err == TGM_ERROR_OK) msg%ptr = out
   end subroutine tensogram_file_decode_message

   !> Read the raw message bytes at `index` (1-based) into a buffer.
   subroutine tensogram_file_read_message(file, index, buf, err)
      type(tensogram_file),   intent(in)  :: file
      integer,                intent(in)  :: index
      type(tensogram_buffer), intent(out) :: buf
      integer(c_int),         intent(out) :: err
      err = c_tgm_file_read_message(file%ptr, int(index - 1, c_size_t), buf%raw)
   end subroutine tensogram_file_read_message

   ! =========================================================================
   !  Append core + generic append overloads
   ! =========================================================================

   !> Encode one tensor and append it to `file_ptr` as a new message. Mirrors
   !> encode_core but targets the file-append entry point (no buffer returned).
   subroutine append_core(file_ptr, ptr, nbytes, fshape, dtype, err, &
                          metadata_json, hash, encoding, filter, compression)
      type(c_ptr),        intent(in)  :: file_ptr
      type(c_ptr),        intent(in)  :: ptr
      integer(c_size_t),  intent(in)  :: nbytes
      integer(c_int64_t), intent(in)  :: fshape(:)
      character(len=*),   intent(in)  :: dtype
      integer(c_int),     intent(out) :: err
      character(len=*), intent(in), optional :: metadata_json, hash
      character(len=*), intent(in), optional :: encoding, filter, compression
      character(kind=c_char), allocatable, target :: meta_c(:), hash_c(:)
      character(len=:),       allocatable         :: meta_s
      type(c_ptr),       target :: ptrs(1)
      integer(c_size_t), target :: lens(1)
      type(c_ptr)               :: hash_ptr
      meta_s = descriptor_json(fshape, dtype, metadata_json, encoding, filter, compression)
      call f_to_cstr(meta_s, meta_c)
      call resolve_hash(hash, hash_c, hash_ptr)
      ptrs(1) = ptr
      lens(1) = nbytes
      err = c_tgm_file_append(file_ptr, c_loc(meta_c), c_loc(ptrs), c_loc(lens), &
                              1_c_size_t, hash_ptr, 0_c_int32_t)
   end subroutine append_core

#define FAM append_
#define TGM_BODY "tgm_append.inc"
#define KS f32
#define DT real(c_float)
#define DTSTR 'float32'
#include "tgm_ranks.inc"
#undef DTSTR
#undef DT
#undef KS
#define KS f64
#define DT real(c_double)
#define DTSTR 'float64'
#include "tgm_ranks.inc"
#undef DTSTR
#undef DT
#undef KS
#define KS i32
#define DT integer(c_int32_t)
#define DTSTR 'int32'
#include "tgm_ranks.inc"
#undef DTSTR
#undef DT
#undef KS
#define KS i64
#define DT integer(c_int64_t)
#define DTSTR 'int64'
#include "tgm_ranks.inc"
#undef DTSTR
#undef DT
#undef KS
#undef TGM_BODY
#undef FAM

   ! =========================================================================
   !  Application-metadata builder (tensogram_meta) + JSON escaping
   ! =========================================================================

   pure function hex2(c) result(h)
      integer, intent(in) :: c
      character(len=2)               :: h
      character(len=16), parameter   :: dig = '0123456789abcdef'
      h(1:1) = dig(c / 16 + 1 : c / 16 + 1)
      h(2:2) = dig(mod(c, 16) + 1 : mod(c, 16) + 1)
   end function hex2

   !> Escape a string for inclusion as a JSON string body (no surrounding
   !> quotes): handles ", \, the short control escapes, and other control
   !> characters as \u00XX.
   pure function json_escape(s) result(o)
      character(len=*), intent(in)  :: s
      character(len=:), allocatable :: o
      integer   :: i, c
      character :: ch
      ! Fast path: most keys/values contain nothing that needs escaping, so
      ! return the input unchanged (a single allocation) rather than rebuilding
      ! it character by character. " (34), \ (92), and control chars (< 32) are
      ! the only characters this escaper rewrites.
      do i = 1, len(s)
         c = iachar(s(i:i))
         if (c == 34 .or. c == 92 .or. c < 32) exit
      end do
      if (i > len(s)) then
         o = s
         return
      end if
      ! Slow path: at least one character needs escaping.
      o = ''
      do i = 1, len(s)
         ch = s(i:i)
         c = iachar(ch)
         select case (c)
         case (34);  o = o // '\"'
         case (92);  o = o // '\\'
         case (8);   o = o // '\b'
         case (9);   o = o // '\t'
         case (10);  o = o // '\n'
         case (12);  o = o // '\f'
         case (13);  o = o // '\r'
         case (0:7, 11, 14:31); o = o // '\u00' // hex2(c)
         case default; o = o // ch
         end select
      end do
   end function json_escape

   subroutine meta_append_pair(self, key, valjson)
      class(tensogram_meta), intent(inout) :: self
      character(len=*),      intent(in)    :: key, valjson
      if (.not. allocated(self%body)) self%body = ''
      if (len(self%body) > 0) self%body = self%body // ','
      self%body = self%body // '"' // json_escape(key) // '":' // valjson
   end subroutine meta_append_pair

   subroutine meta_add_string(self, key, val)
      class(tensogram_meta), intent(inout) :: self
      character(len=*),      intent(in)    :: key, val
      call meta_append_pair(self, key, '"' // json_escape(val) // '"')
   end subroutine meta_add_string

   subroutine meta_add_int(self, key, val)
      class(tensogram_meta), intent(inout) :: self
      character(len=*),      intent(in)    :: key
      integer(c_int64_t),    intent(in)    :: val
      call meta_append_pair(self, key, itoa(val))
   end subroutine meta_add_int

   subroutine meta_add_real(self, key, val)
      class(tensogram_meta), intent(inout) :: self
      character(len=*),      intent(in)    :: key
      real(c_double),        intent(in)    :: val
      character(len=64) :: tmp
      write (tmp, '(g0)') val
      call meta_append_pair(self, key, trim(adjustl(tmp)))
   end subroutine meta_add_real

   !> Emit the accumulated keys as a `"base":[{...}]` top-level JSON fragment,
   !> suitable as the `metadata_json` argument of encode / append.
   function meta_base_json(self) result(js)
      class(tensogram_meta), intent(in) :: self
      character(len=:), allocatable :: js
      if (allocated(self%body)) then
         js = '"base":[{' // self%body // '}]'
      else
         js = '"base":[{}]'
      end if
   end function meta_base_json

   ! =========================================================================
   !  Metadata handle + getters
   ! =========================================================================

   subroutine metadata_free(self)
      class(tensogram_metadata), intent(inout) :: self
      if (c_associated(self%ptr)) then
         call c_tgm_metadata_free(self%ptr)
         self%ptr = c_null_ptr
      end if
   end subroutine metadata_free

   subroutine metadata_final(self)
      type(tensogram_metadata), intent(inout) :: self
      call self%free()
   end subroutine metadata_final

   subroutine metadata_assign(lhs, rhs)
      class(tensogram_metadata), intent(out) :: lhs
      type(tensogram_metadata),  intent(in)  :: rhs
      if (c_associated(rhs%ptr)) then
         error stop "tensogram_metadata is non-copyable: assigning a live handle would alias and double-free; pass by reference"
      else
         error stop "tensogram_metadata is non-copyable: do not assign handles; pass by reference"
      end if
   end subroutine metadata_assign

   !> Extract an independent metadata handle from a decoded message.
   subroutine tensogram_message_metadata(msg, meta, err)
      type(tensogram_message),  intent(in)  :: msg
      type(tensogram_metadata), intent(out) :: meta
      integer(c_int),           intent(out) :: err
      type(c_ptr) :: out
      err = c_tgm_message_metadata(msg%ptr, out)
      if (err == TGM_ERROR_OK) meta%ptr = out
   end subroutine tensogram_message_metadata

   !> Look up a string value by dot-notation key (searches base[i] then
   !> _extra_). Returns '' when the key is absent or not a string.
   !>
   !> DOC-DEPRECATED (coercing, absent==default): the '' sentinel cannot
   !> distinguish an absent key from a stored empty string, and integer / float
   !> / bool leaves are coerced to text. For precise access prefer
   !> `tensogram_metadata_try_get_string` (found flag) or
   !> `tensogram_metadata_get(...)%as_string(...)`.
   function tensogram_metadata_get_string(meta, key) result(val)
      type(tensogram_metadata), intent(in) :: meta
      character(len=*),         intent(in) :: key
      character(len=:), allocatable :: val
      character(kind=c_char), allocatable, target :: key_c(:)
      call f_to_cstr(trim(key), key_c)
      val = cptr_to_fstr(c_tgm_metadata_get_string(meta%ptr, c_loc(key_c)))
   end function tensogram_metadata_get_string

   !> Look up an integer value by dot-notation key; `default_val` when absent.
   !>
   !> DOC-DEPRECATED: `default_val` hides "absent" behind a real value equal to
   !> the default. Prefer `tensogram_metadata_try_get_int` (found flag) or
   !> `tensogram_metadata_get(...)%as_int(...)`.
   function tensogram_metadata_get_int(meta, key, default_val) result(v)
      type(tensogram_metadata), intent(in) :: meta
      character(len=*),         intent(in) :: key
      integer(c_int64_t),       intent(in) :: default_val
      integer(c_int64_t) :: v
      character(kind=c_char), allocatable, target :: key_c(:)
      call f_to_cstr(trim(key), key_c)
      v = c_tgm_metadata_get_int(meta%ptr, c_loc(key_c), default_val)
   end function tensogram_metadata_get_int

   !> Look up a float value by dot-notation key; `default_val` when absent.
   !>
   !> DOC-DEPRECATED: `default_val` hides "absent" behind a real value equal to
   !> the default. Prefer `tensogram_metadata_try_get_float` (found flag) or
   !> `tensogram_metadata_get(...)%as_float(...)`.
   function tensogram_metadata_get_float(meta, key, default_val) result(v)
      type(tensogram_metadata), intent(in) :: meta
      character(len=*),         intent(in) :: key
      real(c_double),           intent(in) :: default_val
      real(c_double) :: v
      character(kind=c_char), allocatable, target :: key_c(:)
      call f_to_cstr(trim(key), key_c)
      v = c_tgm_metadata_get_float(meta%ptr, c_loc(key_c), default_val)
   end function tensogram_metadata_get_float

   ! =========================================================================
   !  Precise metadata access — value cursor (tensogram_value) + accessors
   !  (metadata-access parity). No coercion; absent is distinct from
   !  wrong-type and from a stored default. All handles/strings are borrowed
   !  from the parent tensogram_metadata and valid only until it is freed.
   ! =========================================================================

   !> .true. when this cursor refers to a present value (non-NULL handle).
   logical function value_is_present(self)
      class(tensogram_value), intent(in) :: self
      value_is_present = c_associated(self%ptr)
   end function value_is_present

   !> The value kind as a TGM_VALUE_TYPE_* code. TGM_VALUE_TYPE_NULL for an
   !> absent (non-present) cursor as well as a genuine CBOR null.
   function value_kind(self) result(k)
      class(tensogram_value), intent(in) :: self
      integer(c_int) :: k
      k = c_tgm_value_get_type(self%ptr)
   end function value_kind

   !> Extract a signed 64-bit integer (integer values only, no coercion).
   !> Returns .true. and sets `val` only when the value is an i64-range integer.
   logical function value_as_int(self, val)
      class(tensogram_value), intent(in)  :: self
      integer(c_int64_t),     intent(out) :: val
      value_as_int = c_tgm_value_as_i64(self%ptr, val)
   end function value_as_int

   !> Extract an unsigned 64-bit integer as its i64 bit pattern (Fortran has no
   !> unsigned type). Returns .true. only for a u64-range integer.
   logical function value_as_uint(self, val)
      class(tensogram_value), intent(in)  :: self
      integer(c_int64_t),     intent(out) :: val
      value_as_uint = c_tgm_value_as_u64(self%ptr, val)
   end function value_as_uint

   !> Extract a double: a float as-is, or an integer widened to f64 (the one
   !> widening accessor). Returns .true. only for a numeric value.
   logical function value_as_float(self, val)
      class(tensogram_value), intent(in)  :: self
      real(c_double),         intent(out) :: val
      value_as_float = c_tgm_value_as_f64(self%ptr, val)
   end function value_as_float

   !> Extract a boolean (no coercion). Returns .true. and sets `val` only when
   !> the value is a boolean.
   logical function value_as_bool(self, val)
      class(tensogram_value), intent(in)  :: self
      logical,                intent(out) :: val
      logical(c_bool) :: b
      value_as_bool = c_tgm_value_as_bool(self%ptr, b)
      if (value_as_bool) val = b
   end function value_as_bool

   !> Borrow a string value (text only). Returns .true. and allocates `val`
   !> (exact byte length, interior NULs preserved) only when it is a string;
   !> a stored empty string is a present string ('' with found=.true.), which
   !> is distinct from an absent key (found=.false.).
   logical function value_as_string(self, val)
      class(tensogram_value),        intent(in)  :: self
      character(len=:), allocatable, intent(out) :: val
      type(c_ptr)       :: p
      integer(c_size_t) :: n
      p = c_tgm_value_as_string(self%ptr, n)
       if (c_associated(p)) then
          val = cptr_len_to_fstr(p, n)
          value_as_string = .true.
       else
          value_as_string = .false.
       end if
    end function value_as_string

    !> Borrow a byte-string value (byte strings only). Returns .true. and
    !> allocates `val` to the exact length only when the value is a byte
    !> string (a present zero-length byte string gives a size-0 array with
    !> found=.true., distinct from an absent key, found=.false.); .false.
    !> otherwise. Bytes map onto signed int8 — the same bit pattern, since
    !> Fortran has no unsigned kind.
    logical function value_as_bytes(self, val)
       class(tensogram_value),         intent(in)  :: self
       integer(c_int8_t), allocatable, intent(out) :: val(:)
       type(c_ptr)                :: p
       integer(c_size_t)          :: n
       integer(c_int8_t), pointer :: view(:)
       p = c_tgm_value_as_bytes(self%ptr, n)
       if (.not. c_associated(p)) then
          value_as_bytes = .false.
          return
       end if
       allocate(val(n))
       if (n > 0_c_size_t) then
          call c_f_pointer(p, view, [n])
          val = view
       end if
       value_as_bytes = .true.
    end function value_as_bytes

   !> Number of elements in an array (or entries in a map); 0 for any other
   !> kind or an absent cursor.
   function value_len(self) result(n)
      class(tensogram_value), intent(in) :: self
      integer        :: n
      integer(c_int) :: k
      k = c_tgm_value_get_type(self%ptr)
      if (k == TGM_VALUE_TYPE_ARRAY) then
         n = int(c_tgm_value_array_len(self%ptr))
      else if (k == TGM_VALUE_TYPE_MAP) then
         n = int(c_tgm_value_map_len(self%ptr))
      else
         n = 0
      end if
   end function value_len

   !> Array element `i` (1-based) as a value cursor; an absent cursor if `i`
   !> is out of range or this is not an array.
    function value_elem(self, i) result(v)
       class(tensogram_value), intent(in) :: self
       integer,                intent(in) :: i
       type(tensogram_value) :: v
       ! Guard the 1-based index explicitly: forming the 0-based C index from
       ! i < 1 would convert a negative value to unsigned c_size_t (wrap-around).
       if (i < 1) return  ! v defaults to an absent (C_NULL_PTR) cursor
       v%ptr = c_tgm_value_array_get(self%ptr, int(i - 1, c_size_t))
    end function value_elem

   !> Map key `i` (1-based) as a string; '' if out of range or not a map.
   function value_key(self, i) result(k)
      class(tensogram_value), intent(in) :: self
      integer,                intent(in) :: i
       character(len=:), allocatable :: k
       type(c_ptr)       :: p
       integer(c_size_t) :: n
       if (i < 1) then       ! see value_elem: guard before the 0-based conversion
          k = ''
          return
       end if
       p = c_tgm_value_map_key_at(self%ptr, int(i - 1, c_size_t), n)
      if (c_associated(p)) then
         k = cptr_len_to_fstr(p, n)
      else
         k = ''
      end if
   end function value_key

   !> Map value `i` (1-based) as a value cursor (same order as %key).
    function value_value(self, i) result(v)
       class(tensogram_value), intent(in) :: self
       integer,                intent(in) :: i
       type(tensogram_value) :: v
       if (i < 1) return  ! see value_elem: v defaults to an absent cursor
       v%ptr = c_tgm_value_map_value_at(self%ptr, int(i - 1, c_size_t))
    end function value_value

   !> Single-segment map lookup (does NOT split on '.'; use
   !> tensogram_metadata_get for dot-paths). Absent cursor if the key is
   !> missing or this is not a map. On a base[i] section this can reach
   !> `_reserved_` (enumeration parity).
   function value_get(self, key) result(v)
      class(tensogram_value), intent(in) :: self
      character(len=*),       intent(in) :: key
      type(tensogram_value) :: v
      character(kind=c_char), allocatable, target :: key_c(:)
      call f_to_cstr(trim(key), key_c)
      v%ptr = c_tgm_value_map_get(self%ptr, c_loc(key_c))
   end function value_get

   !> Number of objects (length of `base`) described in the metadata.
   function tensogram_metadata_num_objects(meta) result(n)
      type(tensogram_metadata), intent(in) :: meta
      integer :: n
      n = int(c_tgm_metadata_num_objects(meta%ptr))
   end function tensogram_metadata_num_objects

   !> Existence check for a dot-notation path. With `obj_index` (1-based) the
   !> lookup is scoped to base[obj_index] (no cross-object first-match, no
   !> _extra_ fallback, _reserved_ hidden at the first segment); without it the
   !> lookup is message-level (first match across base[i], then _extra_).
   logical function tensogram_metadata_has(meta, key, obj_index)
      type(tensogram_metadata), intent(in)           :: meta
      character(len=*),         intent(in)           :: key
      integer,                  intent(in), optional :: obj_index
      character(kind=c_char), allocatable, target :: key_c(:)
      call f_to_cstr(trim(key), key_c)
      if (present(obj_index)) then
         tensogram_metadata_has = &
            c_tgm_metadata_has_at(meta%ptr, int(obj_index - 1, c_size_t), c_loc(key_c))
      else
         tensogram_metadata_has = c_tgm_metadata_has(meta%ptr, c_loc(key_c))
      end if
   end function tensogram_metadata_has

   !> Look up a value cursor by dot-notation path. Message-level by default,
   !> or scoped to base[obj_index] (1-based) when `obj_index` is present.
   !> Presence is `result%is_present()`, so a stored 0 / '' / null is
   !> distinguishable from an absent key.
   function tensogram_metadata_get(meta, key, obj_index) result(v)
      type(tensogram_metadata), intent(in)           :: meta
      character(len=*),         intent(in)           :: key
      integer,                  intent(in), optional :: obj_index
      type(tensogram_value) :: v
      character(kind=c_char), allocatable, target :: key_c(:)
      call f_to_cstr(trim(key), key_c)
      if (present(obj_index)) then
         v%ptr = c_tgm_metadata_get_at(meta%ptr, int(obj_index - 1, c_size_t), c_loc(key_c))
      else
         v%ptr = c_tgm_metadata_get(meta%ptr, c_loc(key_c))
      end if
   end function tensogram_metadata_get

   !> Typed get: integer. Returns .true. and sets `value` only when the path is
   !> present AND an i64-range integer. Scoping matches tensogram_metadata_get.
   logical function tensogram_metadata_try_get_int(meta, key, value, obj_index)
      type(tensogram_metadata), intent(in)           :: meta
      character(len=*),         intent(in)           :: key
      integer(c_int64_t),       intent(out)          :: value
      integer,                  intent(in), optional :: obj_index
      type(tensogram_value) :: v
      v = tensogram_metadata_get(meta, key, obj_index)
      tensogram_metadata_try_get_int = v%as_int(value)
   end function tensogram_metadata_try_get_int

   !> Typed get: float (float, or integer widened to f64). Returns .true. and
   !> sets `value` only when the path is present AND numeric.
   logical function tensogram_metadata_try_get_float(meta, key, value, obj_index)
      type(tensogram_metadata), intent(in)           :: meta
      character(len=*),         intent(in)           :: key
      real(c_double),           intent(out)          :: value
      integer,                  intent(in), optional :: obj_index
      type(tensogram_value) :: v
      v = tensogram_metadata_get(meta, key, obj_index)
      tensogram_metadata_try_get_float = v%as_float(value)
   end function tensogram_metadata_try_get_float

   !> Typed get: string (text only, no coercion). Returns .true. and allocates
   !> `value` only when the path is present AND a string (a stored '' counts).
   logical function tensogram_metadata_try_get_string(meta, key, value, obj_index)
      type(tensogram_metadata),      intent(in)           :: meta
      character(len=*),              intent(in)           :: key
      character(len=:), allocatable, intent(out)          :: value
      integer,                       intent(in), optional :: obj_index
      type(tensogram_value) :: v
      v = tensogram_metadata_get(meta, key, obj_index)
      tensogram_metadata_try_get_string = v%as_string(value)
   end function tensogram_metadata_try_get_string

   !> Typed get: boolean (no coercion). Returns .true. and sets `value` only
   !> when the path is present AND a boolean.
   logical function tensogram_metadata_try_get_bool(meta, key, value, obj_index)
      type(tensogram_metadata), intent(in)           :: meta
      character(len=*),         intent(in)           :: key
      logical,                  intent(out)          :: value
      integer,                  intent(in), optional :: obj_index
      type(tensogram_value) :: v
      v = tensogram_metadata_get(meta, key, obj_index)
      tensogram_metadata_try_get_bool = v%as_bool(value)
   end function tensogram_metadata_try_get_bool

   !> View base[obj_index] (1-based) as a map cursor for enumeration. INCLUDES
   !> `_reserved_` (parity with the JSON export / Python's meta.base[i]),
   !> unlike the path getters which hide it. An out-of-range index yields an
   !> absent cursor.
   function tensogram_metadata_object(meta, obj_index) result(v)
      type(tensogram_metadata), intent(in) :: meta
      integer,                  intent(in) :: obj_index
      type(tensogram_value) :: v
      v%ptr = c_tgm_metadata_object(meta%ptr, int(obj_index - 1, c_size_t))
   end function tensogram_metadata_object

   !> View the message-level `_extra_` section as a map cursor. Empty section
   !> is a present, empty map (%len() == 0) — distinct from an absent cursor.
   function tensogram_metadata_extra(meta) result(v)
      type(tensogram_metadata), intent(in) :: meta
      type(tensogram_value) :: v
      v%ptr = c_tgm_metadata_extra(meta%ptr)
   end function tensogram_metadata_extra

   !> View the message-level `_reserved_` section (library-managed namespace,
   !> e.g. tensor descriptors) as a map cursor.
   function tensogram_metadata_reserved(meta) result(v)
      type(tensogram_metadata), intent(in) :: meta
      type(tensogram_value) :: v
      v%ptr = c_tgm_metadata_reserved(meta%ptr)
   end function tensogram_metadata_reserved

   ! =========================================================================
   !  Streaming encoder
   ! =========================================================================

   subroutine stream_enc_free(self)
      class(tensogram_streaming_encoder), intent(inout) :: self
      if (c_associated(self%ptr)) then
         call c_tgm_streaming_encoder_free(self%ptr)
         self%ptr = c_null_ptr
      end if
   end subroutine stream_enc_free

   subroutine stream_enc_final(self)
      type(tensogram_streaming_encoder), intent(inout) :: self
      call self%free()
   end subroutine stream_enc_final

   subroutine stream_enc_assign(lhs, rhs)
      class(tensogram_streaming_encoder), intent(out) :: lhs
      type(tensogram_streaming_encoder),  intent(in)  :: rhs
      if (c_associated(rhs%ptr)) then
         error stop "tensogram_streaming_encoder is non-copyable (live handle); pass by reference"
      else
         error stop "tensogram_streaming_encoder is non-copyable; pass by reference"
      end if
   end subroutine stream_enc_assign

   !> Open a streaming encoder writing a single multi-object message to `path`.
   !> `metadata_json` is free-form message-level GlobalMetadata (NOT a
   !> descriptors map; objects are supplied via _write); defaults to `{}`.
   subroutine tensogram_streaming_encoder_create(path, enc, err, metadata_json, hash)
      character(len=*),                  intent(in)  :: path
      type(tensogram_streaming_encoder), intent(out) :: enc
      integer(c_int),                    intent(out) :: err
      character(len=*), intent(in), optional :: metadata_json, hash
      character(kind=c_char), allocatable, target :: path_c(:), meta_c(:), hash_c(:)
      character(len=:),       allocatable         :: meta_s
      type(c_ptr) :: hash_ptr, out
      call f_to_cstr(trim(path), path_c)
      if (present(metadata_json)) then
         meta_s = metadata_json
      else
         meta_s = '{}'
      end if
      call f_to_cstr(meta_s, meta_c)
      call resolve_hash(hash, hash_c, hash_ptr)
      err = c_tgm_streaming_encoder_create(c_loc(path_c), c_loc(meta_c), hash_ptr, &
                                           0_c_int32_t, out)
      if (err == TGM_ERROR_OK) enc%ptr = out
   end subroutine tensogram_streaming_encoder_create

   !> Finalise the stream: write the footer index/hash + postamble and close
   !> the file. The handle remains valid (release it with `enc%free()`).
   subroutine tensogram_streaming_encoder_finish(enc, err)
      type(tensogram_streaming_encoder), intent(inout) :: enc
      integer(c_int),                    intent(out)   :: err
      err = c_tgm_streaming_encoder_finish(enc%ptr)
   end subroutine tensogram_streaming_encoder_finish

   !> Number of data objects written so far.
   function tensogram_streaming_encoder_count(enc) result(n)
      type(tensogram_streaming_encoder), intent(in) :: enc
      integer :: n
      n = int(c_tgm_streaming_encoder_count(enc%ptr))
   end function tensogram_streaming_encoder_count

   !> Encode one tensor (described by `ptr` + `nbytes` + Fortran `fshape` +
   !> `dtype`) and append it to the open stream as a data-object frame.
   subroutine stream_write_core(enc_ptr, ptr, nbytes, fshape, dtype, err, &
                                encoding, filter, compression)
      type(c_ptr),        intent(in)  :: enc_ptr
      type(c_ptr),        intent(in)  :: ptr
      integer(c_size_t),  intent(in)  :: nbytes
      integer(c_int64_t), intent(in)  :: fshape(:)
      character(len=*),   intent(in)  :: dtype
      integer(c_int),     intent(out) :: err
      character(len=*), intent(in), optional :: encoding, filter, compression
      character(kind=c_char), allocatable, target :: desc_c(:)
      character(len=:),       allocatable         :: desc_s
      desc_s = descriptor_object_json(fshape, dtype, encoding, filter, compression)
      call f_to_cstr(desc_s, desc_c)
      err = c_tgm_streaming_encoder_write(enc_ptr, c_loc(desc_c), ptr, nbytes)
   end subroutine stream_write_core

#define FAM stream_write_
#define TGM_BODY "tgm_stream_write.inc"
#define KS f32
#define DT real(c_float)
#define DTSTR 'float32'
#include "tgm_ranks.inc"
#undef DTSTR
#undef DT
#undef KS
#define KS f64
#define DT real(c_double)
#define DTSTR 'float64'
#include "tgm_ranks.inc"
#undef DTSTR
#undef DT
#undef KS
#define KS i32
#define DT integer(c_int32_t)
#define DTSTR 'int32'
#include "tgm_ranks.inc"
#undef DTSTR
#undef DT
#undef KS
#define KS i64
#define DT integer(c_int64_t)
#define DTSTR 'int64'
#include "tgm_ranks.inc"
#undef DTSTR
#undef DT
#undef KS
#undef TGM_BODY
#undef FAM

end module tensogram
