// Integration tests for tensogram-netcdf.
//
// Fixture files live in testdata/ — generated by testdata/generate.py.
// Run `python testdata/generate.py` to regenerate them.
//
// DecodedObject = (DataObjectDescriptor, Vec<u8>)
// Access descriptor via .0, data bytes via .1

use tensogram_core::{decode, DecodeOptions, Dtype};
use tensogram_netcdf::{convert_netcdf_file, ConvertOptions, NetcdfError, SplitBy};

fn testdata(name: &str) -> std::path::PathBuf {
    let mut path = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    path.push("testdata");
    path.push(name);
    path
}

type DecodedMsg = (
    tensogram_core::types::GlobalMetadata,
    Vec<tensogram_core::types::DecodedObject>,
);

fn decode_first(msgs: &[Vec<u8>]) -> DecodedMsg {
    decode(&msgs[0], &DecodeOptions::default()).expect("decode failed")
}

// ── Task 6: Minimal converter ─────────────────────────────────────────────────

#[test]
fn simple_2d_produces_one_message() {
    let path = testdata("simple_2d.nc");
    let msgs = convert_netcdf_file(&path, &ConvertOptions::default()).unwrap();
    assert_eq!(
        msgs.len(),
        1,
        "SplitBy::File should produce exactly 1 message"
    );
}

#[test]
fn simple_2d_has_one_object_with_correct_shape() {
    let path = testdata("simple_2d.nc");
    let msgs = convert_netcdf_file(&path, &ConvertOptions::default()).unwrap();
    let (meta, objects) = decode_first(&msgs);
    assert_eq!(objects.len(), 1, "simple_2d.nc has 1 variable 'data'");
    assert_eq!(meta.base.len(), 1);
    assert_eq!(objects[0].0.shape, vec![5, 4]);
    assert_eq!(objects[0].0.dtype, Dtype::Float64);
}

#[test]
fn simple_2d_data_roundtrip() {
    let path = testdata("simple_2d.nc");
    let msgs = convert_netcdf_file(&path, &ConvertOptions::default()).unwrap();
    let (_, objects) = decode_first(&msgs);
    // 5*4 = 20 f64 values = 160 bytes
    assert_eq!(objects[0].1.len(), 20 * 8);
}

// ── Task 7: Dtype matrix ──────────────────────────────────────────────────────

#[test]
fn multi_dtype_preserves_native_dtypes() {
    let path = testdata("multi_dtype.nc");
    let msgs = convert_netcdf_file(&path, &ConvertOptions::default()).unwrap();
    let (meta, objects) = decode_first(&msgs);

    let mut dtype_map = std::collections::HashMap::new();
    for (i, obj) in objects.iter().enumerate() {
        if let Some(ciborium::Value::Text(name)) = meta.base[i].get("name") {
            dtype_map.insert(name.clone(), obj.0.dtype);
        }
    }

    // Variables without scale_factor/add_offset should preserve native dtype
    assert_eq!(dtype_map.get("i8"), Some(&Dtype::Int8));
    assert_eq!(dtype_map.get("i16"), Some(&Dtype::Int16));
    assert_eq!(dtype_map.get("i32"), Some(&Dtype::Int32));
    assert_eq!(dtype_map.get("i64"), Some(&Dtype::Int64));
    assert_eq!(dtype_map.get("u8"), Some(&Dtype::Uint8));
    assert_eq!(dtype_map.get("u16"), Some(&Dtype::Uint16));
    assert_eq!(dtype_map.get("u32"), Some(&Dtype::Uint32));
    assert_eq!(dtype_map.get("u64"), Some(&Dtype::Uint64));
    assert_eq!(dtype_map.get("f32"), Some(&Dtype::Float32));
    assert_eq!(dtype_map.get("f64"), Some(&Dtype::Float64));
}

// ── Task 8: Metadata extraction ───────────────────────────────────────────────

#[test]
fn cf_temperature_has_netcdf_metadata() {
    let path = testdata("cf_temperature.nc");
    let msgs = convert_netcdf_file(&path, &ConvertOptions::default()).unwrap();
    let (meta, _) = decode_first(&msgs);

    let temp_entry = meta.base.iter().find(|e| {
        e.get("name").and_then(|v| {
            if let ciborium::Value::Text(s) = v {
                Some(s.as_str())
            } else {
                None
            }
        }) == Some("temperature")
    });
    assert!(
        temp_entry.is_some(),
        "temperature variable should be in base"
    );

    let entry = temp_entry.unwrap();
    let netcdf_meta = entry.get("netcdf").expect("should have netcdf metadata");
    assert!(
        matches!(netcdf_meta, ciborium::Value::Map(_)),
        "netcdf metadata should be a map"
    );
}

#[test]
fn cf_temperature_no_cf_key_without_flag() {
    let path = testdata("cf_temperature.nc");
    let msgs = convert_netcdf_file(&path, &ConvertOptions::default()).unwrap();
    let (meta, _) = decode_first(&msgs);

    for entry in &meta.base {
        assert!(!entry.contains_key("cf"), "no 'cf' key without --cf flag");
    }
}

#[test]
fn cf_temperature_has_cf_key_with_flag() {
    let path = testdata("cf_temperature.nc");
    let opts = ConvertOptions {
        cf: true,
        ..Default::default()
    };
    let msgs = convert_netcdf_file(&path, &opts).unwrap();
    let (meta, _) = decode_first(&msgs);

    let temp_entry = meta.base.iter().find(|e| {
        e.get("name").and_then(|v| {
            if let ciborium::Value::Text(s) = v {
                Some(s.as_str())
            } else {
                None
            }
        }) == Some("temperature")
    });
    assert!(temp_entry.is_some());
    let entry = temp_entry.unwrap();
    assert!(
        entry.contains_key("cf"),
        "temperature should have 'cf' key with --cf flag"
    );
}

// ── Task 9: Packed data + fill values ─────────────────────────────────────────

#[test]
fn cf_temperature_unpacks_to_f64() {
    let path = testdata("cf_temperature.nc");
    let msgs = convert_netcdf_file(&path, &ConvertOptions::default()).unwrap();
    let (_, objects) = decode_first(&msgs);

    // temperature has scale_factor/add_offset → should be unpacked to f64
    let has_f64 = objects.iter().any(|o| o.0.dtype == Dtype::Float64);
    assert!(has_f64, "packed variable should be unpacked to f64");
}

#[test]
fn multi_dtype_nan_values_in_f64_with_nan() {
    let path = testdata("multi_dtype.nc");
    let msgs = convert_netcdf_file(&path, &ConvertOptions::default()).unwrap();
    let (meta, objects) = decode_first(&msgs);

    let nan_idx = meta.base.iter().position(|e| {
        e.get("name").and_then(|v| {
            if let ciborium::Value::Text(s) = v {
                Some(s.as_str())
            } else {
                None
            }
        }) == Some("f64_with_nan")
    });

    if let Some(idx) = nan_idx {
        let data = &objects[idx].1;
        let floats: Vec<f64> = data
            .chunks_exact(8)
            .map(|b| f64::from_le_bytes(b.try_into().unwrap()))
            .collect();
        assert!(
            floats.iter().any(|v: &f64| v.is_nan()),
            "f64_with_nan should contain NaN values"
        );
    }
}

// ── Task 10: --split-by grouping ──────────────────────────────────────────────

#[test]
fn split_by_file_produces_one_message() {
    let path = testdata("multi_var.nc");
    let opts = ConvertOptions {
        split_by: SplitBy::File,
        ..Default::default()
    };
    let msgs = convert_netcdf_file(&path, &opts).unwrap();
    assert_eq!(msgs.len(), 1);
}

#[test]
fn split_by_variable_produces_one_message_per_variable() {
    let path = testdata("multi_var.nc");
    let opts = ConvertOptions {
        split_by: SplitBy::Variable,
        ..Default::default()
    };
    let msgs = convert_netcdf_file(&path, &opts).unwrap();
    // multi_var.nc has temperature, humidity, pressure (char var is skipped)
    assert!(
        msgs.len() >= 3,
        "should have at least 3 messages for 3 numeric vars"
    );
    // Each message should have exactly 1 object
    for msg in &msgs {
        let (_, objects) = decode(msg, &DecodeOptions::default()).unwrap();
        assert_eq!(
            objects.len(),
            1,
            "each message should have 1 object in variable mode"
        );
    }
}

#[test]
fn split_by_record_produces_one_message_per_record() {
    let path = testdata("unlimited_time.nc");
    let opts = ConvertOptions {
        split_by: SplitBy::Record,
        ..Default::default()
    };
    let msgs = convert_netcdf_file(&path, &opts).unwrap();
    // unlimited_time.nc has 5 timesteps
    assert_eq!(
        msgs.len(),
        5,
        "should produce 5 messages for 5 time records"
    );
}

#[test]
fn split_by_record_errors_without_unlimited_dim() {
    let path = testdata("simple_2d.nc");
    let opts = ConvertOptions {
        split_by: SplitBy::Record,
        ..Default::default()
    };
    let result = convert_netcdf_file(&path, &opts);
    assert!(
        matches!(result, Err(NetcdfError::NoUnlimitedDimension { .. })),
        "should error when no unlimited dimension"
    );
}

// ── Task 11: --cf flag ────────────────────────────────────────────────────────

#[test]
fn cf_flag_extracts_standard_name() {
    let path = testdata("cf_temperature.nc");
    let opts = ConvertOptions {
        cf: true,
        ..Default::default()
    };
    let msgs = convert_netcdf_file(&path, &opts).unwrap();
    let (meta, _) = decode_first(&msgs);

    let temp_entry = meta.base.iter().find(|e| {
        e.get("name").and_then(|v| {
            if let ciborium::Value::Text(s) = v {
                Some(s.as_str())
            } else {
                None
            }
        }) == Some("temperature")
    });
    assert!(temp_entry.is_some());
    let cf_val = temp_entry.unwrap().get("cf").expect("should have cf key");
    if let ciborium::Value::Map(cf_map) = cf_val {
        let has_standard_name = cf_map
            .iter()
            .any(|(k, _)| matches!(k, ciborium::Value::Text(s) if s == "standard_name"));
        assert!(has_standard_name, "cf map should contain standard_name");
    } else {
        panic!("cf value should be a map");
    }
}

// ── Task 12: Edge cases ───────────────────────────────────────────────────────

#[test]
fn empty_file_returns_no_variables_error() {
    let path = testdata("empty_file.nc");
    let result = convert_netcdf_file(&path, &ConvertOptions::default());
    assert!(
        matches!(result, Err(NetcdfError::NoVariables)),
        "empty file should return NoVariables error, got: {:?}",
        result
    );
}

#[test]
fn nc3_classic_converts_successfully() {
    let path = testdata("nc3_classic.nc");
    let msgs = convert_netcdf_file(&path, &ConvertOptions::default()).unwrap();
    assert_eq!(
        msgs.len(),
        1,
        "NC3 classic file should convert to 1 message"
    );
    let (_, objects) = decode_first(&msgs);
    assert!(!objects.is_empty(), "should have at least 1 object");
}

#[test]
fn nc4_groups_warns_and_converts_root_only() {
    // nc4_groups.nc has root_var in root + predicted in sub-group
    // We should get root_var but not predicted
    let path = testdata("nc4_groups.nc");
    let msgs = convert_netcdf_file(&path, &ConvertOptions::default()).unwrap();
    assert_eq!(msgs.len(), 1);
    let (meta, _) = decode_first(&msgs);

    let has_root_var = meta.base.iter().any(|e| {
        e.get("name").and_then(|v| {
            if let ciborium::Value::Text(s) = v {
                Some(s.as_str())
            } else {
                None
            }
        }) == Some("root_var")
    });
    assert!(has_root_var, "root_var should be present");

    let has_predicted = meta.base.iter().any(|e| {
        e.get("name").and_then(|v| {
            if let ciborium::Value::Text(s) = v {
                Some(s.as_str())
            } else {
                None
            }
        }) == Some("predicted")
    });
    assert!(
        !has_predicted,
        "predicted (sub-group var) should NOT be present"
    );
}

#[test]
fn multi_var_skips_char_variables() {
    let path = testdata("multi_var.nc");
    let msgs = convert_netcdf_file(&path, &ConvertOptions::default()).unwrap();
    let (meta, _) = decode_first(&msgs);

    let has_description = meta.base.iter().any(|e| {
        e.get("name").and_then(|v| {
            if let ciborium::Value::Text(s) = v {
                Some(s.as_str())
            } else {
                None
            }
        }) == Some("description")
    });
    assert!(
        !has_description,
        "char variable 'description' should be skipped"
    );
}

#[test]
fn multi_var_has_all_numeric_variables() {
    let path = testdata("multi_var.nc");
    let msgs = convert_netcdf_file(&path, &ConvertOptions::default()).unwrap();
    let (meta, _) = decode_first(&msgs);
    let names: Vec<&str> = meta
        .base
        .iter()
        .filter_map(|e| {
            e.get("name").and_then(|v| {
                if let ciborium::Value::Text(s) = v {
                    Some(s.as_str())
                } else {
                    None
                }
            })
        })
        .collect();
    assert!(
        names.contains(&"temperature"),
        "temperature should be present"
    );
    assert!(names.contains(&"humidity"), "humidity should be present");
    assert!(names.contains(&"pressure"), "pressure should be present");
}

#[test]
fn scalar_variable_has_empty_shape() {
    // multi_dtype.nc has a scalar 'pi' variable (ndim=0)
    let path = testdata("multi_dtype.nc");
    let msgs = convert_netcdf_file(&path, &ConvertOptions::default()).unwrap();
    let (meta, objects) = decode_first(&msgs);

    let pi_idx = meta.base.iter().position(|e| {
        e.get("name").and_then(|v| {
            if let ciborium::Value::Text(s) = v {
                Some(s.as_str())
            } else {
                None
            }
        }) == Some("pi")
    });

    if let Some(idx) = pi_idx {
        assert_eq!(
            objects[idx].0.shape,
            vec![],
            "scalar should have empty shape"
        );
        assert_eq!(objects[idx].0.ndim, 0, "scalar should have ndim=0");
    }
    // If pi not found, fixture may not have it — test is vacuously passing
}

#[test]
fn unlimited_time_static_var_included_in_record_split() {
    // unlimited_time.nc has temp(time,y,x) and mask(y,x)
    // In record split, mask should appear in each record message
    let path = testdata("unlimited_time.nc");
    let opts = ConvertOptions {
        split_by: SplitBy::Record,
        ..Default::default()
    };
    let msgs = convert_netcdf_file(&path, &opts).unwrap();
    assert!(!msgs.is_empty());

    let (meta, _) = decode(&msgs[0], &DecodeOptions::default()).unwrap();
    let has_mask = meta.base.iter().any(|e| {
        e.get("name").and_then(|v| {
            if let ciborium::Value::Text(s) = v {
                Some(s.as_str())
            } else {
                None
            }
        }) == Some("mask")
    });
    assert!(
        has_mask,
        "static variable 'mask' should appear in each record message"
    );
}
