/* Tensogram C API — generated by cbindgen. Do not edit. */

#ifndef TENSOGRAM_H
#define TENSOGRAM_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef enum tgm_TgmError {
  OK = 0,
  FRAMING = 1,
  METADATA = 2,
  ENCODING = 3,
  COMPRESSION = 4,
  OBJECT = 5,
  IO = 6,
  HASH_MISMATCH = 7,
  INVALID_ARG = 8,
  /**
   * Returned by `tgm_*_iter_next` when iteration is exhausted.
   */
  END_OF_ITER = 9,
} tgm_TgmError;

/**
 * Opaque handle for iterating over messages in a byte buffer.
 *
 * The caller's buffer must remain valid for the lifetime of this iterator.
 */
typedef struct tgm_TgmBufferIter tgm_TgmBufferIter;

/**
 * File handle.
 */
typedef struct tgm_TgmFile tgm_TgmFile;

/**
 * Opaque handle for iterating over messages in a file.
 */
typedef struct tgm_TgmFileIter tgm_TgmFileIter;

/**
 * Decoded message: global metadata + decoded (descriptor, payload) pairs.
 */
typedef struct tgm_TgmMessage tgm_TgmMessage;

/**
 * Metadata-only handle (no decoded payloads).
 */
typedef struct tgm_TgmMetadata tgm_TgmMetadata;

/**
 * Opaque handle for iterating over objects within a single message.
 */
typedef struct tgm_TgmObjectIter tgm_TgmObjectIter;

typedef struct tgm_TgmScanResult tgm_TgmScanResult;

/**
 * An owned byte buffer returned by encode functions.
 */
typedef struct tgm_TgmBytes {
  uint8_t *data;
  uintptr_t len;
} tgm_TgmBytes;

/**
 * Scan result: array of (offset, length) pairs.
 */
typedef struct tgm_TgmScanEntry {
  uintptr_t offset;
  uintptr_t length;
} tgm_TgmScanEntry;

/**
 * Returns a pointer to the last error message, or NULL if no error.
 * The pointer is valid until the next FFI call on the same thread.
 */
const char *tgm_last_error(void);

/**
 * Free a byte buffer returned by `tgm_encode`.
 */
void tgm_bytes_free(struct tgm_TgmBytes buf);

/**
 * Encode a Tensogram message from JSON metadata and raw data slices.
 *
 * `metadata_json`: null-terminated UTF-8 JSON string. Must contain:
 *   - `"version"` (integer)
 *   - `"descriptors"` (array of per-object descriptor objects)
 *   - optional extra keys (e.g. `"mars"`) at the top level
 *
 * `data_ptrs` / `data_lens`: arrays of length `num_objects`, raw bytes per object.
 *
 * `hash_algo`: null-terminated string ("xxh3") or NULL for no hash.
 *
 * On success returns `TgmError::Ok` and fills `out` with the encoded bytes.
 * The caller must free `out` with `tgm_bytes_free`.
 */
enum tgm_TgmError tgm_encode(const char *metadata_json,
                             const uint8_t *const *data_ptrs,
                             const uintptr_t *data_lens,
                             uintptr_t num_objects,
                             const char *hash_algo,
                             struct tgm_TgmBytes *out);

/**
 * Decode a complete message (global metadata + all object payloads).
 *
 * `buf` / `buf_len`: the wire-format message bytes.
 * `verify_hash`: if non-zero, verify payload hashes during decode.
 *
 * On success, fills `out` with a `TgmMessage` handle.
 * Free with `tgm_message_free`.
 */
enum tgm_TgmError tgm_decode(const uint8_t *buf,
                             uintptr_t buf_len,
                             int32_t verify_hash,
                             struct tgm_TgmMessage **out);

/**
 * Decode only the global metadata (no payload bytes are read).
 */
enum tgm_TgmError tgm_decode_metadata(const uint8_t *buf,
                                      uintptr_t buf_len,
                                      struct tgm_TgmMetadata **out);

/**
 * Decode a single object by index.
 *
 * On success, fills `out` with a `TgmMessage` handle containing exactly
 * one object (at index 0). The global metadata covers the whole message.
 */
enum tgm_TgmError tgm_decode_object(const uint8_t *buf,
                                    uintptr_t buf_len,
                                    uintptr_t index,
                                    int32_t verify_hash,
                                    struct tgm_TgmMessage **out);

/**
 * Decode a partial range from an uncompressed object.
 *
 * `ranges_offsets` / `ranges_counts`: parallel arrays of (element_offset, element_count).
 * `num_ranges`: length of both arrays.
 *
 * On success, fills `out` with a `TgmBytes` buffer of the extracted bytes.
 */
enum tgm_TgmError tgm_decode_range(const uint8_t *buf,
                                   uintptr_t buf_len,
                                   uintptr_t object_index,
                                   const uint64_t *ranges_offsets,
                                   const uint64_t *ranges_counts,
                                   uintptr_t num_ranges,
                                   int32_t verify_hash,
                                   struct tgm_TgmBytes *out);

/**
 * Scan a buffer for message boundaries.
 *
 * Returns a `TgmScanResult` handle. Access entries with `tgm_scan_count`
 * and `tgm_scan_entry`. Free with `tgm_scan_free`.
 */
enum tgm_TgmError tgm_scan(const uint8_t *buf, uintptr_t buf_len, struct tgm_TgmScanResult **out);

uintptr_t tgm_scan_count(const struct tgm_TgmScanResult *result);

struct tgm_TgmScanEntry tgm_scan_entry(const struct tgm_TgmScanResult *result, uintptr_t index);

void tgm_scan_free(struct tgm_TgmScanResult *result);

uint64_t tgm_message_version(const struct tgm_TgmMessage *msg);

/**
 * Returns the number of decoded objects in this message handle.
 * For `tgm_decode` this equals the total object count; for
 * `tgm_decode_object` this is always 1.
 */
uintptr_t tgm_message_num_objects(const struct tgm_TgmMessage *msg);

/**
 * Returns the number of decoded payload buffers.
 * Equivalent to `tgm_message_num_objects` — kept for ABI compatibility.
 */
uintptr_t tgm_message_num_decoded(const struct tgm_TgmMessage *msg);

uint64_t tgm_object_ndim(const struct tgm_TgmMessage *msg, uintptr_t index);

/**
 * Returns a pointer to the shape array. Length is `tgm_object_ndim()`.
 * The pointer is valid until the message is freed.
 */
const uint64_t *tgm_object_shape(const struct tgm_TgmMessage *msg, uintptr_t index);

/**
 * Returns a pointer to the strides array. Length is `tgm_object_ndim()`.
 */
const uint64_t *tgm_object_strides(const struct tgm_TgmMessage *msg, uintptr_t index);

/**
 * Returns the dtype as a null-terminated string (e.g. "float32").
 * The pointer is valid until the message is freed.
 */
const char *tgm_object_dtype(const struct tgm_TgmMessage *msg, uintptr_t index);

/**
 * Returns a pointer to the decoded payload bytes for a decoded object.
 * `decoded_index` is the index into the decoded objects array (0 for the
 * first decoded object, regardless of the original object index).
 * `out_len` receives the byte length.
 */
const uint8_t *tgm_object_data(const struct tgm_TgmMessage *msg,
                               uintptr_t decoded_index,
                               uintptr_t *out_len);

/**
 * Returns the encoding string for a data object descriptor (e.g. "none", "simple_packing").
 */
const char *tgm_payload_encoding(const struct tgm_TgmMessage *msg, uintptr_t index);

/**
 * Returns 1 if the object descriptor has a hash, 0 otherwise.
 */
int32_t tgm_payload_has_hash(const struct tgm_TgmMessage *msg, uintptr_t index);

void tgm_message_free(struct tgm_TgmMessage *msg);

uint64_t tgm_metadata_version(const struct tgm_TgmMetadata *meta);

/**
 * Returns the number of objects described in the global metadata.
 *
 * In wire format v2, `GlobalMetadata` does not embed per-object descriptors,
 * so this function always returns 0. Use `tgm_message_num_objects` on a
 * decoded `TgmMessage` to get the actual object count.
 */
uintptr_t tgm_metadata_num_objects(const struct tgm_TgmMetadata *meta);

/**
 * Look up a string value by dot-notation key (e.g. "mars.class").
 * Returns NULL if the key is not found or is not a string.
 * The pointer is valid until the metadata handle is freed.
 */
const char *tgm_metadata_get_string(const struct tgm_TgmMetadata *meta, const char *key);

/**
 * Look up an integer value by dot-notation key.
 * Returns `default_val` if the key is not found or is not an integer.
 */
int64_t tgm_metadata_get_int(const struct tgm_TgmMetadata *meta,
                             const char *key,
                             int64_t default_val);

/**
 * Look up a float value by dot-notation key.
 */
double tgm_metadata_get_float(const struct tgm_TgmMetadata *meta,
                              const char *key,
                              double default_val);

void tgm_metadata_free(struct tgm_TgmMetadata *meta);

enum tgm_TgmError tgm_file_open(const char *path, struct tgm_TgmFile **out);

enum tgm_TgmError tgm_file_create(const char *path, struct tgm_TgmFile **out);

enum tgm_TgmError tgm_file_message_count(struct tgm_TgmFile *file, uintptr_t *out_count);

/**
 * Decode message at `index` from the file.
 * On success fills `out` with a `TgmMessage` handle.
 */
enum tgm_TgmError tgm_file_decode_message(struct tgm_TgmFile *file,
                                          uintptr_t index,
                                          int32_t verify_hash,
                                          struct tgm_TgmMessage **out);

/**
 * Read raw message bytes at `index`.
 * On success fills `out` with a `TgmBytes` buffer.
 */
enum tgm_TgmError tgm_file_read_message(struct tgm_TgmFile *file,
                                        uintptr_t index,
                                        struct tgm_TgmBytes *out);

/**
 * Append raw message bytes to the file.
 */
enum tgm_TgmError tgm_file_append_raw(struct tgm_TgmFile *file,
                                      const uint8_t *buf,
                                      uintptr_t buf_len);

void tgm_file_close(struct tgm_TgmFile *file);

/**
 * Compute simple_packing parameters for a set of f64 values.
 *
 * Returns TgmError::Ok on success, filling the out-params.
 * Returns Encoding error if data contains NaN.
 */
enum tgm_TgmError tgm_simple_packing_compute_params(const double *values,
                                                    uintptr_t num_values,
                                                    uint32_t bits_per_value,
                                                    int32_t decimal_scale_factor,
                                                    double *out_reference_value,
                                                    int32_t *out_binary_scale_factor);

/**
 * Create a buffer message iterator.
 *
 * Scans `buf` once and stores message boundaries. The buffer must remain
 * valid and unmodified until `tgm_buffer_iter_free` is called.
 */
enum tgm_TgmError tgm_buffer_iter_create(const uint8_t *buf,
                                         uintptr_t buf_len,
                                         struct tgm_TgmBufferIter **out);

/**
 * Return the total number of messages in the buffer iterator.
 */
uintptr_t tgm_buffer_iter_count(const struct tgm_TgmBufferIter *iter);

/**
 * Advance the buffer iterator. On success, sets `out_buf` and `out_len` to
 * the next message slice (borrowed from the original buffer).
 *
 * Returns `TgmError::Ok` if a message is available, `TgmError::EndOfIter`
 * when iteration is exhausted.
 */
enum tgm_TgmError tgm_buffer_iter_next(struct tgm_TgmBufferIter *iter,
                                       const uint8_t **out_buf,
                                       uintptr_t *out_len);

void tgm_buffer_iter_free(struct tgm_TgmBufferIter *iter);

/**
 * Create a file message iterator from an open TgmFile.
 *
 * Scans the file to locate message boundaries. The file handle remains
 * usable after this call.
 */
enum tgm_TgmError tgm_file_iter_create(struct tgm_TgmFile *file, struct tgm_TgmFileIter **out);

/**
 * Advance the file iterator. On success, fills `out` with a `TgmBytes`
 * buffer containing the raw message bytes (caller owns, free with
 * `tgm_bytes_free`).
 *
 * Returns `TgmError::Ok` when a message is available, `TgmError::EndOfIter`
 * when iteration is exhausted.
 */
enum tgm_TgmError tgm_file_iter_next(struct tgm_TgmFileIter *iter, struct tgm_TgmBytes *out);

void tgm_file_iter_free(struct tgm_TgmFileIter *iter);

/**
 * Create an object iterator from raw message bytes.
 *
 * Parses metadata once, then decodes each object on demand when
 * `tgm_object_iter_next` is called.
 */
enum tgm_TgmError tgm_object_iter_create(const uint8_t *buf,
                                         uintptr_t buf_len,
                                         int32_t verify_hash,
                                         struct tgm_TgmObjectIter **out);

/**
 * Advance the object iterator. On success, fills `out` with a `TgmMessage`
 * handle containing exactly one decoded object (the next in sequence).
 *
 * Returns `TgmError::Ok` when an object is available, `TgmError::EndOfIter`
 * when iteration is exhausted. Free each yielded `TgmMessage` with
 * `tgm_message_free`.
 */
enum tgm_TgmError tgm_object_iter_next(struct tgm_TgmObjectIter *iter, struct tgm_TgmMessage **out);

void tgm_object_iter_free(struct tgm_TgmObjectIter *iter);

#endif  /* TENSOGRAM_H */
