/* Tensogram C API — generated by cbindgen. Do not edit. */

#ifndef TENSOGRAM_H
#define TENSOGRAM_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef enum tgm_TgmError {
  OK = 0,
  FRAMING = 1,
  METADATA = 2,
  ENCODING = 3,
  COMPRESSION = 4,
  OBJECT = 5,
  IO = 6,
  HASH_MISMATCH = 7,
  INVALID_ARG = 8,
} tgm_TgmError;

/**
 * File handle.
 */
typedef struct tgm_TgmFile tgm_TgmFile;

/**
 * Decoded message: metadata + decoded object payloads.
 */
typedef struct tgm_TgmMessage tgm_TgmMessage;

/**
 * Metadata-only handle (no decoded payloads).
 */
typedef struct tgm_TgmMetadata tgm_TgmMetadata;

typedef struct tgm_TgmScanResult tgm_TgmScanResult;

/**
 * An owned byte buffer returned by encode functions.
 */
typedef struct tgm_TgmBytes {
  uint8_t *data;
  uintptr_t len;
} tgm_TgmBytes;

/**
 * Scan result: array of (offset, length) pairs.
 */
typedef struct tgm_TgmScanEntry {
  uintptr_t offset;
  uintptr_t length;
} tgm_TgmScanEntry;

/**
 * Returns a pointer to the last error message, or NULL if no error.
 * The pointer is valid until the next FFI call on the same thread.
 */
const char *tgm_last_error(void);

/**
 * Free a byte buffer returned by `tgm_encode`.
 */
void tgm_bytes_free(struct tgm_TgmBytes buf);

/**
 * Encode a Tensogram message from JSON metadata and raw data slices.
 *
 * `metadata_json`: null-terminated UTF-8 JSON string describing the message.
 * `data_ptrs` / `data_lens`: arrays of length `num_objects`, raw bytes per object.
 * `hash_algo`: null-terminated string ("xxh3", "sha1", "md5") or NULL for no hash.
 *
 * On success returns `TgmError::Ok` and fills `out` with the encoded bytes.
 * The caller must free `out` with `tgm_bytes_free`.
 */
enum tgm_TgmError tgm_encode(const char *metadata_json,
                             const uint8_t *const *data_ptrs,
                             const uintptr_t *data_lens,
                             uintptr_t num_objects,
                             const char *hash_algo,
                             struct tgm_TgmBytes *out);

/**
 * Decode a complete message (metadata + all object payloads).
 *
 * `buf` / `buf_len`: the wire-format message bytes.
 * `verify_hash`: if non-zero, verify payload hashes during decode.
 *
 * On success, fills `out` with a `TgmMessage` handle.
 * Free with `tgm_message_free`.
 */
enum tgm_TgmError tgm_decode(const uint8_t *buf,
                             uintptr_t buf_len,
                             int32_t verify_hash,
                             struct tgm_TgmMessage **out);

/**
 * Decode only the metadata (no payload bytes are read).
 */
enum tgm_TgmError tgm_decode_metadata(const uint8_t *buf,
                                      uintptr_t buf_len,
                                      struct tgm_TgmMetadata **out);

/**
 * Decode a single object by index.
 *
 * On success, fills `out` with a `TgmMessage` handle containing exactly
 * one object (at index 0). The metadata covers the whole message.
 */
enum tgm_TgmError tgm_decode_object(const uint8_t *buf,
                                    uintptr_t buf_len,
                                    uintptr_t index,
                                    int32_t verify_hash,
                                    struct tgm_TgmMessage **out);

/**
 * Decode a partial range from an uncompressed object.
 *
 * `ranges_offsets` / `ranges_counts`: parallel arrays of (element_offset, element_count).
 * `num_ranges`: length of both arrays.
 *
 * On success, fills `out` with a `TgmBytes` buffer of the extracted bytes.
 */
enum tgm_TgmError tgm_decode_range(const uint8_t *buf,
                                   uintptr_t buf_len,
                                   uintptr_t object_index,
                                   const uint64_t *ranges_offsets,
                                   const uint64_t *ranges_counts,
                                   uintptr_t num_ranges,
                                   int32_t verify_hash,
                                   struct tgm_TgmBytes *out);

/**
 * Scan a buffer for message boundaries.
 *
 * Returns a `TgmScanResult` handle. Access entries with `tgm_scan_count`
 * and `tgm_scan_entry`. Free with `tgm_scan_free`.
 */
enum tgm_TgmError tgm_scan(const uint8_t *buf, uintptr_t buf_len, struct tgm_TgmScanResult **out);

uintptr_t tgm_scan_count(const struct tgm_TgmScanResult *result);

struct tgm_TgmScanEntry tgm_scan_entry(const struct tgm_TgmScanResult *result, uintptr_t index);

void tgm_scan_free(struct tgm_TgmScanResult *result);

uint64_t tgm_message_version(const struct tgm_TgmMessage *msg);

uintptr_t tgm_message_num_objects(const struct tgm_TgmMessage *msg);

/**
 * Returns the number of decoded payload buffers.
 * For tgm_decode this equals num_objects; for tgm_decode_object this is 1.
 */
uintptr_t tgm_message_num_decoded(const struct tgm_TgmMessage *msg);

uint64_t tgm_object_ndim(const struct tgm_TgmMessage *msg, uintptr_t index);

/**
 * Returns a pointer to the shape array. Length is `tgm_object_ndim()`.
 * The pointer is valid until the message is freed.
 */
const uint64_t *tgm_object_shape(const struct tgm_TgmMessage *msg, uintptr_t index);

/**
 * Returns a pointer to the strides array. Length is `tgm_object_ndim()`.
 */
const uint64_t *tgm_object_strides(const struct tgm_TgmMessage *msg, uintptr_t index);

/**
 * Returns the dtype as a null-terminated string (e.g. "float32").
 * The pointer is valid until the message is freed.
 */
const char *tgm_object_dtype(const struct tgm_TgmMessage *msg, uintptr_t index);

/**
 * Returns a pointer to the decoded payload bytes for a decoded object.
 * `decoded_index` is the index into the decoded objects array (0 for the
 * first decoded object, regardless of the original object index).
 * `out_len` receives the byte length.
 */
const uint8_t *tgm_object_data(const struct tgm_TgmMessage *msg,
                               uintptr_t decoded_index,
                               uintptr_t *out_len);

/**
 * Returns the encoding string for a payload descriptor (e.g. "none", "simple_packing").
 */
const char *tgm_payload_encoding(const struct tgm_TgmMessage *msg, uintptr_t index);

/**
 * Returns 1 if the payload has a hash, 0 otherwise.
 */
int32_t tgm_payload_has_hash(const struct tgm_TgmMessage *msg, uintptr_t index);

void tgm_message_free(struct tgm_TgmMessage *msg);

uint64_t tgm_metadata_version(const struct tgm_TgmMetadata *meta);

uintptr_t tgm_metadata_num_objects(const struct tgm_TgmMetadata *meta);

/**
 * Look up a string value by dot-notation key (e.g. "mars.class").
 * Returns NULL if the key is not found or is not a string.
 * The pointer is valid until the metadata handle is freed.
 */
const char *tgm_metadata_get_string(const struct tgm_TgmMetadata *meta, const char *key);

/**
 * Look up an integer value by dot-notation key.
 * Returns `default_val` if the key is not found or is not an integer.
 */
int64_t tgm_metadata_get_int(const struct tgm_TgmMetadata *meta,
                             const char *key,
                             int64_t default_val);

/**
 * Look up a float value by dot-notation key.
 */
double tgm_metadata_get_float(const struct tgm_TgmMetadata *meta,
                              const char *key,
                              double default_val);

void tgm_metadata_free(struct tgm_TgmMetadata *meta);

enum tgm_TgmError tgm_file_open(const char *path, struct tgm_TgmFile **out);

enum tgm_TgmError tgm_file_create(const char *path, struct tgm_TgmFile **out);

enum tgm_TgmError tgm_file_message_count(struct tgm_TgmFile *file, uintptr_t *out_count);

/**
 * Decode message at `index` from the file.
 * On success fills `out` with a `TgmMessage` handle.
 */
enum tgm_TgmError tgm_file_decode_message(struct tgm_TgmFile *file,
                                          uintptr_t index,
                                          int32_t verify_hash,
                                          struct tgm_TgmMessage **out);

/**
 * Read raw message bytes at `index`.
 * On success fills `out` with a `TgmBytes` buffer.
 */
enum tgm_TgmError tgm_file_read_message(struct tgm_TgmFile *file,
                                        uintptr_t index,
                                        struct tgm_TgmBytes *out);

/**
 * Append raw message bytes to the file.
 */
enum tgm_TgmError tgm_file_append_raw(struct tgm_TgmFile *file,
                                      const uint8_t *buf,
                                      uintptr_t buf_len);

void tgm_file_close(struct tgm_TgmFile *file);

/**
 * Compute simple_packing parameters for a set of f64 values.
 *
 * Returns TgmError::Ok on success, filling the out-params.
 * Returns Encoding error if data contains NaN.
 */
enum tgm_TgmError tgm_simple_packing_compute_params(const double *values,
                                                    uintptr_t num_values,
                                                    uint32_t bits_per_value,
                                                    int32_t decimal_scale_factor,
                                                    double *out_reference_value,
                                                    int32_t *out_binary_scale_factor);

#endif  /* TENSOGRAM_H */
