/*
 * (C) Copyright 2026- ECMWF and individual contributors.
 *
 * This software is licensed under the terms of the Apache Licence Version 2.0
 * which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
 * In applying this licence, ECMWF does not waive the privileges and immunities
 * granted to it by virtue of its status as an intergovernmental organisation nor
 * does it submit to any jurisdiction.
 *
 * Tensogram C API — generated by cbindgen. Do not edit.
 */


#ifndef TENSOGRAM_H
#define TENSOGRAM_H

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Wire-format version emitted and required by this build of the
 * library.
 *
 * Mirrors [`tensogram::WIRE_VERSION`].  The value lives in the
 * tensogram **preamble** (see `plans/WIRE_FORMAT.md` §3) — never in
 * the CBOR metadata frame.  Exposed here so C / C++ callers can
 * reference it without decoding a message first.  cbindgen emits
 * this as a `#define TGM_WIRE_VERSION 3` in the generated header.
 *
 * The literal is mirrored from `tensogram::wire::WIRE_VERSION`
 * because cbindgen source-parses this crate and cannot resolve
 * cross-crate constant expressions; the [`const _: () = assert!`]
 * below keeps the two in lockstep at compile time.
 */
#define TGM_WIRE_VERSION 3

typedef enum {
  TGM_ERROR_OK = 0,
  TGM_ERROR_FRAMING = 1,
  TGM_ERROR_METADATA = 2,
  TGM_ERROR_ENCODING = 3,
  TGM_ERROR_COMPRESSION = 4,
  TGM_ERROR_OBJECT = 5,
  TGM_ERROR_IO = 6,
  TGM_ERROR_HASH_MISMATCH = 7,
  TGM_ERROR_INVALID_ARG = 8,
  /**
   * Returned by `tgm_*_iter_next` when iteration is exhausted.
   */
  TGM_ERROR_END_OF_ITER = 9,
  TGM_ERROR_REMOTE = 10,
  /**
   * Decode-time hash verification was requested but the frame's
   * `HASH_PRESENT` flag is clear (see `plans/WIRE_FORMAT.md` §2.5).
   * Distinct from `HashMismatch` — the digest didn't disagree;
   * there was no digest recorded to compare against.  The
   * offending object index is available through
   * `tgm_last_error_object_index()` for the duration of the
   * thread-local error.
   */
  TGM_ERROR_MISSING_HASH = 11,
  /**
   * Async task exceeded its deadline; the underlying tokio future
   * was dropped at the next yield point.
   */
  TGM_ERROR_TIMEOUT = 12,
  /**
   * Async task observed its cancellation token fire before the
   * future resolved.
   */
  TGM_ERROR_CANCELLED = 13,
} tgm_error;

/**
 * Status returned by `tgm_async_streaming_encoder_try_object_count`.
 *
 * Distinguishes the three states the previous overloaded sentinel
 * (`usize::MAX`) collapsed: invalid handle, busy with another in-flight
 * FFI call, encoder already finished, and a valid count.
 */
typedef enum {
  /**
   * `*out_count` is valid.
   */
  TGM_OBJECT_COUNT_STATUS_OK = 0,
  /**
   * `enc` was NULL.
   */
  TGM_OBJECT_COUNT_STATUS_NULL_HANDLE = 1,
  /**
   * The encoder is currently locked by another in-flight async
   * operation (write/finish).  Try again after that operation
   * completes.
   */
  TGM_OBJECT_COUNT_STATUS_BUSY = 2,
  /**
   * `tgm_async_streaming_encoder_finish` has already consumed the
   * encoder; subsequent calls to other methods will error too.
   */
  TGM_OBJECT_COUNT_STATUS_FINISHED = 3,
} TgmObjectCountStatus;

/**
 * Async file handle backed by `Arc<TensogramFile>` so the same handle
 * is safely shareable across multiple in-flight tasks.
 */
typedef struct tgm_async_file_t tgm_async_file_t;

/**
 * Opaque async streaming-encoder handle.  Internally wraps an
 * `AsyncStreamingEncoder<tokio::fs::File>` behind a `tokio::sync::Mutex`
 * so concurrent `write_object` calls are serialised (the underlying
 * AsyncWrite is naturally serial — concurrent calls would interleave
 * frame bytes).
 */
typedef struct tgm_async_streaming_encoder_t tgm_async_streaming_encoder_t;

/**
 * Opaque task handle exposed to C as `tgm_async_task_t*`.
 */
typedef struct tgm_async_task_t tgm_async_task_t;

/**
 * Opaque handle for iterating over messages in a byte buffer.
 *
 * The caller's buffer must remain valid for the lifetime of this iterator.
 */
typedef struct tgm_buffer_iter_t tgm_buffer_iter_t;

/**
 * Opaque cancellation-token handle exposed to C as
 * `tgm_cancellation_token_t*`.
 */
typedef struct tgm_cancellation_token_t tgm_cancellation_token_t;

/**
 * File handle.
 */
typedef struct tgm_file_t tgm_file_t;

/**
 * Opaque handle for iterating over messages in a file.
 */
typedef struct tgm_file_iter_t tgm_file_iter_t;

/**
 * Decoded message: global metadata + decoded (descriptor, payload) pairs.
 */
typedef struct tgm_message_t tgm_message_t;

/**
 * Metadata-only handle (no decoded payloads).
 */
typedef struct tgm_metadata_t tgm_metadata_t;

/**
 * Opaque handle for iterating over objects within a single message.
 */
typedef struct tgm_object_iter_t tgm_object_iter_t;

/**
 * Opaque handle for scan results.
 */
typedef struct tgm_scan_result_t tgm_scan_result_t;

/**
 * Opaque handle for a streaming encoder that writes data objects progressively.
 */
typedef struct tgm_streaming_encoder_t tgm_streaming_encoder_t;

/**
 * An owned byte buffer returned by encode functions.
 */
typedef struct {
  uint8_t *data;
  size_t len;
} tgm_bytes_t;

/**
 * Mask-companion options for encode entry points (see
 * `plans/WIRE_FORMAT.md` §6.5 and `docs/src/guide/nan-inf-handling.md`).
 * Pass a pointer to this struct to opt into NaN / ±Inf substitution
 * with bitmask companion frames.
 *
 * Each `*_mask_method` string is one of `"none"`, `"rle"`,
 * `"roaring"`, `"lz4"`, `"zstd"`, or `"blosc2"`; pass `NULL` to use
 * the library default (`"roaring"`).  Unknown names cause the
 * owning `tgm_*_with_options` call to return
 * [`TgmError::InvalidArg`] with a clear message via
 * [`tgm_last_error`].
 *
 * `small_mask_threshold_bytes` is the byte-count below which mask
 * blobs are written as `"none"` regardless of the requested method
 * (auto-fallback).  Pass `0` to disable the fallback.  Negative
 * values use the library default (128).
 */
typedef struct {
  bool allow_nan;
  bool allow_inf;
  const char *nan_mask_method;
  const char *pos_inf_mask_method;
  const char *neg_inf_mask_method;
  ptrdiff_t small_mask_threshold_bytes;
} TgmEncodeMaskOptions;

/**
 * Decode-side companion to [`TgmEncodeMaskOptions`].  Pass a pointer
 * to opt out of canonical NaN / Inf restoration.  Pass `NULL` for
 * the default `restore_non_finite = true`.
 */
typedef struct {
  bool restore_non_finite;
} TgmDecodeMaskOptions;

/**
 * Scan result: array of (offset, length) pairs.
 */
typedef struct {
  size_t offset;
  size_t length;
} tgm_scan_entry_t;

/**
 * Returns a pointer to the last error message, or NULL if no error.
 * The pointer is valid until the next FFI call on the same thread.
 */
const char *tgm_last_error(void);

/**
 * Free a byte buffer returned by `tgm_encode`.
 */
void tgm_bytes_free(tgm_bytes_t buf);

/**
 * Encode a Tensogram message from JSON metadata and raw data slices.
 *
 * `metadata_json`: null-terminated UTF-8 JSON string with:
 *   - `"descriptors"` (array of per-object descriptor objects, required)
 *   - `"base"` (array of per-object application metadata, optional)
 *   - any other top-level keys (e.g. `"mars"`) flow into `_extra_`
 *
 * A legacy `"version"` top-level field is tolerated and silently
 * discarded — the wire-format version lives in the preamble, not in
 * the CBOR metadata frame (see `plans/WIRE_FORMAT.md` §§3, 6.1).
 *
 * `data_ptrs` / `data_lens`: arrays of length `num_objects`, raw bytes per object.
 *
 * `hash_algo`: null-terminated string ("xxh3") or NULL for no hash.
 *
 * On success returns `TgmError::Ok` and fills `out` with the encoded bytes.
 * The caller must free `out` with `tgm_bytes_free`.
 *
 * 0.17+: encode rejects non-finite values (NaN / ±Inf) by default.
 * Use [`tgm_encode_with_options`] with a
 * [`TgmEncodeMaskOptions`] pointer (`allow_nan` / `allow_inf`) to
 * opt into NaN / Inf substitution with bitmask companion frames;
 * this entry point always uses the default reject policy.
 */
tgm_error tgm_encode(const char *metadata_json,
                     const uint8_t *const *data_ptrs,
                     const size_t *data_lens,
                     size_t num_objects,
                     const char *hash_algo,
                     uint32_t threads,
                     tgm_bytes_t *out);

/**
 * Encode with explicit NaN / Inf mask-companion options.
 *
 * Like [`tgm_encode`] but takes a [`TgmEncodeMaskOptions`] pointer
 * (nullable — `NULL` behaves like [`tgm_encode`]'s default reject
 * policy).  All other arguments are identical.
 */
tgm_error tgm_encode_with_options(const char *metadata_json,
                                  const uint8_t *const *data_ptrs,
                                  const size_t *data_lens,
                                  size_t num_objects,
                                  const char *hash_algo,
                                  uint32_t threads,
                                  const TgmEncodeMaskOptions *mask_options,
                                  tgm_bytes_t *out);

/**
 * Decode with explicit NaN / Inf restoration options.
 *
 * Like [`tgm_decode`] but takes a [`TgmDecodeMaskOptions`] pointer
 * (nullable — `NULL` behaves like [`tgm_decode`]'s default
 * `restore_non_finite = true`).
 */
tgm_error tgm_decode_with_options(const uint8_t *buf,
                                  size_t buf_len,
                                  int32_t native_byte_order,
                                  uint32_t threads,
                                  int32_t verify_hash,
                                  const TgmDecodeMaskOptions *mask_options,
                                  tgm_message_t **out);

/**
 * Streaming-encoder constructor with NaN / Inf mask-companion options.
 *
 * Like [`tgm_streaming_encoder_create`] but takes a
 * [`TgmEncodeMaskOptions`] pointer.  `NULL` behaves like the default
 * reject policy.
 */
tgm_error tgm_streaming_encoder_create_with_options(const char *path,
                                                    const char *metadata_json,
                                                    const char *hash_algo,
                                                    uint32_t threads,
                                                    const TgmEncodeMaskOptions *mask_options,
                                                    tgm_streaming_encoder_t **out);

/**
 * Append a message to a file with explicit NaN / Inf mask-companion options.
 *
 * Like [`tgm_file_append`] but takes a [`TgmEncodeMaskOptions`]
 * pointer.  `NULL` behaves like the default reject policy.
 */
tgm_error tgm_file_append_with_options(tgm_file_t *file,
                                       const char *metadata_json,
                                       const uint8_t *const *data_ptrs,
                                       const size_t *data_lens,
                                       size_t num_objects,
                                       const char *hash_algo,
                                       uint32_t threads,
                                       const TgmEncodeMaskOptions *mask_options);

/**
 * Encode a Tensogram message from JSON metadata and pre-encoded payload bytes.
 *
 * Like `tgm_encode`, but each `data_ptrs[i]` slice must already be encoded
 * according to the matching descriptor's `encoding` / `filter` / `compression`
 * pipeline. The library does not run the encoding pipeline again — it writes
 * the caller-provided bytes directly into the wire-format payload after
 * validating that the descriptor's pipeline configuration is well-formed.
 *
 * `metadata_json`: same flat JSON schema as `tgm_encode` (`version`,
 *   `descriptors`, optional `base`, plus arbitrary extra top-level keys).
 *
 * `data_ptrs` / `data_lens`: arrays of length `num_objects` pointing at
 *   already-encoded payload bytes (one entry per descriptor).
 *
 * `hash_algo`: null-terminated string ("xxh3") or NULL for no hash. The
 *   library always recomputes the hash over the caller's bytes; any
 *   `hash` field embedded in the descriptor JSON is ignored and overwritten.
 *
 * Notes for compression-aware decoding:
 * - For `szip` compression, callers SHOULD include `szip_block_offsets`
 *   (a list of bit offsets into the compressed payload) inside the
 *   matching descriptor's params so that `tgm_decode_range` can locate
 *   szip block boundaries without rescanning the compressed stream.
 * - Other pipeline params (e.g. `simple_packing` reference value, scale
 *   factors) must also be present in the descriptor — they are not
 *   inferred from the bytes.
 *
 * On success returns `TgmError::Ok` and fills `out` with the encoded message.
 * The caller must free `out` with `tgm_bytes_free`.
 */
tgm_error tgm_encode_pre_encoded(const char *metadata_json,
                                 const uint8_t *const *data_ptrs,
                                 const size_t *data_lens,
                                 size_t num_objects,
                                 const char *hash_algo,
                                 uint32_t threads,
                                 tgm_bytes_t *out);

/**
 * Decode a complete message (global metadata + all object payloads).
 *
 * `buf` / `buf_len`: the wire-format message bytes.
 *
 * On success, fills `out` with a `TgmMessage` handle.
 * Free with `tgm_message_free`.
 */
tgm_error tgm_decode(const uint8_t *buf,
                     size_t buf_len,
                     int32_t native_byte_order,
                     uint32_t threads,
                     int32_t verify_hash,
                     tgm_message_t **out);

/**
 * Decode only the global metadata (no payload bytes are read).
 */
tgm_error tgm_decode_metadata(const uint8_t *buf, size_t buf_len, tgm_metadata_t **out);

/**
 * Decode a single object by index.
 *
 * On success, fills `out` with a `TgmMessage` handle containing exactly
 * one object (at index 0). The global metadata covers the whole message.
 */
tgm_error tgm_decode_object(const uint8_t *buf,
                            size_t buf_len,
                            size_t index,
                            int32_t native_byte_order,
                            uint32_t threads,
                            int32_t verify_hash,
                            tgm_message_t **out);

/**
 * Decode partial ranges from a data object.
 *
 * `ranges_offsets` / `ranges_counts`: parallel arrays of (element_offset, element_count).
 * `num_ranges`: length of both arrays.
 * `join`: when non-zero, concatenate all ranges into a single buffer in `out[0]`
 *         and set `*out_count = 1`.  When zero (split mode), write one `TgmBytes`
 *         per range into `out[0..num_ranges]` and set `*out_count = num_ranges`.
 *         The caller must pre-allocate `out` with at least `num_ranges` entries
 *         when `join == 0`, or 1 entry when `join != 0`.
 * `out_count`: filled with the number of buffers written to `out`.
 *
 * Free each returned buffer with `tgm_bytes_free`.
 */
tgm_error tgm_decode_range(const uint8_t *buf,
                           size_t buf_len,
                           size_t object_index,
                           const uint64_t *ranges_offsets,
                           const uint64_t *ranges_counts,
                           size_t num_ranges,
                           int32_t native_byte_order,
                           uint32_t threads,
                           int32_t join,
                           tgm_bytes_t *out,
                           size_t *out_count);

/**
 * Scan a buffer for message boundaries.
 *
 * Returns a `TgmScanResult` handle. Access entries with `tgm_scan_count`
 * and `tgm_scan_entry`. Free with `tgm_scan_free`.
 */
tgm_error tgm_scan(const uint8_t *buf, size_t buf_len, tgm_scan_result_t **out);

/**
 * Returns the number of messages found by `tgm_scan`.
 */
size_t tgm_scan_count(const tgm_scan_result_t *result);

tgm_scan_entry_t tgm_scan_entry(const tgm_scan_result_t *result, size_t index);

/**
 * Free a scan result handle.
 */
void tgm_scan_free(tgm_scan_result_t *result);

/**
 * Returns the wire format version the decoder read from the preamble.
 *
 * v3 decoders reject any other version at preamble parse time, so
 * this always returns [`tensogram::WIRE_VERSION`] for any live
 * `TgmMessage` handle.  The CBOR metadata frame carries no
 * `version` key of its own (see `plans/WIRE_FORMAT.md` §6.1).
 * Returns `0` for a null handle.
 */
uint64_t tgm_message_version(const tgm_message_t *msg);

/**
 * Returns the number of decoded objects in this message handle.
 * For `tgm_decode` this equals the total object count; for
 * `tgm_decode_object` this is always 1.
 */
size_t tgm_message_num_objects(const tgm_message_t *msg);

/**
 * Returns the number of decoded payload buffers.
 * Equivalent to `tgm_message_num_objects` — kept for ABI compatibility.
 */
size_t tgm_message_num_decoded(const tgm_message_t *msg);

/**
 * Returns the number of dimensions for object at index.
 */
uint64_t tgm_object_ndim(const tgm_message_t *msg, size_t index);

/**
 * Returns a pointer to the shape array. Length is `tgm_object_ndim()`.
 * The pointer is valid until the message is freed.
 */
const uint64_t *tgm_object_shape(const tgm_message_t *msg, size_t index);

/**
 * Returns a pointer to the strides array. Length is `tgm_object_ndim()`.
 */
const uint64_t *tgm_object_strides(const tgm_message_t *msg, size_t index);

/**
 * Returns the dtype as a null-terminated string (e.g. "float32").
 * The pointer is valid until the message is freed.
 */
const char *tgm_object_dtype(const tgm_message_t *msg, size_t index);

/**
 * Returns a pointer to the decoded payload bytes for a decoded object.
 * `decoded_index` is the index into the decoded objects array (0 for the
 * first decoded object, regardless of the original object index).
 * `out_len` receives the byte length.
 */
const uint8_t *tgm_object_data(const tgm_message_t *msg, size_t decoded_index, size_t *out_len);

/**
 * Returns the encoding string for a data object descriptor (e.g. "none", "simple_packing").
 * The pointer is valid until the message is freed.
 */
const char *tgm_payload_encoding(const tgm_message_t *msg, size_t index);

/**
 * Returns 1 if the i-th data object has a populated inline hash
 * slot, 0 otherwise.
 *
 * In v3 the per-object hash lives in the frame footer's inline
 * slot (see `plans/WIRE_FORMAT.md` §2.4) rather than the CBOR
 * descriptor.  v3 hashing is a message-wide toggle: either every
 * frame's slot is populated (preamble flag `HASHES_PRESENT = 1`)
 * or every slot is zero (`HASHES_PRESENT = 0`).  This accessor
 * returns 1 when the i-th slot holds a non-zero xxh3-64 digest,
 * and 0 when the slot is zero (most commonly the whole-message
 * `HASHES_PRESENT = 0` case) or when the index is out of range.
 *
 * A zero slot on a message that advertises `HASHES_PRESENT = 1`
 * is a structural anomaly (tamper or writer bug) — surface via
 * `tgm_validate` at the `checksum` / `integrity` level, which
 * will report a HashMismatch against the body's recomputed digest.
 *
 * The matching hex digest is available via
 * [`tgm_object_hash_value`]; the algorithm tag (always
 * `"xxh3"` in v3) via [`tgm_object_hash_type`].
 */
int32_t tgm_payload_has_hash(const tgm_message_t *msg, size_t index);

/**
 * Extract a metadata handle from a decoded message.
 * The metadata handle is independent — free it separately with `tgm_metadata_free`.
 */
tgm_error tgm_message_metadata(const tgm_message_t *msg, tgm_metadata_t **out);

/**
 * Returns the object type string (e.g. "ndarray"). Valid until message freed.
 */
const char *tgm_object_type(const tgm_message_t *msg, size_t index);

/**
 * Returns the byte order string ("big" or "little"). Valid until message freed.
 */
const char *tgm_object_byte_order(const tgm_message_t *msg, size_t index);

/**
 * Returns the filter string (e.g. "none", "shuffle"). Valid until message freed.
 */
const char *tgm_object_filter(const tgm_message_t *msg, size_t index);

/**
 * Returns the compression string (e.g. "none", "zstd"). Valid until message freed.
 */
const char *tgm_object_compression(const tgm_message_t *msg, size_t index);

/**
 * Returns the hash type string ("xxh3") or NULL if no hash. Valid until message freed.
 */
const char *tgm_object_hash_type(const tgm_message_t *msg, size_t index);

/**
 * Returns the hash value hex string or NULL if no hash. Valid until message freed.
 */
const char *tgm_object_hash_value(const tgm_message_t *msg, size_t index);

/**
 * Free a decoded message handle.
 */
void tgm_message_free(tgm_message_t *msg);

/**
 * Returns the wire format version.
 *
 * Sourced from [`tensogram::WIRE_VERSION`] since v3 decoders reject any
 * other version at preamble parse time.  The CBOR metadata frame
 * carries no `version` key of its own (see
 * `plans/WIRE_FORMAT.md` §6.1).  Returns `0` for a null handle.
 */
uint64_t tgm_metadata_version(const tgm_metadata_t *meta);

/**
 * Returns the number of objects described in the global metadata.
 *
 * Returns the length of the `base` array, which has one entry per data object.
 */
size_t tgm_metadata_num_objects(const tgm_metadata_t *meta);

/**
 * Look up a string value by dot-notation key (e.g. "mars.class").
 *
 * Text is returned as-is; integer / float / bool leaves are coerced to their
 * string form.  Returns NULL if the key is not found, the value is a container
 * (map / array), null, or bytes, or the value contains an interior NUL byte
 * (not representable as a C string).
 * The pointer is valid until the metadata handle is freed.
 */
const char *tgm_metadata_get_string(const tgm_metadata_t *meta, const char *key);

/**
 * Look up an integer value by dot-notation key.
 * Returns `default_val` if the key is not found or is not an integer.
 */
int64_t tgm_metadata_get_int(const tgm_metadata_t *meta, const char *key, int64_t default_val);

/**
 * Look up a float value by dot-notation key.  Integer leaves are widened to
 * `f64`.  Returns `default_val` if the key is not found or the value is not
 * numeric.
 */
double tgm_metadata_get_float(const tgm_metadata_t *meta, const char *key, double default_val);

/**
 * Look up a string value in object `obj_index`'s metadata by dot-notation key
 * (e.g. `"shortName"`, `"mars.class"`, `"geometry.gridType"`).
 *
 * Scoped to `base[obj_index]` only — no cross-object first-match, no `extra`
 * fallback, and `_reserved_` is skipped at the first level (use the object
 * accessors for the tensor shape/dtype).  Integer / float / bool leaves are
 * coerced to their string form.
 *
 * Returns NULL if the handle is null, `obj_index` is out of range, the key is
 * absent, the value is a container (map / array), null, or bytes, or the value
 * contains an interior NUL byte (not representable as a C string).  The pointer
 * is valid until the metadata handle is freed.
 */
const char *tgm_metadata_get_string_at(const tgm_metadata_t *meta,
                                       size_t obj_index,
                                       const char *key);

/**
 * Look up an integer value in object `obj_index`'s metadata by dot-notation
 * key.  Returns `default_val` if the handle is null, `obj_index` is out of
 * range, the key is absent, or the value is not an integer.  See
 * [`tgm_metadata_get_string_at`] for scoping rules.
 */
int64_t tgm_metadata_get_int_at(const tgm_metadata_t *meta,
                                size_t obj_index,
                                const char *key,
                                int64_t default_val);

/**
 * Look up a float value in object `obj_index`'s metadata by dot-notation key.
 * Returns `default_val` if the handle is null, `obj_index` is out of range,
 * the key is absent, or the value is not numeric.  Integer leaves are widened
 * to `f64`.  See [`tgm_metadata_get_string_at`] for scoping rules.
 */
double tgm_metadata_get_float_at(const tgm_metadata_t *meta,
                                 size_t obj_index,
                                 const char *key,
                                 double default_val);

/**
 * Serialise object `obj_index`'s full metadata (`base[obj_index]`) to a JSON
 * object string — including any `_reserved_.tensor` descriptor.
 *
 * This is the enumerate-everything companion to the typed getters: a caller
 * that does not know the key set ahead of time (e.g. a metadata viewer) can
 * display or parse the whole object without walking CBOR itself.  Returns
 * NULL for a null handle or an out-of-range `obj_index`.  The pointer is valid
 * until the metadata handle is freed.
 */
const char *tgm_metadata_object_to_json(const tgm_metadata_t *meta, size_t obj_index);

/**
 * Serialise the whole global metadata to a JSON object string, shaped
 * `{ "base": [...], "_reserved_": {...}, "_extra_": {...} }` (empty sections
 * omitted).  Returns NULL for a null handle; the pointer is valid until the
 * metadata handle is freed.
 */
const char *tgm_metadata_to_json(const tgm_metadata_t *meta);

/**
 * Free a metadata handle.
 */
void tgm_metadata_free(tgm_metadata_t *meta);

/**
 * Open an existing Tensogram file for reading.
 */
tgm_error tgm_file_open(const char *path, tgm_file_t **out);

/**
 * Create a new Tensogram file for writing.
 */
tgm_error tgm_file_create(const char *path, tgm_file_t **out);

/**
 * Count messages in the file (may trigger lazy scan).
 */
tgm_error tgm_file_message_count(tgm_file_t *file, size_t *out_count);

/**
 * Decode message at `index` from the file.
 * On success fills `out` with a `TgmMessage` handle.
 */
tgm_error tgm_file_decode_message(tgm_file_t *file,
                                  size_t index,
                                  int32_t native_byte_order,
                                  uint32_t threads,
                                  int32_t verify_hash,
                                  tgm_message_t **out);

/**
 * Read raw message bytes at `index`.
 * On success fills `out` with a `TgmBytes` buffer.
 */
tgm_error tgm_file_read_message(tgm_file_t *file, size_t index, tgm_bytes_t *out);

/**
 * Append raw message bytes to the file.
 */
tgm_error tgm_file_append_raw(tgm_file_t *file, const uint8_t *buf, size_t buf_len);

/**
 * Returns the file path as a null-terminated string.
 * The pointer is valid until the file handle is closed.
 */
const char *tgm_file_path(const tgm_file_t *file);

/**
 * Encode and append a message to the file.
 * Same JSON schema as `tgm_encode` for `metadata_json`.
 *
 * Non-finite-value rejection is on by default in 0.17+; see `tgm_encode`.
 */
tgm_error tgm_file_append(tgm_file_t *file,
                          const char *metadata_json,
                          const uint8_t *const *data_ptrs,
                          const size_t *data_lens,
                          size_t num_objects,
                          const char *hash_algo,
                          uint32_t threads);

/**
 * Close a file handle and release resources.
 */
void tgm_file_close(tgm_file_t *file);

/**
 * Compute simple_packing parameters for a set of f64 values.
 *
 * Returns TgmError::Ok on success, filling the out-params.
 * Returns Encoding error if data contains NaN.
 */
tgm_error tgm_simple_packing_compute_params(const double *values,
                                            size_t num_values,
                                            uint32_t bits_per_value,
                                            int32_t decimal_scale_factor,
                                            double *out_reference_value,
                                            int32_t *out_binary_scale_factor);

/**
 * Create a buffer message iterator.
 *
 * Scans `buf` once and stores message boundaries. The buffer must remain
 * valid and unmodified until `tgm_buffer_iter_free` is called.
 */
tgm_error tgm_buffer_iter_create(const uint8_t *buf, size_t buf_len, tgm_buffer_iter_t **out);

/**
 * Return the total number of messages in the buffer iterator.
 */
size_t tgm_buffer_iter_count(const tgm_buffer_iter_t *iter);

/**
 * Advance the buffer iterator. On success, sets `out_buf` and `out_len` to
 * the next message slice (borrowed from the original buffer).
 *
 * Returns `TgmError::Ok` if a message is available, `TgmError::EndOfIter`
 * when iteration is exhausted.
 */
tgm_error tgm_buffer_iter_next(tgm_buffer_iter_t *iter, const uint8_t **out_buf, size_t *out_len);

/**
 * Free a buffer iterator handle.
 */
void tgm_buffer_iter_free(tgm_buffer_iter_t *iter);

/**
 * Create a file message iterator from an open TgmFile.
 *
 * Scans the file to locate message boundaries. The file handle remains
 * usable after this call.
 */
tgm_error tgm_file_iter_create(tgm_file_t *file, tgm_file_iter_t **out);

/**
 * Advance the file iterator. On success, fills `out` with a `TgmBytes`
 * buffer containing the raw message bytes (caller owns, free with
 * `tgm_bytes_free`).
 *
 * Returns `TgmError::Ok` when a message is available, `TgmError::EndOfIter`
 * when iteration is exhausted.
 */
tgm_error tgm_file_iter_next(tgm_file_iter_t *iter, tgm_bytes_t *out);

/**
 * Free a file iterator handle.
 */
void tgm_file_iter_free(tgm_file_iter_t *iter);

/**
 * Create an object iterator from raw message bytes.
 *
 * Parses metadata once, then decodes each object on demand when
 * `tgm_object_iter_next` is called. The global metadata from the
 * original message is preserved in each yielded `TgmMessage`.
 */
tgm_error tgm_object_iter_create(const uint8_t *buf,
                                 size_t buf_len,
                                 int32_t native_byte_order,
                                 int32_t verify_hash,
                                 tgm_object_iter_t **out);

/**
 * Advance the object iterator. On success, fills `out` with a `TgmMessage`
 * handle containing exactly one decoded object (the next in sequence).
 *
 * Returns `TgmError::Ok` when an object is available, `TgmError::EndOfIter`
 * when iteration is exhausted. Free each yielded `TgmMessage` with
 * `tgm_message_free`.
 */
tgm_error tgm_object_iter_next(tgm_object_iter_t *iter, tgm_message_t **out);

/**
 * Free an object iterator handle.
 */
void tgm_object_iter_free(tgm_object_iter_t *iter);

/**
 * Convert an error code to a human-readable string.
 * Returns a static string (always valid, never NULL).
 *
 * Accepts a raw integer and matches by value so that invalid discriminants
 * from C callers do not trigger undefined behaviour in Rust.
 */
const char *tgm_error_string(tgm_error err);

/**
 * Compute a hash of the given data.
 * Returns `TGM_ERROR_OK` on success, fills `out` with a `tgm_bytes_t`
 * containing the hex-encoded hash string (NOT null-terminated).
 * Free with `tgm_bytes_free`.
 */
tgm_error tgm_compute_hash(const uint8_t *data,
                           size_t data_len,
                           const char *algo,
                           tgm_bytes_t *out);

/**
 * Run environment diagnostics and serialise the report as a JSON byte buffer.
 *
 * The report mirrors `tensogram::doctor::run_diagnostics()` and the
 * `tensogram doctor` CLI subcommand.  Cross-language parity: the same
 * JSON shape is produced by the Python `tensogram.doctor()` and the
 * WASM `doctor()` exports — see `docs/src/cli/doctor.md` for the
 * schema.  The C FFI build does **not** run the GRIB or NetCDF
 * converter self-tests (those features are CLI-only), so the
 * `self_test` array covers only the core encode/decode pipeline plus
 * the codecs compiled into the dylib.
 *
 * On success returns `TgmError::Ok` and fills `out` with a JSON
 * payload (UTF-8, NOT null-terminated).  Use `tgm_bytes_free` to
 * release it.  Callers can safely treat `out.data` as a `char*` of
 * length `out.len` and pass it to `json_loads` / `nlohmann::json::parse`
 * / equivalent.
 *
 * On serialisation failure returns `TgmError::Encoding` and writes a
 * human-readable description retrievable via `tgm_last_error()`.
 *
 * # Example
 *
 * ```c
 * tgm_bytes_t report = {0};
 * if (tgm_doctor_to_json(&report) == TGM_ERROR_OK) {
 *     fwrite(report.data, 1, report.len, stdout);
 *     tgm_bytes_free(report);
 * }
 * ```
 */
tgm_error tgm_doctor_to_json(tgm_bytes_t *out);

/**
 * Create a streaming encoder writing to a file.
 *
 * `metadata_json` is a free-form JSON object.  The `"descriptors"`
 * key is NOT permitted here (objects are supplied one at a time
 * via `tgm_streaming_encoder_write`).  A legacy top-level
 * `"version"` is tolerated and routed into `_extra_` on encode
 * (see `parse_streaming_metadata_json`).
 *
 * `hash_algo`: null-terminated string ("xxh3") or NULL for no hash.
 *
 * On success fills `out` with a `TgmStreamingEncoder` handle.
 * Free with `tgm_streaming_encoder_free` or finalize with
 * `tgm_streaming_encoder_finish`.
 */
tgm_error tgm_streaming_encoder_create(const char *path,
                                       const char *metadata_json,
                                       const char *hash_algo,
                                       uint32_t threads,
                                       tgm_streaming_encoder_t **out);

/**
 * Write a PrecederMetadata frame for the next data object.
 *
 * `metadata_json` is a JSON object with per-object metadata keys
 * (e.g. `{"mars": {"param": "2t"}, "units": "K"}`).  The keys
 * become `payload[0]` in a GlobalMetadata CBOR with empty `common`.
 *
 * Must be followed by exactly one `tgm_streaming_encoder_write` call
 * before another preceder or `tgm_streaming_encoder_finish`.
 */
tgm_error tgm_streaming_encoder_write_preceder(tgm_streaming_encoder_t *enc,
                                               const char *metadata_json);

/**
 * Write a single data object to the streaming encoder.
 *
 * `descriptor_json` is a JSON object with the descriptor fields
 * (type, ndim, shape, strides, dtype, byte_order, encoding, filter,
 * compression, etc.).
 */
tgm_error tgm_streaming_encoder_write(tgm_streaming_encoder_t *enc,
                                      const char *descriptor_json,
                                      const uint8_t *data,
                                      size_t data_len);

/**
 * Write a single pre-encoded data object to the streaming encoder.
 *
 * Like `tgm_streaming_encoder_write`, but `data` must already be encoded
 * according to the descriptor's pipeline (`encoding` / `filter` /
 * `compression`). The library does not run the encoding pipeline — it
 * validates the descriptor's pipeline configuration and writes the bytes
 * as-is into a data object frame. The hash (if configured on the encoder)
 * is recomputed over the caller's bytes.
 *
 * `descriptor_json`: same JSON schema as `tgm_streaming_encoder_write`.
 *
 * For `szip` compression, callers SHOULD include `szip_block_offsets`
 * (bit offsets, not byte offsets) in the descriptor's params so that
 * `tgm_decode_range` can locate compressed block boundaries later.
 * Other pipeline params (e.g. `simple_packing` reference value, scale
 * factors) must also be present in the descriptor.
 *
 * Any `hash` field embedded in the descriptor JSON is ignored — the
 * library always recomputes the hash from the caller's bytes.
 */
tgm_error tgm_streaming_encoder_write_pre_encoded(tgm_streaming_encoder_t *enc,
                                                  const char *descriptor_json,
                                                  const uint8_t *data,
                                                  size_t data_len);

/**
 * Return the number of objects written so far.
 */
size_t tgm_streaming_encoder_count(const tgm_streaming_encoder_t *enc);

/**
 * Finalize the streaming encoder, writing footer and closing the file.
 *
 * After calling this, the handle is still valid but empty — the caller
 * must still call `tgm_streaming_encoder_free` to release it.
 */
tgm_error tgm_streaming_encoder_finish(tgm_streaming_encoder_t *enc);

/**
 * Free a streaming encoder without finalizing (abandons the output).
 */
void tgm_streaming_encoder_free(tgm_streaming_encoder_t *enc);

/**
 * Validate a single Tensogram message buffer.
 *
 * `buf` / `buf_len`: the wire-format message bytes (single message).
 *   `buf` may be NULL when `buf_len` is 0 (empty-buffer validation).
 * `level`: validation depth — null-terminated C string:
 *   `"quick"` (structure only), `"default"` (up to hash check),
 *   `"checksum"` (hash check, suppress structural warnings),
 *   `"full"` (full decode + NaN/Inf scan). NULL defaults to `"default"`.
 * `check_canonical`: non-zero to check RFC 8949 CBOR key ordering.
 * `out`: receives UTF-8 JSON bytes describing the validation report.
 *   Not NUL-terminated — use `out->len` for the byte count.
 *   Free with `tgm_bytes_free`.
 *
 * Returns `TGM_ERROR_OK` on success (even if the message has issues —
 * the issues are in the JSON report). Returns `TGM_ERROR_INVALID_ARG`
 * for argument validation failures (null pointers, invalid level string),
 * or `TGM_ERROR_ENCODING` if JSON serialization of the report fails.
 */
tgm_error tgm_validate(const uint8_t *buf,
                       size_t buf_len,
                       const char *level,
                       int32_t check_canonical,
                       tgm_bytes_t *out);

/**
 * Validate all messages in a `.tgm` file.
 *
 * `path`: null-terminated UTF-8 path to the file.
 * `level`: validation depth (same as `tgm_validate`). NULL = `"default"`.
 * `check_canonical`: non-zero to check CBOR key ordering.
 * `out`: receives UTF-8 JSON bytes describing the file validation report.
 *   Not NUL-terminated — use `out->len` for the byte count.
 *   Free with `tgm_bytes_free`.
 *
 * Returns `TGM_ERROR_OK` on success (issues are in the JSON).
 * Returns `TGM_ERROR_IO` if the file cannot be opened or read.
 * Returns `TGM_ERROR_INVALID_ARG` for null pointers or invalid level.
 * Returns `TGM_ERROR_ENCODING` if JSON serialization of the report fails.
 */
tgm_error tgm_validate_file(const char *path,
                            const char *level,
                            int32_t check_canonical,
                            tgm_bytes_t *out);

/**
 * Allocate a fresh cancellation token in the un-cancelled state.
 *
 * The returned handle is caller-owned; free it with
 * `tgm_cancellation_token_free`.  A single token may be passed to
 * any number of `tgm_async_*` calls; cancelling it propagates to
 * all in-flight tasks holding a reference.
 */
tgm_cancellation_token_t *tgm_cancellation_token_create(void);

/**
 * Cancel the token.  Idempotent.  Cancelling a NULL handle is a
 * no-op.  Tasks attached to this token transition to
 * [`TgmError::Cancelled`] at their next yield point.
 */
void tgm_cancellation_token_cancel(tgm_cancellation_token_t *tok);

/**
 * Returns `true` if the token has been cancelled.  A NULL handle
 * returns `false`.
 */
bool tgm_cancellation_token_is_cancelled(const tgm_cancellation_token_t *tok);

/**
 * Free a cancellation token.  Safe to call before any in-flight
 * task completes — each task holds its own internal clone of the
 * underlying tokio token, so freeing the user-side handle does not
 * invalidate cancellation for already-spawned tasks.  Freeing a
 * NULL handle is a no-op.
 */
void tgm_cancellation_token_free(tgm_cancellation_token_t *tok);

/**
 * Register a completion callback on `task`.  Must be called exactly
 * once per task; subsequent calls return [`TgmError::InvalidArg`]
 * regardless of whether the task is still pending or already
 * resolved.
 *
 * The callback fires on a **dispatcher pool worker** (a non-tokio
 * thread owned by `tensogram-ffi`), so a slow or blocking callback
 * does not stall the runtime.  The callback contract: callbacks
 * must complete quickly, must not
 * throw, and must not block on locks held by the caller of any
 * other tgm_* function on this thread.
 *
 * If the task has already resolved when this function is called,
 * the callback is enqueued on the dispatcher pool immediately so
 * the worker runs the user code on a dispatcher thread.  Under
 * extreme overload (the dispatcher's bounded queue is full) the
 * callback may run inline on the caller's thread as a graceful-
 * degradation path; bump `dispatcher_workers` via
 * `tgm_runtime_configure` to avoid this.
 */
tgm_error tgm_async_task_set_completion(tgm_async_task_t *task, void (*cb)(void*), void *userdata);

/**
 * Returns `true` if the task has resolved (whether successfully,
 * by error, by timeout, or by cancellation).  A NULL handle returns
 * `false`.  Non-blocking; safe to call from any thread.
 */
bool tgm_async_task_is_ready(const tgm_async_task_t *task);

/**
 * Cancel an in-flight task by signalling its internal token.  The
 * task transitions to [`TgmError::Cancelled`] at the next yield point.
 * A NULL handle is a no-op.
 */
void tgm_async_task_cancel(tgm_async_task_t *task);

/**
 * Free a task handle.  Must be called exactly once per task to
 * release the slot's heap allocation.  Safe to call after
 * [`tgm_async_task_join`]: the join consumes the result but does
 * not free the handle itself.  Freeing a NULL handle is a no-op.
 */
void tgm_async_task_free(tgm_async_task_t *task);

/**
 * Block the calling thread until the task is ready, then return
 * its outcome.
 *
 * `_join_void` is for tasks whose success is ABI-empty (writes,
 * finishes, prefetches).  Returns [`TgmError::Ok`] on success.  On
 * failure, the matching error code is returned and
 * [`tgm_last_error`] is populated.
 *
 * Call [`tgm_async_task_free`] to release the task slot after
 * joining.  Joining the same task twice returns
 * [`TgmError::InvalidArg`] (`task result already consumed`).
 */
tgm_error tgm_async_task_join_void(tgm_async_task_t *task);

/**
 * Block the calling thread until the task is ready, then write its
 * `usize` result to `*out` and return [`TgmError::Ok`].  See
 * [`tgm_async_task_join_void`] for the joint contract on errors,
 * type mismatches, and double-join.
 */
tgm_error tgm_async_task_join_size(tgm_async_task_t *task, uint64_t *out);

/**
 * Block until ready, then transfer ownership of the task's byte
 * buffer to the caller via `*out`.  The caller must release the
 * buffer with [`tgm_bytes_free`].  See [`tgm_async_task_join_void`]
 * for the joint contract.
 */
tgm_error tgm_async_task_join_bytes(tgm_async_task_t *task, tgm_bytes_t *out);

/**
 * Block until ready, then transfer ownership of the decoded message
 * to the caller via `*out`.  The caller must release the message
 * with [`tgm_message_free`].  See [`tgm_async_task_join_void`] for
 * the joint contract.
 */
tgm_error tgm_async_task_join_message(tgm_async_task_t *task, tgm_message_t **out);

/**
 * Block until ready, then transfer ownership of the decoded
 * metadata to the caller via `*out`.  The caller must release it
 * with [`tgm_metadata_free`].  See [`tgm_async_task_join_void`]
 * for the joint contract.
 */
tgm_error tgm_async_task_join_metadata(tgm_async_task_t *task, tgm_metadata_t **out);

/**
 * Block until ready, then transfer ownership of the opened async
 * file handle to the caller via `*out`.  The caller must release it
 * with [`tgm_async_file_close`].  See [`tgm_async_task_join_void`]
 * for the joint contract.
 */
tgm_error tgm_async_task_join_async_file(tgm_async_task_t *task, tgm_async_file_t **out);

/**
 * Block until ready, then transfer ownership of an array of byte
 * buffers (one per requested range) to the caller.  Writes the
 * array pointer to `*out_array` and the entry count to
 * `*out_count`.  The caller must release the array via
 * [`tgm_multi_bytes_free`].  See [`tgm_async_task_join_void`] for
 * the joint contract.
 */
tgm_error tgm_async_task_join_multi_bytes(tgm_async_task_t *task,
                                          tgm_bytes_t **out_array,
                                          size_t *out_count);

/**
 * Free an array of `TgmBytes` returned by `tgm_async_task_join_multi_bytes`.
 */
void tgm_multi_bytes_free(tgm_bytes_t *array, size_t count);

/**
 * Borrowed pointer to the file's path string.  Valid until the
 * handle is closed.  Returns NULL on a NULL handle.
 */
const char *tgm_async_file_path(const tgm_async_file_t *file);

/**
 * Close an async file handle.  Internally backed by
 * `Arc<TensogramFile>`, so any task currently using the handle
 * keeps the underlying file alive until the task completes.
 * Closing a NULL handle is a no-op.
 */
void tgm_async_file_close(tgm_async_file_t *file);

/**
 * Open a Tensogram file asynchronously.  Returns immediately with a
 * task handle; join via `tgm_async_task_join_async_file`.
 */
tgm_error tgm_async_file_open(const char *path,
                              tgm_cancellation_token_t *cancel,
                              uint64_t timeout_ms,
                              tgm_async_task_t **out_task);

/**
 * Open a remote `.tgm` (S3 / GCS / Azure / HTTP).  Always exported
 * at the C ABI level so consumers linking the cdylib never see an
 * undefined symbol; when the `async-remote` Cargo feature is off
 * the function returns [`TgmError::Remote`] with a clear
 * `tgm_last_error()` message instead of dispatching.
 */
tgm_error tgm_async_file_open_remote(const char *url,
                                     const char *const *storage_keys,
                                     const char *const *storage_values,
                                     size_t nopts,
                                     bool bidirectional,
                                     tgm_cancellation_token_t *cancel,
                                     uint64_t timeout_ms,
                                     tgm_async_task_t **out_task);

/**
 * Async equivalent of [`tgm_file_message_count`].  Returns
 * immediately with a task handle that resolves to the message count
 * (joinable via [`tgm_async_task_join_size`]).  See the type
 * docstrings for the cancellation/timeout/null-handle contract
 * shared by every `tgm_async_file_*` entry point.
 */
tgm_error tgm_async_file_message_count(tgm_async_file_t *file,
                                       tgm_cancellation_token_t *cancel,
                                       uint64_t timeout_ms,
                                       tgm_async_task_t **out_task);

/**
 * Async equivalent of [`tgm_file_read_message`].  Resolves to the
 * raw message bytes (joinable via [`tgm_async_task_join_bytes`]).
 * See the type docstrings for the shared cancellation/timeout
 * contract.
 */
tgm_error tgm_async_file_read_message(tgm_async_file_t *file,
                                      size_t index,
                                      tgm_cancellation_token_t *cancel,
                                      uint64_t timeout_ms,
                                      tgm_async_task_t **out_task);

/**
 * Async equivalent of [`tgm_file_decode_message`].  Resolves to a
 * fully decoded [`TgmMessage`] (joinable via
 * [`tgm_async_task_join_message`]).  `threads = 0` selects the
 * `tensogram::DecodeOptions` default.  See the type docstrings for
 * the shared cancellation/timeout contract.
 */
tgm_error tgm_async_file_decode_message(tgm_async_file_t *file,
                                        size_t index,
                                        bool native_byte_order,
                                        uint32_t threads,
                                        bool restore_non_finite,
                                        bool verify_hash,
                                        tgm_cancellation_token_t *cancel,
                                        uint64_t timeout_ms,
                                        tgm_async_task_t **out_task);

/**
 * Async equivalent of [`tgm_file_decode_metadata`].  Resolves to a
 * [`TgmMetadata`] handle (joinable via
 * [`tgm_async_task_join_metadata`]) without materialising tensor
 * payloads.  See the type docstrings for the shared
 * cancellation/timeout contract.
 */
tgm_error tgm_async_file_decode_metadata(tgm_async_file_t *file,
                                         size_t index,
                                         tgm_cancellation_token_t *cancel,
                                         uint64_t timeout_ms,
                                         tgm_async_task_t **out_task);

/**
 * Async equivalent of [`tgm_file_decode_object`].  Resolves to a
 * single-object [`TgmMessage`] (joinable via
 * [`tgm_async_task_join_message`]) so the existing `tgm_object_*`
 * and `tgm_message_*` accessors work uniformly.  See the type
 * docstrings for the shared cancellation/timeout contract.
 */
tgm_error tgm_async_file_decode_object(tgm_async_file_t *file,
                                       size_t msg_index,
                                       size_t obj_index,
                                       bool native_byte_order,
                                       uint32_t threads,
                                       bool restore_non_finite,
                                       bool verify_hash,
                                       tgm_cancellation_token_t *cancel,
                                       uint64_t timeout_ms,
                                       tgm_async_task_t **out_task);

/**
 * Async equivalent of [`tgm_file_decode_range`].  Each `(offset,
 * count)` pair in `offsets[]` / `counts[]` (length `n_ranges`)
 * describes a sub-range of the object's logical element stream.
 * Resolves to a vector of byte buffers, one per range, joinable via
 * [`tgm_async_task_join_multi_bytes`].  See the type docstrings for
 * the shared cancellation/timeout contract.
 */
tgm_error tgm_async_file_decode_range(tgm_async_file_t *file,
                                      size_t msg_index,
                                      size_t obj_index,
                                      const uint64_t *offsets,
                                      const uint64_t *counts,
                                      size_t n_ranges,
                                      bool native_byte_order,
                                      uint32_t threads,
                                      tgm_cancellation_token_t *cancel,
                                      uint64_t timeout_ms,
                                      tgm_async_task_t **out_task);

/**
 * Configure the FFI tokio runtime.  Must be called before any other
 * `tgm_async_*` call; subsequent calls return [`TgmError::InvalidArg`].
 *
 * Pass `0` to use the default for any field.
 */
tgm_error tgm_runtime_configure(uint32_t workers,
                                uint32_t dispatcher_workers,
                                uint64_t multipart_part_size_bytes);

/**
 * Shut the shared async runtime down, blocking for up to
 * `timeout_ms` while in-flight tasks drain.
 *
 * Returns the number of tasks that had **not** finished when the
 * timeout elapsed (`0` on a clean drain).  After this call the
 * runtime is permanently shut down: every subsequent `tgm_async_*`
 * entry point fails fast with `TGM_ERROR_IO` and a descriptive
 * `tgm_last_error()` (`"runtime has been shut down"`).  The runtime
 * is single-shot — there is no rebuild.
 *
 * Behaviour by prior state:
 *   * **never built** (no async op ran) → transitions straight to
 *     `ShutDown` and returns `0`; nothing was ever spawned.
 *   * **build previously failed** → transitions to `ShutDown` and
 *     returns `0`; there was no runtime to drain.
 *   * **already shut down** → idempotent no-op returning `0`.
 *   * **live** → takes ownership of the runtime, drains in-flight
 *     tasks up to `timeout_ms`, tears the runtime down, and reports
 *     the count of tasks that had not finished by the deadline.
 *
 * Must not be called from inside an async callback running on the
 * runtime's own worker threads (tokio forbids dropping a runtime
 * from within itself).  The intended caller is the application's
 * main/teardown thread.
 */
uint64_t tgm_runtime_shutdown_blocking(uint64_t timeout_ms);

/**
 * Borrowed pointer to the encoder's path string.  Valid for the
 * lifetime of the handle.  Returns NULL on a NULL handle.
 */
const char *tgm_async_streaming_encoder_path(const tgm_async_streaming_encoder_t *enc);

/**
 * Free the encoder handle.
 *
 * **Drop semantics:** the underlying encoder is held behind an
 * `Arc<Mutex<Option<...>>>`.  If a task is mid-flight (e.g. a
 * `write_object` whose returned `tgm_async_task_t*` has not been
 * joined and freed yet), the task holds its own `Arc` clone of the
 * inner state.  Calling `tgm_async_streaming_encoder_free` while a
 * task is in flight is therefore memory-safe: the inner encoder
 * stays alive until the last `Arc` (the task's) drops.
 *
 * However: if the encoder is dropped without
 * `tgm_async_streaming_encoder_finish` having completed, the on-disk
 * file is **structurally invalid** (no footer frames, no postamble,
 * `total_length = 0`).  Validating readers will reject the file.
 * This matches the cancellation-mid-stream contract: operational
 * systems do not trust truncated `.tgm` files.  Callers who care about a clean file must
 * drive a successful `finish` task before freeing the encoder.
 */
void tgm_async_streaming_encoder_free(tgm_async_streaming_encoder_t *enc);

/**
 * Create an async streaming encoder writing to a local file.
 *
 * Returns a task that resolves to a `tgm_async_streaming_encoder_t*`
 * (joinable via `tgm_async_task_join_async_streaming_encoder`).
 *
 * `metadata_json` follows the same schema as the sync streaming
 * encoder (see `tgm_streaming_encoder_create`).  The async encoder
 * writes the preamble + header metadata frame to the sink before
 * the task resolves.
 */
tgm_error tgm_async_streaming_encoder_create(const char *path,
                                             const char *metadata_json,
                                             const char *hash_algo,
                                             uint32_t threads,
                                             tgm_cancellation_token_t *cancel,
                                             uint64_t timeout_ms,
                                             tgm_async_task_t **out_task);

/**
 * Encode and append one data object to the stream.
 *
 * `descriptor_json` is a JSON-serialised `DataObjectDescriptor`
 * matching the sync `tgm_streaming_encoder_write_object` schema.
 * `data` / `len` describe the raw element buffer; the encoder runs
 * the configured filter / compression / encoding pipeline on it.
 *
 * The C caller's `data` buffer is **copied** before this function
 * returns, so the buffer may be reused immediately.  The returned
 * task resolves to `void` (joinable via
 * [`tgm_async_task_join_void`]).
 *
 * Concurrent `write_*` calls on the same encoder are serialised
 * via an internal `tokio::sync::Mutex`; the underlying AsyncWrite
 * is naturally serial.
 */
tgm_error tgm_async_streaming_encoder_write_object(tgm_async_streaming_encoder_t *enc,
                                                   const char *descriptor_json,
                                                   const uint8_t *data,
                                                   size_t len,
                                                   tgm_cancellation_token_t *cancel,
                                                   uint64_t timeout_ms,
                                                   tgm_async_task_t **out_task);

/**
 * Append one already-encoded data object to the stream, bypassing
 * the encoder's filter / compression / encoding pipeline.  `data`
 * is treated as the final on-disk payload bytes; `descriptor_json`
 * must describe the post-pipeline frame.
 *
 * Useful for relaying frames between encoders without redundant
 * transcoding.  Other semantics (data copy, serialisation,
 * cancellation, void result) match
 * [`tgm_async_streaming_encoder_write_object`].
 */
tgm_error tgm_async_streaming_encoder_write_pre_encoded(tgm_async_streaming_encoder_t *enc,
                                                        const char *descriptor_json,
                                                        const uint8_t *data,
                                                        size_t len,
                                                        tgm_cancellation_token_t *cancel,
                                                        uint64_t timeout_ms,
                                                        tgm_async_task_t **out_task);

/**
 * Append a per-message preceder metadata frame.  `metadata_json`
 * is a flat JSON object (one level of nesting); keys become CBOR
 * map keys, values are converted to CBOR primitives.
 *
 * Resolves to `void` (joinable via [`tgm_async_task_join_void`]).
 * Serialised against `write_*` via the same internal mutex.
 */
tgm_error tgm_async_streaming_encoder_write_preceder(tgm_async_streaming_encoder_t *enc,
                                                     const char *metadata_json,
                                                     tgm_cancellation_token_t *cancel,
                                                     uint64_t timeout_ms,
                                                     tgm_async_task_t **out_task);

/**
 * Finalise the stream: flush pending frames, write the footer,
 * and (if `backfill = true`) seek back to update the preamble's
 * `total_length`.
 *
 * Consumes the encoder's inner state — subsequent `write_*` /
 * `finish` calls on the same handle return
 * [`TensogramError::Framing`] (`encoder already finished`).  The
 * handle itself must still be released with
 * [`tgm_async_streaming_encoder_free`].
 *
 * `backfill` requires that the underlying `tokio::fs::File`
 * supports seeks (true for local files, may not be true for
 * future remote sinks).  If a clean file is required and the
 * task is cancelled mid-finish, the on-disk file is structurally
 * invalid (see free's drop semantics).
 */
tgm_error tgm_async_streaming_encoder_finish(tgm_async_streaming_encoder_t *enc,
                                             bool backfill,
                                             tgm_cancellation_token_t *cancel,
                                             uint64_t timeout_ms,
                                             tgm_async_task_t **out_task);

/**
 * Snapshot the encoder's object count without blocking.  Returns a
 * status describing whether `*out_count` is valid.
 *
 * Use this in preference to the convenience accessor when you need
 * to distinguish "0 objects written so far" from "handle invalid"
 * or "encoder already finished".
 */
TgmObjectCountStatus tgm_async_streaming_encoder_try_object_count(const tgm_async_streaming_encoder_t *enc,
                                                                  size_t *out_count);

/**
 * Convenience: object count as a single number, with the historical
 * `usize::MAX` sentinel covering all "not OK" outcomes (null handle,
 * busy, finished).  Callers that need to discriminate should use
 * [`tgm_async_streaming_encoder_try_object_count`] instead.
 */
size_t tgm_async_streaming_encoder_object_count(const tgm_async_streaming_encoder_t *enc);

/**
 * Typed join for tasks returning a streaming-encoder handle.
 */
tgm_error tgm_async_task_join_async_streaming_encoder(tgm_async_task_t *task,
                                                      tgm_async_streaming_encoder_t **out);

#endif  /* TENSOGRAM_H */
