/*
 * (C) Copyright 2026- ECMWF and individual contributors.
 *
 * This software is licensed under the terms of the Apache Licence Version 2.0
 * which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
 * In applying this licence, ECMWF does not waive the privileges and immunities
 * granted to it by virtue of its status as an intergovernmental organisation nor
 * does it submit to any jurisdiction.
 *
 * Tensogram C API — generated by cbindgen. Do not edit.
 */


#ifndef TENSOGRAM_H
#define TENSOGRAM_H

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

typedef enum {
  TGM_ERROR_OK = 0,
  TGM_ERROR_FRAMING = 1,
  TGM_ERROR_METADATA = 2,
  TGM_ERROR_ENCODING = 3,
  TGM_ERROR_COMPRESSION = 4,
  TGM_ERROR_OBJECT = 5,
  TGM_ERROR_IO = 6,
  TGM_ERROR_HASH_MISMATCH = 7,
  TGM_ERROR_INVALID_ARG = 8,
  /**
   * Returned by `tgm_*_iter_next` when iteration is exhausted.
   */
  TGM_ERROR_END_OF_ITER = 9,
  TGM_ERROR_REMOTE = 10,
} tgm_error;

/**
 * Opaque handle for iterating over messages in a byte buffer.
 *
 * The caller's buffer must remain valid for the lifetime of this iterator.
 */
typedef struct tgm_buffer_iter_t tgm_buffer_iter_t;

/**
 * File handle.
 */
typedef struct tgm_file_t tgm_file_t;

/**
 * Opaque handle for iterating over messages in a file.
 */
typedef struct tgm_file_iter_t tgm_file_iter_t;

/**
 * Decoded message: global metadata + decoded (descriptor, payload) pairs.
 */
typedef struct tgm_message_t tgm_message_t;

/**
 * Metadata-only handle (no decoded payloads).
 */
typedef struct tgm_metadata_t tgm_metadata_t;

/**
 * Opaque handle for iterating over objects within a single message.
 */
typedef struct tgm_object_iter_t tgm_object_iter_t;

/**
 * Opaque handle for scan results.
 */
typedef struct tgm_scan_result_t tgm_scan_result_t;

/**
 * Opaque handle for a streaming encoder that writes data objects progressively.
 */
typedef struct tgm_streaming_encoder_t tgm_streaming_encoder_t;

/**
 * An owned byte buffer returned by encode functions.
 */
typedef struct {
  uint8_t *data;
  size_t len;
} tgm_bytes_t;

/**
 * Scan result: array of (offset, length) pairs.
 */
typedef struct {
  size_t offset;
  size_t length;
} tgm_scan_entry_t;

/**
 * Returns a pointer to the last error message, or NULL if no error.
 * The pointer is valid until the next FFI call on the same thread.
 */
const char *tgm_last_error(void);

/**
 * Free a byte buffer returned by `tgm_encode`.
 */
void tgm_bytes_free(tgm_bytes_t buf);

/**
 * Encode a Tensogram message from JSON metadata and raw data slices.
 *
 * `metadata_json`: null-terminated UTF-8 JSON string. Must contain:
 *   - `"version"` (integer)
 *   - `"descriptors"` (array of per-object descriptor objects)
 *   - optional extra keys (e.g. `"mars"`) at the top level
 *
 * `data_ptrs` / `data_lens`: arrays of length `num_objects`, raw bytes per object.
 *
 * `hash_algo`: null-terminated string ("xxh3") or NULL for no hash.
 *
 * `reject_nan` / `reject_inf`: when `true`, the encoder scans float
 * payloads before the pipeline runs and returns
 * [`TgmError::Encoding`] on the first NaN / Inf.  Pass `false` to
 * preserve the current behaviour.  See the Rust
 * `EncodeOptions::reject_nan` docs for full semantics.  Integer
 * dtypes are not scanned.
 *
 * On success returns `TgmError::Ok` and fills `out` with the encoded bytes.
 * The caller must free `out` with `tgm_bytes_free`.
 */
tgm_error tgm_encode(const char *metadata_json,
                     const uint8_t *const *data_ptrs,
                     const size_t *data_lens,
                     size_t num_objects,
                     const char *hash_algo,
                     uint32_t threads,
                     bool reject_nan,
                     bool reject_inf,
                     tgm_bytes_t *out);

/**
 * Encode a Tensogram message from JSON metadata and pre-encoded payload bytes.
 *
 * Like `tgm_encode`, but each `data_ptrs[i]` slice must already be encoded
 * according to the matching descriptor's `encoding` / `filter` / `compression`
 * pipeline. The library does not run the encoding pipeline again — it writes
 * the caller-provided bytes directly into the wire-format payload after
 * validating that the descriptor's pipeline configuration is well-formed.
 *
 * `metadata_json`: same flat JSON schema as `tgm_encode` (`version`,
 *   `descriptors`, optional `base`, plus arbitrary extra top-level keys).
 *
 * `data_ptrs` / `data_lens`: arrays of length `num_objects` pointing at
 *   already-encoded payload bytes (one entry per descriptor).
 *
 * `hash_algo`: null-terminated string ("xxh3") or NULL for no hash. The
 *   library always recomputes the hash over the caller's bytes; any
 *   `hash` field embedded in the descriptor JSON is ignored and overwritten.
 *
 * Notes for compression-aware decoding:
 * - For `szip` compression, callers SHOULD include `szip_block_offsets`
 *   (a list of bit offsets into the compressed payload) inside the
 *   matching descriptor's params so that `tgm_decode_range` can locate
 *   szip block boundaries without rescanning the compressed stream.
 * - Other pipeline params (e.g. `simple_packing` reference value, scale
 *   factors) must also be present in the descriptor — they are not
 *   inferred from the bytes.
 *
 * On success returns `TgmError::Ok` and fills `out` with the encoded message.
 * The caller must free `out` with `tgm_bytes_free`.
 */
tgm_error tgm_encode_pre_encoded(const char *metadata_json,
                                 const uint8_t *const *data_ptrs,
                                 const size_t *data_lens,
                                 size_t num_objects,
                                 const char *hash_algo,
                                 uint32_t threads,
                                 tgm_bytes_t *out);

/**
 * Decode a complete message (global metadata + all object payloads).
 *
 * `buf` / `buf_len`: the wire-format message bytes.
 * `verify_hash`: if non-zero, verify payload hashes during decode.
 *
 * On success, fills `out` with a `TgmMessage` handle.
 * Free with `tgm_message_free`.
 */
tgm_error tgm_decode(const uint8_t *buf,
                     size_t buf_len,
                     int32_t verify_hash,
                     int32_t native_byte_order,
                     uint32_t threads,
                     tgm_message_t **out);

/**
 * Decode only the global metadata (no payload bytes are read).
 */
tgm_error tgm_decode_metadata(const uint8_t *buf, size_t buf_len, tgm_metadata_t **out);

/**
 * Decode a single object by index.
 *
 * On success, fills `out` with a `TgmMessage` handle containing exactly
 * one object (at index 0). The global metadata covers the whole message.
 */
tgm_error tgm_decode_object(const uint8_t *buf,
                            size_t buf_len,
                            size_t index,
                            int32_t verify_hash,
                            int32_t native_byte_order,
                            uint32_t threads,
                            tgm_message_t **out);

/**
 * Decode partial ranges from a data object.
 *
 * `ranges_offsets` / `ranges_counts`: parallel arrays of (element_offset, element_count).
 * `num_ranges`: length of both arrays.
 * `join`: when non-zero, concatenate all ranges into a single buffer in `out[0]`
 *         and set `*out_count = 1`.  When zero (split mode), write one `TgmBytes`
 *         per range into `out[0..num_ranges]` and set `*out_count = num_ranges`.
 *         The caller must pre-allocate `out` with at least `num_ranges` entries
 *         when `join == 0`, or 1 entry when `join != 0`.
 * `out_count`: filled with the number of buffers written to `out`.
 *
 * Free each returned buffer with `tgm_bytes_free`.
 */
tgm_error tgm_decode_range(const uint8_t *buf,
                           size_t buf_len,
                           size_t object_index,
                           const uint64_t *ranges_offsets,
                           const uint64_t *ranges_counts,
                           size_t num_ranges,
                           int32_t verify_hash,
                           int32_t native_byte_order,
                           uint32_t threads,
                           int32_t join,
                           tgm_bytes_t *out,
                           size_t *out_count);

/**
 * Scan a buffer for message boundaries.
 *
 * Returns a `TgmScanResult` handle. Access entries with `tgm_scan_count`
 * and `tgm_scan_entry`. Free with `tgm_scan_free`.
 */
tgm_error tgm_scan(const uint8_t *buf, size_t buf_len, tgm_scan_result_t **out);

/**
 * Returns the number of messages found by `tgm_scan`.
 */
size_t tgm_scan_count(const tgm_scan_result_t *result);

tgm_scan_entry_t tgm_scan_entry(const tgm_scan_result_t *result, size_t index);

/**
 * Free a scan result handle.
 */
void tgm_scan_free(tgm_scan_result_t *result);

/**
 * Returns the wire format version from a decoded message.
 */
uint64_t tgm_message_version(const tgm_message_t *msg);

/**
 * Returns the number of decoded objects in this message handle.
 * For `tgm_decode` this equals the total object count; for
 * `tgm_decode_object` this is always 1.
 */
size_t tgm_message_num_objects(const tgm_message_t *msg);

/**
 * Returns the number of decoded payload buffers.
 * Equivalent to `tgm_message_num_objects` — kept for ABI compatibility.
 */
size_t tgm_message_num_decoded(const tgm_message_t *msg);

/**
 * Returns the number of dimensions for object at index.
 */
uint64_t tgm_object_ndim(const tgm_message_t *msg, size_t index);

/**
 * Returns a pointer to the shape array. Length is `tgm_object_ndim()`.
 * The pointer is valid until the message is freed.
 */
const uint64_t *tgm_object_shape(const tgm_message_t *msg, size_t index);

/**
 * Returns a pointer to the strides array. Length is `tgm_object_ndim()`.
 */
const uint64_t *tgm_object_strides(const tgm_message_t *msg, size_t index);

/**
 * Returns the dtype as a null-terminated string (e.g. "float32").
 * The pointer is valid until the message is freed.
 */
const char *tgm_object_dtype(const tgm_message_t *msg, size_t index);

/**
 * Returns a pointer to the decoded payload bytes for a decoded object.
 * `decoded_index` is the index into the decoded objects array (0 for the
 * first decoded object, regardless of the original object index).
 * `out_len` receives the byte length.
 */
const uint8_t *tgm_object_data(const tgm_message_t *msg, size_t decoded_index, size_t *out_len);

/**
 * Returns the encoding string for a data object descriptor (e.g. "none", "simple_packing").
 * The pointer is valid until the message is freed.
 */
const char *tgm_payload_encoding(const tgm_message_t *msg, size_t index);

/**
 * Returns 1 if the object descriptor has a hash, 0 otherwise.
 */
int32_t tgm_payload_has_hash(const tgm_message_t *msg, size_t index);

/**
 * Extract a metadata handle from a decoded message.
 * The metadata handle is independent — free it separately with `tgm_metadata_free`.
 */
tgm_error tgm_message_metadata(const tgm_message_t *msg, tgm_metadata_t **out);

/**
 * Returns the object type string (e.g. "ndarray"). Valid until message freed.
 */
const char *tgm_object_type(const tgm_message_t *msg, size_t index);

/**
 * Returns the byte order string ("big" or "little"). Valid until message freed.
 */
const char *tgm_object_byte_order(const tgm_message_t *msg, size_t index);

/**
 * Returns the filter string (e.g. "none", "shuffle"). Valid until message freed.
 */
const char *tgm_object_filter(const tgm_message_t *msg, size_t index);

/**
 * Returns the compression string (e.g. "none", "zstd"). Valid until message freed.
 */
const char *tgm_object_compression(const tgm_message_t *msg, size_t index);

/**
 * Returns the hash type string ("xxh3") or NULL if no hash. Valid until message freed.
 */
const char *tgm_object_hash_type(const tgm_message_t *msg, size_t index);

/**
 * Returns the hash value hex string or NULL if no hash. Valid until message freed.
 */
const char *tgm_object_hash_value(const tgm_message_t *msg, size_t index);

/**
 * Free a decoded message handle.
 */
void tgm_message_free(tgm_message_t *msg);

/**
 * Returns the wire format version from metadata.
 */
uint64_t tgm_metadata_version(const tgm_metadata_t *meta);

/**
 * Returns the number of objects described in the global metadata.
 *
 * Returns the length of the `base` array, which has one entry per data object.
 */
size_t tgm_metadata_num_objects(const tgm_metadata_t *meta);

/**
 * Look up a string value by dot-notation key (e.g. "mars.class").
 * Returns NULL if the key is not found or is not a string.
 * The pointer is valid until the metadata handle is freed.
 */
const char *tgm_metadata_get_string(const tgm_metadata_t *meta, const char *key);

/**
 * Look up an integer value by dot-notation key.
 * Returns `default_val` if the key is not found or is not an integer.
 */
int64_t tgm_metadata_get_int(const tgm_metadata_t *meta, const char *key, int64_t default_val);

/**
 * Look up a float value by dot-notation key.
 */
double tgm_metadata_get_float(const tgm_metadata_t *meta, const char *key, double default_val);

/**
 * Free a metadata handle.
 */
void tgm_metadata_free(tgm_metadata_t *meta);

/**
 * Open an existing Tensogram file for reading.
 */
tgm_error tgm_file_open(const char *path, tgm_file_t **out);

/**
 * Create a new Tensogram file for writing.
 */
tgm_error tgm_file_create(const char *path, tgm_file_t **out);

/**
 * Count messages in the file (may trigger lazy scan).
 */
tgm_error tgm_file_message_count(tgm_file_t *file, size_t *out_count);

/**
 * Decode message at `index` from the file.
 * On success fills `out` with a `TgmMessage` handle.
 */
tgm_error tgm_file_decode_message(tgm_file_t *file,
                                  size_t index,
                                  int32_t verify_hash,
                                  int32_t native_byte_order,
                                  uint32_t threads,
                                  tgm_message_t **out);

/**
 * Read raw message bytes at `index`.
 * On success fills `out` with a `TgmBytes` buffer.
 */
tgm_error tgm_file_read_message(tgm_file_t *file, size_t index, tgm_bytes_t *out);

/**
 * Append raw message bytes to the file.
 */
tgm_error tgm_file_append_raw(tgm_file_t *file, const uint8_t *buf, size_t buf_len);

/**
 * Returns the file path as a null-terminated string.
 * The pointer is valid until the file handle is closed.
 */
const char *tgm_file_path(const tgm_file_t *file);

/**
 * Encode and append a message to the file.
 * Same JSON schema as `tgm_encode` for `metadata_json`.
 * `reject_nan` / `reject_inf` match `tgm_encode`'s semantics.
 */
tgm_error tgm_file_append(tgm_file_t *file,
                          const char *metadata_json,
                          const uint8_t *const *data_ptrs,
                          const size_t *data_lens,
                          size_t num_objects,
                          const char *hash_algo,
                          uint32_t threads,
                          bool reject_nan,
                          bool reject_inf);

/**
 * Close a file handle and release resources.
 */
void tgm_file_close(tgm_file_t *file);

/**
 * Compute simple_packing parameters for a set of f64 values.
 *
 * Returns TgmError::Ok on success, filling the out-params.
 * Returns Encoding error if data contains NaN.
 */
tgm_error tgm_simple_packing_compute_params(const double *values,
                                            size_t num_values,
                                            uint32_t bits_per_value,
                                            int32_t decimal_scale_factor,
                                            double *out_reference_value,
                                            int32_t *out_binary_scale_factor);

/**
 * Create a buffer message iterator.
 *
 * Scans `buf` once and stores message boundaries. The buffer must remain
 * valid and unmodified until `tgm_buffer_iter_free` is called.
 */
tgm_error tgm_buffer_iter_create(const uint8_t *buf, size_t buf_len, tgm_buffer_iter_t **out);

/**
 * Return the total number of messages in the buffer iterator.
 */
size_t tgm_buffer_iter_count(const tgm_buffer_iter_t *iter);

/**
 * Advance the buffer iterator. On success, sets `out_buf` and `out_len` to
 * the next message slice (borrowed from the original buffer).
 *
 * Returns `TgmError::Ok` if a message is available, `TgmError::EndOfIter`
 * when iteration is exhausted.
 */
tgm_error tgm_buffer_iter_next(tgm_buffer_iter_t *iter, const uint8_t **out_buf, size_t *out_len);

/**
 * Free a buffer iterator handle.
 */
void tgm_buffer_iter_free(tgm_buffer_iter_t *iter);

/**
 * Create a file message iterator from an open TgmFile.
 *
 * Scans the file to locate message boundaries. The file handle remains
 * usable after this call.
 */
tgm_error tgm_file_iter_create(tgm_file_t *file, tgm_file_iter_t **out);

/**
 * Advance the file iterator. On success, fills `out` with a `TgmBytes`
 * buffer containing the raw message bytes (caller owns, free with
 * `tgm_bytes_free`).
 *
 * Returns `TgmError::Ok` when a message is available, `TgmError::EndOfIter`
 * when iteration is exhausted.
 */
tgm_error tgm_file_iter_next(tgm_file_iter_t *iter, tgm_bytes_t *out);

/**
 * Free a file iterator handle.
 */
void tgm_file_iter_free(tgm_file_iter_t *iter);

/**
 * Create an object iterator from raw message bytes.
 *
 * Parses metadata once, then decodes each object on demand when
 * `tgm_object_iter_next` is called. The global metadata from the
 * original message is preserved in each yielded `TgmMessage`.
 */
tgm_error tgm_object_iter_create(const uint8_t *buf,
                                 size_t buf_len,
                                 int32_t verify_hash,
                                 int32_t native_byte_order,
                                 tgm_object_iter_t **out);

/**
 * Advance the object iterator. On success, fills `out` with a `TgmMessage`
 * handle containing exactly one decoded object (the next in sequence).
 *
 * Returns `TgmError::Ok` when an object is available, `TgmError::EndOfIter`
 * when iteration is exhausted. Free each yielded `TgmMessage` with
 * `tgm_message_free`.
 */
tgm_error tgm_object_iter_next(tgm_object_iter_t *iter, tgm_message_t **out);

/**
 * Free an object iterator handle.
 */
void tgm_object_iter_free(tgm_object_iter_t *iter);

/**
 * Convert an error code to a human-readable string.
 * Returns a static string (always valid, never NULL).
 *
 * Accepts a raw integer and matches by value so that invalid discriminants
 * from C callers do not trigger undefined behaviour in Rust.
 */
const char *tgm_error_string(tgm_error err);

/**
 * Compute a hash of the given data.
 * Returns `TGM_ERROR_OK` on success, fills `out` with a `tgm_bytes_t`
 * containing the hex-encoded hash string (NOT null-terminated).
 * Free with `tgm_bytes_free`.
 */
tgm_error tgm_compute_hash(const uint8_t *data,
                           size_t data_len,
                           const char *algo,
                           tgm_bytes_t *out);

/**
 * Create a streaming encoder writing to a file.
 *
 * `metadata_json` must contain `"version"` key (and optional extra keys,
 * but NOT `"descriptors"`).
 *
 * `hash_algo`: null-terminated string ("xxh3") or NULL for no hash.
 *
 * On success fills `out` with a `TgmStreamingEncoder` handle.
 * Free with `tgm_streaming_encoder_free` or finalize with
 * `tgm_streaming_encoder_finish`.
 */
tgm_error tgm_streaming_encoder_create(const char *path,
                                       const char *metadata_json,
                                       const char *hash_algo,
                                       uint32_t threads,
                                       bool reject_nan,
                                       bool reject_inf,
                                       tgm_streaming_encoder_t **out);

/**
 * Write a PrecederMetadata frame for the next data object.
 *
 * `metadata_json` is a JSON object with per-object metadata keys
 * (e.g. `{"mars": {"param": "2t"}, "units": "K"}`).  The keys
 * become `payload[0]` in a GlobalMetadata CBOR with empty `common`.
 *
 * Must be followed by exactly one `tgm_streaming_encoder_write` call
 * before another preceder or `tgm_streaming_encoder_finish`.
 */
tgm_error tgm_streaming_encoder_write_preceder(tgm_streaming_encoder_t *enc,
                                               const char *metadata_json);

/**
 * Write a single data object to the streaming encoder.
 *
 * `descriptor_json` is a JSON object with the descriptor fields
 * (type, ndim, shape, strides, dtype, byte_order, encoding, filter,
 * compression, etc.).
 */
tgm_error tgm_streaming_encoder_write(tgm_streaming_encoder_t *enc,
                                      const char *descriptor_json,
                                      const uint8_t *data,
                                      size_t data_len);

/**
 * Write a single pre-encoded data object to the streaming encoder.
 *
 * Like `tgm_streaming_encoder_write`, but `data` must already be encoded
 * according to the descriptor's pipeline (`encoding` / `filter` /
 * `compression`). The library does not run the encoding pipeline — it
 * validates the descriptor's pipeline configuration and writes the bytes
 * as-is into a data object frame. The hash (if configured on the encoder)
 * is recomputed over the caller's bytes.
 *
 * `descriptor_json`: same JSON schema as `tgm_streaming_encoder_write`.
 *
 * For `szip` compression, callers SHOULD include `szip_block_offsets`
 * (bit offsets, not byte offsets) in the descriptor's params so that
 * `tgm_decode_range` can locate compressed block boundaries later.
 * Other pipeline params (e.g. `simple_packing` reference value, scale
 * factors) must also be present in the descriptor.
 *
 * Any `hash` field embedded in the descriptor JSON is ignored — the
 * library always recomputes the hash from the caller's bytes.
 */
tgm_error tgm_streaming_encoder_write_pre_encoded(tgm_streaming_encoder_t *enc,
                                                  const char *descriptor_json,
                                                  const uint8_t *data,
                                                  size_t data_len);

/**
 * Return the number of objects written so far.
 */
size_t tgm_streaming_encoder_count(const tgm_streaming_encoder_t *enc);

/**
 * Finalize the streaming encoder, writing footer and closing the file.
 *
 * After calling this, the handle is still valid but empty — the caller
 * must still call `tgm_streaming_encoder_free` to release it.
 */
tgm_error tgm_streaming_encoder_finish(tgm_streaming_encoder_t *enc);

/**
 * Free a streaming encoder without finalizing (abandons the output).
 */
void tgm_streaming_encoder_free(tgm_streaming_encoder_t *enc);

/**
 * Validate a single Tensogram message buffer.
 *
 * `buf` / `buf_len`: the wire-format message bytes (single message).
 *   `buf` may be NULL when `buf_len` is 0 (empty-buffer validation).
 * `level`: validation depth — null-terminated C string:
 *   `"quick"` (structure only), `"default"` (up to hash check),
 *   `"checksum"` (hash check, suppress structural warnings),
 *   `"full"` (full decode + NaN/Inf scan). NULL defaults to `"default"`.
 * `check_canonical`: non-zero to check RFC 8949 CBOR key ordering.
 * `out`: receives UTF-8 JSON bytes describing the validation report.
 *   Not NUL-terminated — use `out->len` for the byte count.
 *   Free with `tgm_bytes_free`.
 *
 * Returns `TGM_ERROR_OK` on success (even if the message has issues —
 * the issues are in the JSON report). Returns `TGM_ERROR_INVALID_ARG`
 * for argument validation failures (null pointers, invalid level string),
 * or `TGM_ERROR_ENCODING` if JSON serialization of the report fails.
 */
tgm_error tgm_validate(const uint8_t *buf,
                       size_t buf_len,
                       const char *level,
                       int32_t check_canonical,
                       tgm_bytes_t *out);

/**
 * Validate all messages in a `.tgm` file.
 *
 * `path`: null-terminated UTF-8 path to the file.
 * `level`: validation depth (same as `tgm_validate`). NULL = `"default"`.
 * `check_canonical`: non-zero to check CBOR key ordering.
 * `out`: receives UTF-8 JSON bytes describing the file validation report.
 *   Not NUL-terminated — use `out->len` for the byte count.
 *   Free with `tgm_bytes_free`.
 *
 * Returns `TGM_ERROR_OK` on success (issues are in the JSON).
 * Returns `TGM_ERROR_IO` if the file cannot be opened or read.
 * Returns `TGM_ERROR_INVALID_ARG` for null pointers or invalid level.
 * Returns `TGM_ERROR_ENCODING` if JSON serialization of the report fails.
 */
tgm_error tgm_validate_file(const char *path,
                            const char *level,
                            int32_t check_canonical,
                            tgm_bytes_t *out);

#endif  /* TENSOGRAM_H */
