/// Example 01 — Basic encode / decode round-trip (C++)
///
/// Encodes a 100×200 float32 temperature grid into a Tensogram message,
/// transmits it across a socket (simulated by a byte vector here), and
/// decodes it on the receiving side.
///
/// NOTE: Requires tensogram-ffi (not yet implemented).
///       This file documents the intended C FFI API.

#include <cassert>
#include <cstdio>
#include <cstring>
#include <vector>
#include <stdexcept>

// Planned FFI header (generated by cbindgen from tensogram-ffi)
#include "tensogram.h"

/// RAII wrapper so we don't forget to call tgm_message_free().
struct Message {
    tgm_message_t *ptr = nullptr;
    explicit Message(tgm_message_t *p) : ptr(p) {}
    ~Message() { if (ptr) tgm_message_free(ptr); }
    Message(const Message&) = delete;
    Message& operator=(const Message&) = delete;
};

/// Check tgm_error_t and throw on failure.
static void check(tgm_error_t err, const char *context) {
    if (err != TGM_OK) {
        char buf[256];
        std::snprintf(buf, sizeof(buf), "%s: %s", context, tgm_error_string(err));
        throw std::runtime_error(buf);
    }
}

int main() {
    // ── 1. Prepare data ───────────────────────────────────────────────────────
    constexpr int ROWS = 100, COLS = 200;
    constexpr int N = ROWS * COLS;

    std::vector<float> temps(N);
    for (int i = 0; i < N; ++i)
        temps[i] = 273.15f + static_cast<float>(i) * 0.001f;

    const uint8_t *data_ptr = reinterpret_cast<const uint8_t*>(temps.data());
    size_t data_len = N * sizeof(float);

    // ── 2. Describe the tensor as JSON metadata ───────────────────────────────
    //
    // The C API accepts JSON for metadata to avoid forcing callers to link
    // against ciborium. The library converts JSON → CBOR internally.
    const char *metadata_json = R"({
        "version": 1,
        "objects": [{
            "type": "ntensor",
            "ndim": 2,
            "shape": [100, 200],
            "strides": [200, 1],
            "dtype": "float32",
            "mars": {"param": "2t", "levtype": "sfc"}
        }],
        "payload": [{
            "byte_order": "big",
            "encoding": "none",
            "filter": "none",
            "compression": "none"
        }],
        "mars": {
            "class": "od",
            "type": "fc",
            "date": "20260401",
            "step": 6
        }
    })";

    // ── 3. Encode ─────────────────────────────────────────────────────────────
    uint8_t *msg_buf = nullptr;
    size_t   msg_len = 0;
    const uint8_t *data_ptrs[] = { data_ptr };
    size_t         data_lens[] = { data_len };

    check(
        tgm_encode(metadata_json, data_ptrs, data_lens, 1, &msg_buf, &msg_len),
        "tgm_encode"
    );

    std::printf("Encoded: %zu bytes\n", msg_len);
    std::printf("Magic:   %.8s\n", reinterpret_cast<char*>(msg_buf));
    std::printf("Term:    %.8s\n", reinterpret_cast<char*>(msg_buf + msg_len - 8));

    // ── 4. Decode ─────────────────────────────────────────────────────────────
    tgm_message_t *raw_msg = nullptr;
    check(tgm_decode(msg_buf, msg_len, &raw_msg), "tgm_decode");
    Message msg(raw_msg);

    // ── 5. Inspect the decoded message ───────────────────────────────────────
    size_t num_objects = tgm_message_num_objects(msg.ptr);
    std::printf("Objects: %zu\n", num_objects);
    assert(num_objects == 1);

    size_t ndim = tgm_object_ndim(msg.ptr, 0);
    const uint64_t *shape = tgm_object_shape(msg.ptr, 0);
    const char     *dtype = tgm_object_dtype(msg.ptr, 0);
    std::printf("  Object 0: ndim=%zu  shape=[%llu, %llu]  dtype=%s\n",
                ndim, (unsigned long long)shape[0],
                (unsigned long long)shape[1], dtype);

    // ── 6. Access raw data ────────────────────────────────────────────────────
    size_t decoded_len = 0;
    const uint8_t *decoded = tgm_object_data(msg.ptr, 0, &decoded_len);

    assert(decoded_len == data_len);
    assert(std::memcmp(decoded, data_ptr, data_len) == 0);
    std::printf("Data:    %zu bytes — round-trip OK\n", decoded_len);

    // ── 7. Free the encoded buffer ────────────────────────────────────────────
    tgm_free(msg_buf);

    return 0;
}
