// (C) Copyright 2026- ECMWF and individual contributors.
//
// This software is licensed under the terms of the Apache Licence Version 2.0
// which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
// In applying this licence, ECMWF does not waive the privileges and immunities
// granted to it by virtue of its status as an intergovernmental organisation nor
// does it submit to any jurisdiction.

/**
 * Cross-language metadata-access parity — TypeScript side.
 *
 * Decodes the shared fixture `tests/fixtures/metadata_parity.tgm` (generated by
 * `tests/fixtures/gen_metadata_parity.py`) and asserts the same capability
 * matrix the Rust oracle (`rust/tensogram/tests/metadata_parity.rs`) and Python
 * (`python/tests/test_metadata_parity.py`) assert against the identical bytes.
 * See `plans/METADATA_ACCESS_PARITY.md` §7.
 */

import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { beforeAll, describe, expect, it } from 'vitest';
import {
  decodeMetadata,
  getMetaBool,
  getMetaFloat,
  getMetaInt,
  getMetaKey,
  getMetaKeyAt,
  getMetaString,
  hasMetaKey,
  hasMetaKeyAt,
  init,
} from '../src/index.js';
import type { GlobalMetadata } from '../src/index.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const FIXTURE = join(__dirname, '../../tests/fixtures/metadata_parity.tgm');

describe('metadata parity — shared fixture', () => {
  let meta: GlobalMetadata;

  beforeAll(async () => {
    await init();
    meta = decodeMetadata(readFileSync(FIXTURE));
  });

  it('object count', () => {
    expect(meta.base?.length).toBe(2);
  });

  it('existence: absent is distinct from a real 0 / ""', () => {
    expect(hasMetaKey(meta, 'shortName')).toBe(true);
    expect(hasMetaKey(meta, 'level')).toBe(true); // 0
    expect(hasMetaKey(meta, 'note')).toBe(true); // ""
    expect(hasMetaKey(meta, 'missing')).toBe(false);
  });

  it('message-level typed access (no coercion)', () => {
    expect(getMetaString(meta, 'shortName')).toBe('2t'); // base[0] wins
    expect(getMetaInt(meta, 'level')).toBe(0);
    expect(getMetaString(meta, 'note')).toBe('');
    expect(getMetaInt(meta, 'count')).toBe(-5);
    expect(getMetaInt(meta, 'big')).toBe(2147483648);
    expect(getMetaFloat(meta, 'ratio')).toBe(0.5);
    expect(getMetaInt(meta, 'ratio')).toBeUndefined(); // no coercion
    expect(getMetaBool(meta, 'flag')).toBe(true);
    expect(getMetaString(meta, 'level')).toBeUndefined(); // wrong type != absent
  });

  it('nested map + array', () => {
    expect(getMetaKey(meta, 'mars.class')).toBe('od');
    expect(getMetaKey(meta, 'levels')).toEqual([1000, 850, 500]);
  });

  it('extra fallback + explicit prefix', () => {
    expect(getMetaKey(meta, 'source')).toBe('parity-fixture');
    expect(getMetaKey(meta, 'extra.source')).toBe('parity-fixture');
  });

  it('_reserved_ hidden from path getters, visible via base[i]', () => {
    expect(hasMetaKey(meta, '_reserved_.tensor')).toBe(false);
    expect(hasMetaKeyAt(meta, 0, '_reserved_.tensor')).toBe(false);
    const tensor = (meta.base?.[0]?._reserved_ as Record<string, any> | undefined)?.tensor;
    expect(tensor?.dtype).toBe('float32');
    expect(tensor?.shape).toEqual([2, 3]);
  });

  it('per-object scoping', () => {
    expect(getMetaKeyAt(meta, 0, 'shortName')).toBe('2t');
    expect(getMetaKeyAt(meta, 1, 'shortName')).toBe('msl');
    expect(getMetaKeyAt(meta, 0, 'mars.class')).toBe('od');
    expect(getMetaKeyAt(meta, 1, 'mars.class')).toBe('ea');
    expect(hasMetaKeyAt(meta, 0, 'only0')).toBe(true);
    expect(hasMetaKeyAt(meta, 1, 'only0')).toBe(false);
    expect(getMetaKeyAt(meta, 1, 'only0')).toBeUndefined();
  });
});
