# (C) Copyright 2026- ECMWF and individual contributors.
#
# This software is licensed under the terms of the Apache Licence Version 2.0
# which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
# In applying this licence, ECMWF does not waive the privileges and immunities
# granted to it by virtue of its status as an intergovernmental organisation nor
# does it submit to any jurisdiction.

"""Cross-language metadata-access parity — Python side.

Decodes the shared fixture `tests/fixtures/metadata_parity.tgm` (generated by
`tests/fixtures/gen_metadata_parity.py`) and asserts the same capability matrix
the Rust oracle (`rust/tensogram/tests/metadata_parity.rs`) and TypeScript
(`typescript/tests/metadataParity.test.ts`) assert against the identical bytes.
See `plans/METADATA_ACCESS_PARITY.md` §7.
"""

from __future__ import annotations

from pathlib import Path

import pytest
import tensogram

FIXTURE = Path(__file__).resolve().parents[2] / "tests" / "fixtures" / "metadata_parity.tgm"


@pytest.fixture
def meta() -> tensogram.Metadata:
    return tensogram.decode_metadata(FIXTURE.read_bytes())


def test_object_count(meta) -> None:
    assert meta.num_objects == 2
    assert len(meta.base) == 2


def test_existence_absent_distinct_from_zero_or_empty(meta) -> None:
    assert meta.has_path("shortName")
    assert meta.has_path("level")  # value is 0
    assert meta.has_path("note")  # value is ""
    assert not meta.has_path("missing")


def test_message_level_typed_access(meta) -> None:
    assert meta.get_path("shortName") == "2t"  # base[0] wins
    assert meta.get_path("level") == 0
    assert meta.get_path("note") == ""
    assert meta.get_path("count") == -5
    assert meta.get_path("big") == 2147483648
    assert meta.get_path("ratio") == 0.5
    assert meta.get_path("flag") is True
    assert meta.get_path("missing", "fallback") == "fallback"


def test_nested_and_array(meta) -> None:
    assert meta.get_path("mars.class") == "od"
    assert meta.get_path("mars") == {"class": "od", "stream": "oper"}
    assert meta.get_path("levels") == [1000, 850, 500]


def test_extra_fallback_and_prefix(meta) -> None:
    assert meta.get_path("source") == "parity-fixture"
    assert meta.get_path("extra.source") == "parity-fixture"


def test_reserved_hidden_from_path_visible_in_base(meta) -> None:
    assert not meta.has_path("_reserved_.tensor")
    assert not meta.has_path_at(0, "_reserved_.tensor")
    assert "_reserved_" in meta.base[0]
    assert meta.base[0]["_reserved_"]["tensor"]["dtype"] == "float32"
    assert meta.base[0]["_reserved_"]["tensor"]["shape"] == [2, 3]


def test_per_object_scoping(meta) -> None:
    assert meta.get_path_at(0, "shortName") == "2t"
    assert meta.get_path_at(1, "shortName") == "msl"
    assert meta.get_path_at(0, "mars.class") == "od"
    assert meta.get_path_at(1, "mars.class") == "ea"
    assert meta.has_path_at(0, "only0")
    assert not meta.has_path_at(1, "only0")
    assert meta.get_path_at(1, "only0") is None


def test_mapping_protocol(meta) -> None:
    assert "shortName" in meta
    assert meta["shortName"] == "2t"
    assert meta.get("missing") is None
    assert "source" in set(meta.keys())
