name: Publish tensogram-anemoi to PyPI

on:
  workflow_dispatch:

jobs:
  anemoi:
    uses: ecmwf/reusable-workflows/.github/workflows/cd-pypi.yml@3832c3c496db0f664f53734211df431fe9eef868
    with:
      working-directory: python/tensogram-anemoi/
    secrets: inherit
