name: Publish tensogram-xarray and tensogram-zarr to PyPI

on:
  workflow_dispatch:

jobs:
  xarray:
    uses: ecmwf/reusable-workflows/.github/workflows/cd-pypi.yml@main
    with:
      working-directory: python/tensogram-xarray/
    secrets: inherit

  zarr:
    uses: ecmwf/reusable-workflows/.github/workflows/cd-pypi.yml@main
    with:
      working-directory: python/tensogram-zarr/
    secrets: inherit
